apache/samza

samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/CliConstants.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/CliEnvironment.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/CliShell.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/CliShellEnvironmentVariableHandler.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/CliView.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/Main.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/QueryResultLogView.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/impl/SamzaExecutor.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/EnvironmentVariableHandler.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/EnvironmentVariableHandlerImpl.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/EnvironmentVariableSpecs.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/ExecutorException.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/NonQueryResult.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/QueryResult.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/SqlExecutor.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/util/Pair.java
samza-sql-shell/src/test/java/org/apache/samza/sql/client/impl/SamzaExecutorTest.java

1. User can now set environment variables for the shell itself and for any SqlExecutor, by executing the '`SET`' command in the shell or by using a configuration file. User can also choose to use any SqlExecutor they want in the same way. 
2. Refine the abstraction of environment variables. New interfaces and abstract classes are added so the shell itself and any SqlExecutor can now give a specification about what variables they support, what the possible values are, the default value, and whether they accept unknown variables or not. The shell and SqlExecutors now handle environment variables in a consistent way.
3. The `SET` command controls environment variables which affects corresponding behaviors of the Shell. Conforming to Unix philosophy, the usage and behavior of command `SET` is …

SAMZA-2027: Supports environment variables for SqlExecutors. 

---

samza-core/src/test/java/org/apache/samza/zk/TestZkUtils.java

@shanthoosh @cameronlee314 @xinyuiscool increased timeout for test zk connection, stops swallowing of exceptions.

SAMZA-2095: Update timeout for flaky test ZK connection test

---

samza-api/src/main/java/org/apache/samza/system/SystemConsumer.java
samza-core/src/main/scala/org/apache/samza/config/JobConfig.scala
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/scala/org/apache/samza/storage/TestTaskStorageManager.scala
samza-core/src/test/scala/org/apache/samza/system/TestSystemConsumers.scala

This is a followup PR to address the comments from #869. It is comprised of the following changes:
1. SAMZA-1985 introduced startpoint abstraction, a comprehensive mechanism to define starting positions for a input SystemStreamPartition in samza. This patch merely adds the register(SystemStreamPartition, Startpoint) API to SystemConsumer. 
2. Removes the default metadata store defined for startpoints. This is helpful in not creating the unnecessary metastore connections as a part of container initialization before the startpoint feature is fully completed.
Follow-ups:
1. In a follow-up PR,  new register API and start-point visitors will be implemented for different I/O connectors.
2. Usages of SystemConsumer#register(SystemStreamPartition, offset) is very wide-spread in samza codebase. …

SAMZA-2083: Adds the register(SystemStreamPartition, startpoint) API to the SystemConsumer.

---

samza-api/src/main/java/org/apache/samza/sql/udfs/SamzaSqlUdf.java
samza-api/src/main/java/org/apache/samza/sql/udfs/SamzaSqlUdfMethod.java
samza-api/src/main/java/org/apache/samza/sql/udfs/ScalarUdf.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlExecutionContext.java
samza-sql/src/main/java/org/apache/samza/sql/fn/BuildOutputRecordUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/ConvertToStringUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/FlattenUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/GetSqlFieldUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/RegexMatchUdf.java
samza-sql/src/main/java/org/apache/samza/sql/impl/ConfigBasedUdfResolver.java
samza-sql/src/main/java/org/apache/samza/sql/interfaces/UdfMetadata.java
samza-sql/src/main/java/org/apache/samza/sql/planner/QueryPlanner.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlScalarFunctionImpl.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlUdfOperatorTable.java
samza-sql/src/test/java/org/apache/samza/sql/runner/TestSamzaSqlApplicationConfig.java
samza-sql/src/test/java/org/apache/samza/sql/util/MyTestArrayUdf.java
samza-sql/src/test/java/org/apache/samza/sql/util/MyTestPolyUdf.java
samza-sql/src/test/java/org/apache/samza/sql/util/MyTestUdf.java
samza-sql/src/test/java/org/apache/samza/sql/util/SamzaSqlTestConfig.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

This PR adds following capabilities to UDF
1. Adds typed UDFS : Previously samza sql udfs were un-typed all the params used to be Objects, Although this allowed flexibility of polymorphism without having to implement multiple methods. This was fragile. We couldn't do validations during initialization phase. This change adds types to the UDFs.
2. Decouples name of the method from udf: previously all udf methods have to be named "execute". Now the Udfs methods can be named whatever the developer prefers. The UDFMethods are identified using the annotation. 
3. Adds polymorphism to UDFs : Adds capability where you can have mulitple methods for the same UDF name. i.e. multiple methods within the class can be annotated as SamzaSQLUDFMethod.
4. Minor : Adds description to the UDF. which can be …

Support for types in Samza SQL UDF

---

samza-aws/src/main/java/org/apache/samza/system/kinesis/consumer/KinesisRecordProcessor.java
samza-aws/src/main/java/org/apache/samza/system/kinesis/consumer/KinesisSystemConsumer.java
samza-aws/src/main/java/org/apache/samza/system/kinesis/consumer/KinesisSystemConsumerOffset.java
samza-aws/src/main/java/org/apache/samza/system/kinesis/consumer/SSPAllocator.java
samza-aws/src/main/java/org/apache/samza/system/kinesis/descriptors/KinesisInputDescriptor.java
samza-aws/src/main/java/org/apache/samza/system/kinesis/descriptors/KinesisSystemDescriptor.java
samza-aws/src/test/java/org/apache/samza/system/kinesis/consumer/TestKinesisRecordProcessor.java
samza-aws/src/test/java/org/apache/samza/system/kinesis/consumer/TestKinesisSystemConsumer.java

1. Redundant things removed
2. Several methods simplified
3. Condition ``if (numRecordsPerShard > 0)`` in ``TestKinesisSystemConsumer.java``  was removed because it is always true (there is same check at line 130 and return in else block in case it is false). 
4. Deprecated ``onCheckpoint`` method was replaced with ``afterCheckpoint``

SAMZA-2103: [samza-aws] code cleanup and refactoring

---

samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
samza-sql/src/test/java/org/apache/samza/sql/avro/TestAvroRelConversion.java
samza-sql/src/test/java/org/apache/samza/sql/avro/schemas/ComplexRecord.avsc
samza-sql/src/test/java/org/apache/samza/sql/avro/schemas/ComplexRecord.java
samza-sql/src/test/java/org/apache/samza/sql/system/TestAvroSystemFactory.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

1. Fix the bug in AvroRelConverter where it throws when a union type has a subRecord
2. Adding a test case with union type with a subrecord.

End to end test case for union type with subRecord

---

samza-api/src/main/java/org/apache/samza/config/Config.java

Config is supposed to be immutable, but method Map#replaceAll in its default implementation mutates the config. Code to check:
```
Map<String, String> m = new HashMap<String, String>() {
{
put("foo1", "val1");
put("baz2", "val3");
}
};
Config conf = new MapConfig(m);
conf.replaceAll((key,value) -> "newValue");
System.out.println(conf); // {baz2=newValue, foo1=newValue}
```

Make config immutable again

---

samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
samza-sql/src/test/java/org/apache/samza/sql/avro/TestAvroRelConversion.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlRemoteTable.java

Right now Samza SQL AvroRelConverter transforms the records with null values into null records. I think this was added to support `select * from` usecase when the input has null records, But ideally that should be supported through a mechanism where the entire record is passed as null from input to the output rather than add a current hack where we are flattening the record with null values into null record.

Records with all null values are transformed to null records

---

samza-sql/src/main/java/org/apache/samza/sql/SamzaSqlInputTransformer.java

IncomingMessageEnvelope uses 0L for non-present event/arrival times. 
The SamzaSqlInputTransformer should check for that and assign the SamzaSqlRelMsgMetadata corresponding fields accordingly. This PR fixes this.

[SAMZA-2114] Samza-Sql Diagnostics: SamzaSqlInputTransformer to check presence of event and arrival time in ime

---

samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlRelMsgMetadata.java
samza-sql/src/main/java/org/apache/samza/sql/runner/SamzaSqlApplicationConfig.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ProjectTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/QueryTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ScanTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/TranslatorInputMetricsMapFunction.java
samza-sql/src/main/java/org/apache/samza/sql/translator/TranslatorOutputMetricsMapFunction.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

This method adds the System message metadata to the SamzaSQLRelMessageMetadata and uses the metadata to directly send these system messages to output stream directly bypassing the Samza SQL processing pipeline.

Propogating the system messages to the stream.

---

samza-core/src/main/java/org/apache/samza/task/AsyncRunLoop.java
samza-test/src/test/java/org/apache/samza/test/processor/TestTaskApplication.java
samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java

A samza container is comprised of multiple tasks and event-loop. Event loop is the main orchestration layer between the different stages of a task(process, commit, window) and delivers messages to task by polling them from different consumers. 
Currently in samza, the event loop dispatches messages to the tasks as per user-defined configuration `task.max.concurrency`. After dispatching messages with count equal to `task.max.concurrency` to the tasks,  the event loop is blocked until the processing of at-least a single dispatched message finishes(aka the task implementation invokes `taskCallBack.complete()` for at-least a dispatched message). 
When the event loop is blocked by this, the user thread would sometimes try to shutdown the event loop. This shutdown intent marked by the …

SAMZA-2118: Improve the shutdown sequence of AsyncRunLoop.

---

samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/scala/org/apache/samza/container/TestTaskInstance.scala

Currently the TaskInstance.checkCaughtUp() logic has a bug that if there is no incoming messages for a partition, it will not mark the ssp to be caught up. Instead, it should mark ssp to be caught up if the starting offset is already the upcoming offset for a ssp, meaning it has consumed all the messages in this partition and waiting for the future incoming messages. This indicates the ssp is fully caught up.

SAMZA-2122: Fix the task caught-up logic which doesn't handle no incoming messages

---

README.md
RELEASE.md
docs/contribute/tests.md
docs/learn/tutorials/versioned/remote-debugging-samza.md

Post 1.0, samza does not support scala 2.10 version. This patch removes the references of the scala 2.10 version from the documentation.

Remove scala 2.10 version from documentation.

---

samza-core/src/main/java/org/apache/samza/execution/StreamEdge.java
samza-core/src/test/java/org/apache/samza/execution/TestStreamEdge.java
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemAdmin.java
samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaSystemFactory.scala
samza-kafka/src/main/scala/org/apache/samza/system/kafka_deprecated/KafkaSystemAdmin.scala
samza-kafka/src/main/scala/org/apache/samza/system/kafka_deprecated/KafkaSystemFactory.scala
samza-kafka/src/test/java/org/apache/samza/system/kafka/TestKafkaSystemFactoryJava.java

- Kafka properties doesn't support replication.factor when creating topic, so change the way to override intermediate stream properties. 
- Due to planner created twice, we need to check the physical stream name has been created for intermediate streams to avoid the run.id got appended twice.

SAMZA-2126: Bug fixes for batch-mode generated stream specs

---

samza-core/src/main/java/org/apache/samza/system/SystemAdmins.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/java/org/apache/samza/task/TestAsyncRunLoop.java
samza-core/src/test/scala/org/apache/samza/processor/StreamProcessorTestUtils.scala
samza-core/src/test/scala/org/apache/samza/system/TestSystemConsumers.scala

This patch is comprised of the following changes:
* Moves the offset comparison check to SystemConsumers
* Currently the offset comparator check to find a lowest for a `SystemStreamPartition` is duplicated in some implementations of  SystemConsumer API.
* Some `SystemConsumer` implementations do not perform this offset comparator check
in the implementation of register method.
* Moving this one level up from `SystemConsumer.register(SystemStreamPartition, offset)` API implementation to  `SystemConsumers.register(SystemStreamPartition, offset)` API implementation removes unnecessary duplication and ensures functional correctness.
* Fixes to the test-cases in `TestSystemConsumer`.
There should be no functional breakages introduced by moving the offset-comparator check to `SystemConsumers` …

SAMZA-2129: Move the offset comparison check to choose the lowest offset to SystemConsumers.

---

samza-core/src/main/java/org/apache/samza/startpoint/StartpointKey.java
samza-core/src/main/java/org/apache/samza/startpoint/StartpointKeySerializer.java
samza-core/src/test/java/org/apache/samza/startpoint/TestStartpointKey.java

StartpointKey has unnecessary redundancies when serialized. Example: 
```
"{\"systemStreamPartition\":{\"system\":\"test\",\"stream\":\"test\",\"partition\":{\"partitionId\":2},\"systemStream\":{\"system\":\"test\",\"stream\":\"test\"}},\"taskName\":{\"taskName\":\"Partition 2\"}}"
```
The serialized key should should be flattened to 4 elements: system, stream, partition ID and taskName.
@shanthoosh please take a look.

SAMZA-2132: Flatten startpoint key when serialized.

---

samza-core/src/main/java/org/apache/samza/zk/ZkBarrierForVersionUpgrade.java
samza-core/src/main/java/org/apache/samza/zk/ZkCoordinationUtilsFactory.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinatorFactory.java
samza-core/src/main/java/org/apache/samza/zk/ZkStringSerializer.java
samza-core/src/test/java/org/apache/samza/zk/TestZkBarrierForVersionUpgrade.java
samza-core/src/test/java/org/apache/samza/zk/TestZkStringSerializer.java
samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java

This patch is comprised of the following changes: 
1. Switch from using SerializableSerializer to ZkStringSerializer in the zkClient for standalone.
ZkClient uses pluggable serde to serialize/deserialize user-defined types to bytes before it's written to zookeeper. In the current implementation, the predefined SerializableSerializer(which uses the java native serialization) provided as default by the ZkClient library is used by samza-standalone. SerializableSerializer augments special characters  on top of the serialized data as auxiliary data. The presence of these special characters makes the parsing of zookeeper data impossible  when building custom tools in languages(such as python) that does not have java native serializer. To solve this problem, this patch introduces string …

 SAMZA-2091: Update ZkClient in samza-standalone to use string serializer

---

samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala

Example before this fix:
```
2019-03-21 08:36:34.810 [main] JobModelManager$ [INFO] Storing ssp: Partition 1 and task: 0 into metadata store
```

SAMZA-2138: Incorrect logging when task to container mapping is written.

---

RELEASE.md

Currently the RELEASE.md which outlines the samza release process in open-source has the following problems:
* There is no clear separation between the steps that has to be followed before and after the successful vote completion.
* There are formatting errors in the bash commands that has to be executed to validate the release.
This PR fixes the above problems.

SAMZA-2147: Improve the documentation of the samza release process.

---

docs/learn/tutorials/versioned/samza-sql.md

Currently, the bash/sql scripts available in samza-sql release validation page were not using the proper markdown rules and hence they're not rendered properly. 
Please refer to current [samza-sql-validation-page](https://github.com/apache/samza/blob/master/docs/learn/tutorials/versioned/samza-sql.md) to know more about the rendering problems.
We identified this problem during samza-1.1 release-validation and this PR fixes the above problem.

SAMZA-2148: Fix the rendering of bash and sql scripts  in samza-sql release validation page.

---

docs/_menu/index.html
docs/_releases/1.1.0.md

@jmakes @jagadish-v0 @shanthoosh 
Added 1.1.0 version to release tab.

DOCS: Fix release tab

---

samza-api/src/main/java/org/apache/samza/sql/SamzaSqlRelRecord.java
samza-api/src/main/java/org/apache/samza/sql/schema/SqlSchema.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlRelMessage.java
samza-sql/src/main/java/org/apache/samza/sql/planner/QueryPlanner.java
samza-sql/src/main/java/org/apache/samza/sql/planner/RelSchemaConverter.java
samza-sql/src/main/java/org/apache/samza/sql/translator/QueryTranslator.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlRemoteTable.java

1. Commit adds support for deleting records from table by adding a special __op__ field. SQL users can use this field to say whether the row needs to be deleted in the output table. This is a stop mechanism till we support DELETE operation in SQL. 
2. Adds support for pluggable RelProviders to add the special fields __key__. This is useful if the relProvider knows the type of __key__ and wants to set it explicitly.
3. Removes the hack where field positions are incremented by 1 in RelSchemaConverter to support the special field __key__. With this change the knowledge of the special fields exists only in queryTranslator. In future we could consider moving this logic to RelSchemaProvider.

SAMZA-2110 : Support for deleting records from a table

---

samza-core/src/main/java/org/apache/samza/coordinator/stream/CoordinatorStreamSystemConsumer.java
samza-core/src/main/java/org/apache/samza/coordinator/stream/messages/CoordinatorStreamMessage.java
samza-core/src/test/java/org/apache/samza/coordinator/stream/TestCoordinatorStreamMessage.java
samza-core/src/test/java/org/apache/samza/coordinator/stream/TestCoordinatorStreamSystemConsumer.java

1) NPE exposed in `CoordinatorStreamMessage#equals` now that the metadata store allows arbitrary messages to be stored in the coordinator stream. See [SAMZA-2143](https://issues.apache.org/jira/browse/SAMZA-2143) for example NPE stack trace.
2) In `CoordinatorStreamSystemConsumer`, remove unused `getBootstrappedStream` overloaded method and unit test the appropriate method that is actually used in non-test code.
@shanthoosh - please take a look when you get a chance.

SAMZA-2143: Fix NPE in `CoordinatorStreamMessage#equals` and some clean-up to CoordinatorStreamSystemConsumer

---

samza-core/src/main/scala/org/apache/samza/metrics/reporter/MetricsSnapshotReporterFactory.scala

Currently we relying on app.class or task.class to get the version. For beam the app.class is anonymous class which caused exception when loading the class of it. This patch will do a try catch for this exception and use 0.0.1 as default.

SAMZA-2163: Add try-catch to get the version in MetricsSnapshotReporterFactory

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/coordinator/metadatastore/CoordinatorStreamStore.java
samza-core/src/main/java/org/apache/samza/coordinator/stream/CoordinatorStreamValueSerde.java
samza-core/src/main/java/org/apache/samza/coordinator/stream/messages/SetChangelogMapping.java
samza-core/src/main/java/org/apache/samza/storage/ChangelogStreamManager.java
samza-core/src/main/java/org/apache/samza/storage/StorageRecovery.java
samza-core/src/main/scala/org/apache/samza/checkpoint/CheckpointTool.scala
samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala
samza-core/src/main/scala/org/apache/samza/job/local/ProcessJobFactory.scala
samza-core/src/main/scala/org/apache/samza/job/local/ThreadJobFactory.scala
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/java/org/apache/samza/clustermanager/TestClusterBasedJobCoordinator.java
samza-core/src/test/java/org/apache/samza/coordinator/metadatastore/CoordinatorStreamStoreTestUtil.java
samza-core/src/test/java/org/apache/samza/coordinator/stream/MockCoordinatorStreamSystemFactory.java
samza-core/src/test/java/org/apache/samza/coordinator/stream/MockCoordinatorStreamWrappedConsumer.java
samza-core/src/test/scala/org/apache/samza/checkpoint/TestCheckpointTool.scala
samza-core/src/test/scala/org/apache/samza/coordinator/TestJobCoordinator.scala
samza-yarn/src/main/java/org/apache/samza/validation/YarnJobValidationTool.java
samza-yarn/src/test/scala/org/apache/samza/job/yarn/TestSamzaYarnAppMasterService.scala

Currently the metadata of a samza job is stored into a kafka topic named coordinator stream.
In samza-yarn `ApplicationMaster`, the same coordinator stream is read twice as a part of the `ApplicationMaster` startup sequence. This duplicate read unnecessarily prolongs the startup time of the application master and makes the container allocation take longer than usual. This inadvertently incurs a substantial increase in input stream processing delay depending upon the size of the coordinator stream. 
To mitigate this problem, the two util classes in samza viz `ChangelogPartitionManager`, `Config` should be moved to use the MetadataStore abstraction.

SAMZA-2161: Move ChangelogPartitionManager and CoordinatorStream ConfigReader to MetadataStore.

---

samza-kafka/src/main/scala/org/apache/samza/checkpoint/kafka/KafkaCheckpointManager.scala

We read checkpoints at the start of a container for once. We should close the consumer after that so it won't keep filling the BEM with checkpoints written later. Currently I saw a lot of these checkpoint messages in the BEM.

SAMZA-2164: Close the consumer after reading checkpoints

---

samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java

https://github.com/apache/samza/pull/951 introduced a regression in TestZkLocalApplicationRunner by creating topics with 5 partitions instead of 1.

Fix ZkLocalApplicationRunner regression introduced by PR #951

---

samza-core/src/main/java/org/apache/samza/coordinator/stream/messages/CoordinatorStreamMessage.java
samza-core/src/main/java/org/apache/samza/coordinator/stream/messages/SetConfig.java
samza-core/src/test/java/org/apache/samza/coordinator/stream/TestCoordinatorStreamMessage.java

Currently the configurations in the coordinator stream are deleted by sending a  Delete message with  message-map set as null and type set as `SetConfig.TYPE`. 
To read configurations from the coordinator stream, there should be a check at the caller API to find if configuration message has been deleted or not. Otherwise it results in a NPE. 
This patch encapsulates the isDelete check into the CoordinatorStreamMessage class and returns null if the configuration key has been deleted.

SAMZA-2173: Fix NullPointerException in SetConfig MessageFormat when configurations are deleted.

---

samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala

Samza stores the metadata of the job into a log-compacted kafka topic called coordinator stream.
Due to some operational issue, we converted serialized null value into bytes and stored them as values for some keys in the coordinator stream. These keys will not be log-compacted by kafka, since they're not actually null messages. 
This patch ignores the configurations from coordinator stream with serialized-null values and buffers only keys  with non-null values in memory in ApplicationMaster.
Verified the changes in this patch by testing with a samza-hello-samza job by injecting samza-reserved configuration keys with serialized null values into the coordinator stream.  Here is the entire local [testing](https://gist.github.com/shanthoosh/88ef289cb98d6d3be9db9fb76bc04472#file-test-deserializ …

SAMZA-2176: Ignore the configuration keys with serialized null values from the coordinator stream.

---

samza-core/src/test/scala/org/apache/samza/storage/TestTaskStorageManager.scala

The store offset file and format was updated in Samza 1.1 (to consolidate with offset file for side-inputs), and the tests were updated accordingly in #915.
This PR makes the tests parameterized so that they run for both the legacy and the new format of the offset file. The actual change to ensure that apps can rollback from 1.1 to 1.0 without rebootstrapping was checked as part of #1005

Adding tests for legacy store offset file

---

samza-core/src/main/java/org/apache/samza/system/inmemory/InMemoryManager.java
samza-core/src/main/java/org/apache/samza/system/inmemory/InMemorySystemProducer.java
samza-test/src/main/java/org/apache/samza/test/framework/TestRunner.java
samza-test/src/test/java/org/apache/samza/test/framework/StreamTaskIntegrationTest.java

Please read the jira tagged for description: https://issues.apache.org/jira/browse/SAMZA-2178
Use cases where this is helpful: 
Systems like Brooklin at LinkedIn where they have a custom BrooklinIncomingMessageEnvelope (BIMEs), this helps to directly feed BIMEs to InMemorySystem for Testing 
@bharathkk @prateekm please have a look when you have time!

SAMZA-2178: Utils to directly inject custom IME to InMemorySystem streams via TestRunner

---

samza-core/src/main/java/org/apache/samza/container/grouper/task/GroupByContainerCount.java

print all task models when job fails with incorrect container count

SAMZA-2183: print all tasks when job fails validation

---

samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/scala/org/apache/samza/container/TestTaskInstance.scala
samza-core/src/test/scala/org/apache/samza/system/TestSystemConsumers.scala

This patch is comprised of the following changes:
* Integrates the resolving startpoints to offset workflow to container startup sequence.
* Either if the startpoint does not exist for a (taskname, system-stream-partition) or the startpoint resolution fails, then the checkpointed offset is used as starting offset 
* Added unit-tests to validate the altered starting offset computation flow for a partition.

SAMZA-2189: Integrate startpoint resolution workflow with SamzaContainer startup sequence.

---

samza-api/src/main/java/org/apache/samza/table/descriptors/RemoteTableDescriptor.java
samza-core/src/test/java/org/apache/samza/table/remote/descriptors/TestRemoteTableDescriptor.java
samza-sql/src/test/java/org/apache/samza/sql/util/RemoteStoreIOResolverTestFactory.java
samza-test/src/test/java/org/apache/samza/test/table/TestRemoteTableEndToEnd.java

By default rate limiter will be enabled. The user need to provide a rate limiter for the
table descriptor or disable read/write rate limiter explicitly.

SAMZA-2134:Enable table rate limiter by default.

---

samza-core/src/test/java/org/apache/samza/table/remote/descriptors/TestRemoteTableDescriptor.java
samza-test/src/test/java/org/apache/samza/test/table/TestCouchbaseRemoteTableEndToEnd.java

A recent code merge makes rate limiter as a required config. It break some
new tests that are added after that PR is created and checked in before that PR is commited.

SAMZA-2193: Fix unit-test failure after making rate limiter as a required config

---

docs/learn/documentation/versioned/api/table-api.md
samza-api/src/main/java/org/apache/samza/table/batching/Batch.java
samza-api/src/main/java/org/apache/samza/table/batching/BatchProvider.java
samza-api/src/main/java/org/apache/samza/table/batching/Operation.java
samza-api/src/main/java/org/apache/samza/table/descriptors/RemoteTableDescriptor.java
samza-core/src/main/java/org/apache/samza/table/batching/AbstractBatch.java
samza-core/src/main/java/org/apache/samza/table/batching/AsyncBatchingTable.java
samza-core/src/main/java/org/apache/samza/table/batching/BatchHandler.java
samza-core/src/main/java/org/apache/samza/table/batching/BatchMetrics.java
samza-core/src/main/java/org/apache/samza/table/batching/BatchNotSupportedException.java
samza-core/src/main/java/org/apache/samza/table/batching/BatchProcessor.java
samza-core/src/main/java/org/apache/samza/table/batching/BatchingNotSupportedException.java
samza-core/src/main/java/org/apache/samza/table/batching/CompactBatch.java
samza-core/src/main/java/org/apache/samza/table/batching/CompactBatchProvider.java
samza-core/src/main/java/org/apache/samza/table/batching/CompleteBatch.java
samza-core/src/main/java/org/apache/samza/table/batching/CompleteBatchProvider.java
samza-core/src/main/java/org/apache/samza/table/batching/DeleteOperation.java
samza-core/src/main/java/org/apache/samza/table/batching/GetOperation.java
samza-core/src/main/java/org/apache/samza/table/batching/PutOperation.java
samza-core/src/main/java/org/apache/samza/table/batching/TableBatchHandler.java
samza-core/src/main/java/org/apache/samza/table/remote/RemoteTable.java
samza-core/src/main/java/org/apache/samza/table/remote/RemoteTableProvider.java
samza-core/src/main/java/org/apache/samza/table/utils/TableMetricsUtil.java
samza-core/src/test/java/org/apache/samza/table/batching/TestBatchProcessor.java
samza-core/src/test/java/org/apache/samza/table/batching/TestBatchTable.java
samza-core/src/test/java/org/apache/samza/table/caching/TestCachingTable.java
samza-core/src/test/java/org/apache/samza/table/remote/TestRemoteTable.java
samza-test/src/test/java/org/apache/samza/test/table/TestRemoteTableEndToEnd.java
samza-test/src/test/java/org/apache/samza/test/table/TestRemoteTableWithBatchEndToEnd.java
samza-test/src/test/java/org/apache/samza/test/table/TestTableData.java

Add a CompactBatch class to allow users to compact and batch
the operations sent to the remote store via table APIs.
@weisong44 Please review.

SAMZA-2191: Batch support for table APIs

---

samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/main/scala/org/apache/samza/config/JobConfig.scala

`StartpointManager` instantiation in the `ContainerLaunchUtil` depends on the `MetadataStoreFactory` config which is not currently be used now due to PR #987. This PR switches to using the directly created metadata store to construct the `StartpointManager` that puts it in parity with other managers that use the metadata store.
[SAMZA-2216](https://issues.apache.org/jira/browse/SAMZA-2216) tracks the follow on work to reintegrate the factory.

SAMZA-2215 : StartpointManager fix for previous CoordinatorStreamStore refactor

---

samza-sql/src/test/java/org/apache/samza/sql/system/TestAvroSystemFactory.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

Adding a Samza SQL test case with switch case statement. 
Adding few testcases to test the boolean check behavior which identifies the calcite bug and a workaround for it.

SAMZA-2229: Adding a SQL test case with switch case and Boolean checks

---

bin/merge-pull-request.py

This reverts commit 7aa619564f740ebe5540ad37c13fe8da2550c2ac.
Some committers still use this merge script instead of merging directly
from GitHub, so adding this back for now. We can remove this merge
script once everyone moves to the GitHub flow.

Revert "[Cleanup] Removing merge-pull-request.py script since it is no longer used to merge PRs (see Contributor's Corner doc) (#1028)"

---

samza-api/src/main/java/org/apache/samza/table/remote/BaseTableFunction.java

This is to ensure the field "table" is not included in generated configuration for this table function.

SAMZA-2236: Make member table in BaseTableFunction transient

---

samza-api/src/main/java/org/apache/samza/sql/udfs/ScalarUdf.java
samza-sql/src/main/java/org/apache/samza/sql/data/Expression.java
samza-sql/src/main/java/org/apache/samza/sql/data/RexToJavaCompiler.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlExecutionContext.java
samza-sql/src/main/java/org/apache/samza/sql/fn/BuildOutputRecordUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/ConvertToStringUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/FlattenUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/GetSqlFieldUdf.java
samza-sql/src/main/java/org/apache/samza/sql/fn/RegexMatchUdf.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlScalarFunctionImpl.java
samza-sql/src/main/java/org/apache/samza/sql/translator/FilterTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ProjectTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestFilterTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestProjectTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/util/MyTestArrayUdf.java
samza-sql/src/test/java/org/apache/samza/sql/util/MyTestPolyUdf.java
samza-sql/src/test/java/org/apache/samza/sql/util/MyTestUdf.java

This change provides ability for the UDFs to access the Samza context. Context is needed by the UDFs for various reasons
1. To create metrics
2. To access configs
3. Access any external contexts

SAMZA-2234: Passing context to Samza SQL UDFs

---

samza-shell/src/main/bash/run-class.sh

Samza 1.1.0 on AWS EMR (emr - 5.13.0, amazon 2.8.3, zookeeper 3.4.10) not working because run-class.sh assumes if JAVA_HOME is defined, jar exists under $JAVA_HOME/bin. This turns out not the case.

SAMZA-2245: check jar path under java home

---

samza-sql/src/main/java/org/apache/samza/sql/planner/QueryPlanner.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlOperatorTable.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

There were quite a few basic calcite sql functions that were not included in the original Samza SQL operators that are supported. 
1. Adding these functions to the operator table. 
2. Making the Samza SQL parser lenient to allow !=, %, - and row value operators
3. Adding SqlToRelConverterConfig explicitly so that it is clear that we have opportunity to override this in future if needed.

Samza-2254: Adding relevant calcite functions to Samza SQL

---

samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala
samza-core/src/test/scala/org/apache/samza/container/TestSamzaContainer.scala

This metric is the diff of System.nanoTime() which is a positive long (since the number of nano seconds for which a JVM a running shouldnt be negative). 
Therefore I am using a long for it.

SAMZA-2262: Change container-startup-time to a gauge from a timer and to ms instead of ns

---

.travis.yml

The builds are close to hitting the 30 min timeout limit. This increases the limit to 40 min.

Minor: Increase Travis-CI timeout to 40 min.

---

samza-core/src/main/java/org/apache/samza/clustermanager/AbstractContainerAllocator.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/ResourceRequestState.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerRequestState.java

Fixed the following issue:
1. AM gets extra containers from the RM which it saves for later use
2. When the container that we saved in step1 dies, the AM on receiving this callback does nothing about it.
3. Later, when we are looking for a container to use - we pick up the dead container that we saved and did not clean up (step 1&2) and launch a container. 
4. Now, if this launched container ever dies - the RM will never notify the AM about it since it see's it as a duplicate (step 2)
5. Job is left without the container rescheduled and will need to be restarted.

SAMZA-2248: Fix AM bookkeeping on receiving dead container notifications

---

samza-sql-shell/src/main/java/org/apache/samza/sql/client/cli/CliShell.java
samza-sql/src/main/java/org/apache/samza/sql/impl/ConfigBasedUdfResolver.java
samza-sql/src/main/java/org/apache/samza/sql/interfaces/UdfMetadata.java

Field                | Type
-------------------------------
auditHeader          | ROW(INT64,STRING,STRING,STRING,BYTES,INT32,STRING,STRING)
inviterUrn           | STRING
inviteeUrn           | STRING
invitationType       | STRING
inviterActorUrn      | STRING
invitationTrackingId | BYTES

Support for complex schema in Samza SQL shell for describe command

---

samza-azure/src/main/java/org/apache/samza/coordinator/AzureJobCoordinatorFactory.java
samza-core/src/main/java/org/apache/samza/coordinator/JobCoordinatorFactory.java
samza-core/src/main/java/org/apache/samza/processor/StreamProcessor.java
samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/main/java/org/apache/samza/standalone/PassthroughJobCoordinatorFactory.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinatorFactory.java
samza-core/src/test/java/org/apache/samza/processor/TestStreamProcessor.java
samza-core/src/test/java/org/apache/samza/runtime/TestLocalApplicationRunner.java
samza-core/src/test/java/org/apache/samza/zk/TestZkJobCoordinator.java
samza-sql/src/main/java/org/apache/samza/sql/runner/SamzaSqlApplicationRunner.java
samza-sql/src/test/java/org/apache/samza/sql/util/SamzaSqlTestConfig.java
samza-test/src/main/java/org/apache/samza/test/framework/TestRunner.java
samza-test/src/test/java/org/apache/samza/processor/TestZkStreamProcessorBase.java
samza-test/src/test/java/org/apache/samza/test/samzasql/SamzaSqlIntegrationTestHarness.java

**Motivation**
The current implementation of the coordinator stream metadata store's `init()` method is an expensive call as it bootstraps the full coordinator stream. We want to invoke init() only once during the entire lifecycle of a standalone application.
**Implementation**
This PR instantiates the coordinator stream metadata store from the scope of the top-level `LocalApplicationRunner`. This allows other components, such as `StreamProcessor`, `JobCoordinator`, `SamzaContainer`, `StartpointManager` and other managers, to use the coordinator stream metadata store freely without needing to manage its lifecycle.
**Note**
Currently there are split responsibilities between a ZK metadata store and the coordinator stream metadata store. The former is required for JobModel and run.id because …

SAMZA-2260: Standalone - coordinator stream metadata store lifecycle

---

samza-core/src/main/java/org/apache/samza/startpoint/StartpointManager.java
samza-core/src/test/java/org/apache/samza/startpoint/TestStartpointManager.java

Added a "delete all" for startpoints so we have the ability to delete all in case we run into situations where the startpoints poses a problem for the job.

SAMZA-2278: Delete all for startpoints and fan outs.

---

samza-api/src/main/java/org/apache/samza/system/IncomingMessageEnvelope.java
samza-sql/src/main/java/org/apache/samza/sql/SamzaSqlInputTransformer.java
samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlRelMessage.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlRelMsgMetadata.java
samza-sql/src/main/java/org/apache/samza/sql/translator/FilterTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/LogicalAggregateTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ProjectTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/QueryTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ScanTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/util/TranslatorUtils.java
samza-sql/src/test/java/org/apache/samza/sql/data/TestSamzaSqlRelMessage.java
samza-sql/src/test/java/org/apache/samza/sql/serializers/TestSamzaSqlRelMessageSerde.java
samza-sql/src/test/java/org/apache/samza/sql/serializers/TestSamzaSqlRelRecordSerde.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestFilterTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestProjectTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestSamzaSqlLocalTableJoinFunction.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestSamzaSqlRemoteTableJoinFunction.java

1) Converting timestamps to numerical instead of text
2) fixing latency resolution issue by using nanoTime resolution and reporting micro resolution latencies

[SAMZA-2282] Fixing SamzaSQL Latency Metrics resolution

---

samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java
samza-core/src/test/scala/org/apache/samza/container/TestTaskInstance.scala

**Problem:**
SamzaContainer startup sequence fetches the metadata of same input streams multiple times. Fetching the metadata of a stream entails making a expensive remote call to underlying messaging broker. This redundant fetch-input-stream-metadata API invocations incurred significant delays in the start of actual message processing in the samza job.
**Impact:**
1. With some samza jobs at LinkedIn, we observed that this fetch-input-stream-metadata loop took around 1.5 hrs to complete.
2. The redundant fetch-input-stream-metadata remote API calls will significantly increase the load on the underlying messaging broker.
**Fix:**
This patch fixes the unnecessary delay by fetching the metadata of the input streams only once in SamzaContainer(rather than once per SystemStreamPartition per …

SAMZA-2284: Remove redundant getStreamMetadata calls in SamzaContainer startup sequence.

---

samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java

The containerlaunchutil.run method got refactored without taking into accounts its invocation from BeamContainerRunner

Adding method to enable ContainerLaunchUtil to work with current BeamContainerRunner

---

samza-sql/src/main/java/org/apache/samza/sql/util/SamzaSqlQueryParser.java
samza-sql/src/test/java/org/apache/samza/sql/util/TestSamzaSqlQueryParser.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

SamzaSQLQueryParser uses a brittle regEx parsing to fetch the SQL statement from the SQL. Removing this Regex parsing and use the string generated from SqlSelect node.

Samza-2287: Removing RegEx based matching while parsing the sql statement

---

samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/test/java/org/apache/samza/runtime/TestLocalApplicationRunner.java

Certain standalone configurations do not define a `job.coordinator.system` because a coordinator stream is not necessary. For example, in PassthroughJobCoordinator configured jobs or integration test jobs might not have this defined. This PR allows support for such scenarios.
Added additional unit tests and verified by @xinyuiscool with his testing.
@xinyuiscool - Please take a look when you get a chance.

SAMZA-2294: LocalApplicationRunner support for missing coordinator stream

---

samza-test/src/test/scala/org/apache/samza/test/harness/AbstractKafkaServerTestHarness.scala

Build on my local machine went from over 26 minutes to ~23.5 minutes.

SAMZA-2292: [Test improvement] Enable kafka topic deletion for integration test harnesses to improve test run times

---

samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaConsumerProxy.java

Fix for topic lag metrics where topic contains period (.)
`messages-behind-high-watermark` and `high-watermark` are calculated from kafka's `records-lag` consumer metric. In version 1.1 or so, when metrics moved from including the topic name in the metric name to using tags, they added a replacement of period to underscore. See commit :
https://github.com/apache/kafka/commit/5d81639907869ce7355c40d2bac176a655e52074#diff-b45245913eaae46aa847d2615d62cde0R1331
When Samza refactored to match this, the same replacement was not made, so the lookup of the "records-lag" metric in KafkaConsumerProxy fails to find a match.
The related commit on Samza is here:
https://github.com/apache/samza/commit/01c06055057e8c260e73bf3f7db7b9eb53af3745#diff-b56db493dfdd2fd2d471f6df342fe661R400
The fix is a simple …

SAMZA-2295 : records-lag based topic metrics not working for topics with periods (dot, '.') in them

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/coordinator/MetadataResourceUtil.java
samza-core/src/main/java/org/apache/samza/standalone/PassthroughJobCoordinator.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/main/scala/org/apache/samza/job/local/ProcessJobFactory.scala
samza-core/src/main/scala/org/apache/samza/job/local/ThreadJobFactory.scala
samza-core/src/test/java/org/apache/samza/coordinator/TestMetadataResourceUtil.java
samza-core/src/test/java/org/apache/samza/zk/TestZkJobCoordinator.java

**Root cause**
In standalone, the configs are being read from the JobModel, but in the standalone scenario, the config in the JobModel is not populated. The checkpoint and changelog system configurations were attempted to be read from the job model rather than the internally constructed configs.
**Fix**
Use the constructed config rather than the configs from JobModel

SAMZA-2296: Metadata streams not created in Standalone

---

samza-core/src/main/java/org/apache/samza/system/inmemory/InMemoryManager.java
samza-core/src/main/java/org/apache/samza/system/inmemory/InMemorySystemAdmin.java
samza-core/src/main/java/org/apache/samza/system/inmemory/InMemorySystemConsumer.java
samza-core/src/test/java/org/apache/samza/system/inmemory/TestInMemoryManager.java
samza-core/src/test/java/org/apache/samza/system/inmemory/TestInMemorySystemAdmin.java
samza-core/src/test/java/org/apache/samza/system/inmemory/TestInMemorySystemConsumer.java
samza-test/src/main/java/org/apache/samza/test/framework/TestRunner.java

Added unit tests.
Ran a local build to make sure existing usages are still working.
Changed `TestSamzaSqlEndToEnd.testEndToEndStreamTableRightJoin` (which uses intermediate streams) to use in-memory system. Failed before this change, succeeded after this change.

SAMZA-2297: InMemorySystemAdmin offsets are off-by-one in some cases 

---

samza-api/src/main/java/org/apache/samza/operators/KV.java

The current KV class misses these primitive methods so that it can be used correctly in comparison, map or hash. Adding these methods to fix it.

SAMZA-2302: Add equals, hashcode and toString to KV

---

samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala
samza-core/src/test/java/org/apache/samza/coordinator/TestJobModelManager.java

Testing done (verification done through log messages on the AM):
1) Used samza-hello-samza to verify that the correct number of containers is used when using `GroupByContainerIds` as the task name grouper, which depends on the container mapping.
2) Verified that preferred host got set when host affinity is enabled.

SAMZA-2304: Existing container locality mapping is incorrect when building job model

---

samza-api/src/main/java/org/apache/samza/table/descriptors/RemoteTableDescriptor.java
samza-core/src/main/java/org/apache/samza/table/remote/AsyncRemoteTable.java
samza-core/src/main/java/org/apache/samza/table/remote/RemoteTable.java
samza-core/src/test/java/org/apache/samza/table/remote/TestAsyncRemoteTable.java
samza-core/src/test/java/org/apache/samza/table/remote/TestRemoteTable.java
samza-core/src/test/java/org/apache/samza/table/remote/descriptors/TestRemoteTableDescriptor.java

@dengpan-yin @dengpanyin @xinyuiscool 
Removed validation for read table requied

SAMZA-2309: Remove readFn requirement for remote tables

---

samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/test/java/org/apache/samza/runtime/TestLocalApplicationRunner.java

**Root Causes**
For standalone, to prevent a double bootstrap of the coordinator stream in the coordinator stream metadata store from the `StreamProcessor` and from the `ZkJobCoordinator`, the initialization of the metadata store was moved up to the `LocalApplicationRunner`. However, during the refactor, the creation of the underlying coordinator stream was left out.
The other root cause is that the assumption was made if a metadata store was not passed in to the `LocalApplicationRunner`, by default it will create a coordinator stream metadata store. However, if a PassthroughJobCoordinator is used or if the `job.coordinator.system` is not defined, the underlying coordinator stream cannot be created. These need to be accounted for.
**Fix**
Create the default coordinator stream metadata …

SAMZA-2298: Fix CoordinatorStreamStore creation for LocalApplicationRunner

---

samza-sql/src/main/java/org/apache/samza/sql/SamzaSqlInputTransformer.java
samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlRelMessage.java
samza-sql/src/main/java/org/apache/samza/sql/data/SamzaSqlRelMsgMetadata.java
samza-sql/src/main/java/org/apache/samza/sql/translator/FilterTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/LogicalAggregateTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ProjectTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/QueryTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ScanTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/TranslatorConstants.java
samza-sql/src/test/java/org/apache/samza/sql/data/TestSamzaSqlRelMessage.java
samza-sql/src/test/java/org/apache/samza/sql/serializers/TestSamzaSqlRelMessageSerde.java
samza-sql/src/test/java/org/apache/samza/sql/serializers/TestSamzaSqlRelRecordSerde.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestFilterTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestProjectTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestSamzaSqlLocalTableJoinFunction.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestSamzaSqlRemoteTableJoinFunction.java

1) Use nanoTime for SamzaSql specific latency metrics (i.e., logical operator processing time, and query latency)
2) remove some unused imports

[SAMZA-2283] Samza Sql Diagnostics: use Nanosecond for logical operator processing time and query latency

---

samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/scala/org/apache/samza/util/TestCoordinatorStreamUtil.scala

In the previous PR: https://github.com/apache/samza/pull/1010/files
config with null/empty values will be filter out when reading the coordinator stream,
this will cause some problems when the user expects an empty string to be a value config.

SAMZA-2318: Empty config values from coordinator stream shouldn't be removed

---

samza-api/src/main/java/org/apache/samza/sql/schema/SamzaSqlFieldType.java
samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
samza-sql/src/main/java/org/apache/samza/sql/avro/AvroTypeFactoryImpl.java
samza-sql/src/main/java/org/apache/samza/sql/planner/RelSchemaConverter.java
samza-sql/src/test/java/org/apache/samza/sql/avro/TestAvroRelConversion.java
samza-sql/src/test/java/org/apache/samza/sql/system/TestAvroSystemFactory.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

In Sql, REAL is 4-bytes while FLOAT and DOUBLE are both 8-bytes. While in Java and Avro, FLOAT is 4-bytes and DOUBLE is 8-bytes.
Fix the discrepancy in Samza Sql code by introducing REAL Samza Sql schema type and do the right mapping in AvroTypeFactoryImpl and RelSchemaConverter. Changes made earlier in AvroRelConverter are reverted.
Equivalent change in Calcite was made as part of this ticket: https://issues.apache.org/jira/browse/CALCITE-638

SAMZA-2321: Samza-sql - Introduce REAL Samza sql schema type

---

samza-core/src/main/java/org/apache/samza/runtime/ClusterBasedProcessorLifecycleListener.java
samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/test/java/org/apache/samza/runtime/TestClusterBasedProcessorLifecycleListener.java

The fix removes join() on the main thread from the shutdown
hook which causes a deadlock when a signal is received.
The shutdown hook now polls periodically to check
the container status on shutdown.

[SAMZA-2198] Fix deadlock in container signal handler

---

samza-api/src/main/java/org/apache/samza/table/descriptors/RemoteTableDescriptor.java
samza-core/src/main/java/org/apache/samza/util/EmbeddedTaggedRateLimiter.java

Existing java doc is confusing about what the actual behavior is for the default rate limiter. We should explicitly note that it is for the entire job and per task credit needs to divide that by number of tasks.

Samza-2331: Fix java doc of table descriptor for default rate limiter

---

samza-core/src/main/java/org/apache/samza/config/SystemConfig.java
samza-core/src/main/scala/org/apache/samza/config/StreamConfig.scala
samza-core/src/test/java/org/apache/samza/config/TestStreamConfig.java

It is going to take a bit more time to do the actual migration to Java, but this is an important first step that would be needed anyways. We can get this change in first, and then do the actual migration later.

SAMZA-2328: [Scala cleanup] Convert StreamConfig to Java (part 1: update test coverage and clarify functionality in javadocs)

---

samza-core/src/main/java/org/apache/samza/clustermanager/ContainerAllocator.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/StandbyContainerManager.java
samza-core/src/test/java/org/apache/samza/clustermanager/MockContainerAllocatorWithHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/MockContainerAllocatorWithoutHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithoutHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerProcessManager.java

Summary: This PR just renames AbstractContainerAllocator to ContainerAllocator
Note: This is a stacked PR on: https://github.com/apache/samza/pull/1152
*For the ease of reviewing, please review this PR from commit onwards:*
https://github.com/apache/samza/commit/439f0bc7305d4ad1cb50821df60f9c97ae84b20e

SAMZA-2319: [2/2] Simplify Container Allocation logic : Rename AbstractContainerAllocator to ContainerAllocator

---

build.gradle
gradle/dependency-versions.gradle
samza-api/src/main/java/org/apache/samza/storage/StorageEngine.java
samza-api/src/main/java/org/apache/samza/storage/kv/KeyValueStore.java
samza-core/src/main/java/org/apache/samza/operators/util/InternalInMemoryStore.java
samza-core/src/test/java/org/apache/samza/operators/impl/store/TestInMemoryStore.java
samza-core/src/test/java/org/apache/samza/storage/MockStorageEngine.java
samza-kv-inmemory/src/main/scala/org/apache/samza/storage/kv/inmemory/InMemoryKeyValueStore.scala
samza-kv-rocksdb/src/main/scala/org/apache/samza/storage/kv/RocksDbKeyValueStore.scala
samza-kv/src/main/java/org/apache/samza/storage/kv/LargeMessageSafeStore.java
samza-kv/src/main/scala/org/apache/samza/storage/kv/AccessLoggedStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/BaseKeyValueStorageEngineFactory.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/CachedStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngineMetrics.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/LoggedStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/NullSafeKeyValueStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStore.scala
samza-kv/src/test/scala/org/apache/samza/storage/kv/MockKeyValueStore.scala
samza-kv/src/test/scala/org/apache/samza/storage/kv/TestKeyValueStorageEngine.scala

This PR adds a new 'checkpoint' API to KeyValueStore that allows taking persistent (on-disk) snapshots of the local store state during commits for implementations that support it.
In RocksDB, this creates a new [Checkpoint](https://github.com/facebook/rocksdb/wiki/Checkpoints) directory. 
For supporting transactional state, during a commit, the newest changelog SSP offset is stored in the OFFSET file in this checkpoint directory, as well as in the checkpoint topic. During container start / store restore, the checkpoint directory corresponding to the changelog offset in the checkpoint topic is selected (if any) and used as the basis for restore.
Thanks to @xinyuiscool for contributing this.

Transactional State [1/5]: Added Store Checkpoint API

---

samza-api/src/main/java/org/apache/samza/storage/StorageEngine.java
samza-api/src/main/java/org/apache/samza/system/ChangelogSSPIterator.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/java/org/apache/samza/storage/MockStorageEngine.java
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala
samza-kv/src/test/scala/org/apache/samza/storage/kv/TestKeyValueStorageEngine.scala

This PR changes the KeyValueStorageEngine restore API and implementation to take a new ChangelogSSPIterator instead of a plain Iterator.
The new ChangelogSSPIterator is similar to the existing SystemStreamPartitionIterator with the following differences: 
1. This new iterator has 2 modes: `Restore` and `Trim`. 
2. It takes an `endingOffset` during construction. The mode changes from `Restore` to `Trim` during iteration if the current message offset is greater than the ending offset (and trim mode is enabled).
3. Does not check for end of stream since it isn't applicable to changelog topics.
For supporting transactional state, we only restore changelog messages up to the changelog SSP offset in the checkpoint topic. Any messages after this 'checkpointed changelog offset' are trimmed by …

Transactional State [2/5]: Added a ChangelogSSPIterator API

---

samza-core/src/main/java/org/apache/samza/storage/StorageManagerUtil.java
samza-core/src/main/java/org/apache/samza/storage/TaskSideInputStorageManager.java
samza-core/src/main/java/org/apache/samza/util/DiagnosticsUtil.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/TaskStorageManager.scala
samza-core/src/main/scala/org/apache/samza/util/FileUtil.scala
samza-core/src/test/scala/org/apache/samza/storage/TestTaskStorageManager.scala
samza-core/src/test/scala/org/apache/samza/util/TestFileUtil.scala
samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbOptionsHelper.java
samza-rest/src/main/java/org/apache/samza/monitor/LocalStoreMonitor.java
samza-test/src/main/java/org/apache/samza/test/framework/TestRunner.java
samza-test/src/main/scala/org/apache/samza/test/performance/TestKeyValuePerformance.scala

This PR changes StorageManagerUtil and FileUtil method to instance methods instead of static methods. Since many of these methods have side effects (modify disk contents), this helps mock their behavior in unit tests without performing actual I/O or using PowerMock.

Transactional State [3/5]: Made StorageManagerUtil and FileUtil non-static for mocking side effects in tests

---

samza-test/src/test/java/org/apache/samza/test/processor/TestStreamApplication.java
samza-test/src/test/java/org/apache/samza/test/processor/TestTaskApplication.java
samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java
samza-test/src/test/java/org/apache/samza/test/startpoint/StartpointTestHarness.java
samza-test/src/test/java/org/apache/samza/test/startpoint/TestStartpoint.java
samza-test/src/test/java/org/apache/samza/test/util/TestKafkaEvent.java

Added Startpoints to ZK Standalone integration tests.

SAMZA-2322: Integrate startpoints with ZK Standalone integration tests.

---

samza-sql/src/main/java/org/apache/samza/sql/avro/AvroTypeFactoryImpl.java
samza-sql/src/main/java/org/apache/samza/sql/interfaces/SqlIOConfig.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlValidator.java
samza-sql/src/main/java/org/apache/samza/sql/runner/SamzaSqlApplication.java
samza-sql/src/main/java/org/apache/samza/sql/translator/FilterTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/ProjectTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/avro/TestAvroRelConversion.java
samza-sql/src/test/java/org/apache/samza/sql/avro/schemas/ComplexRecord.avsc
samza-sql/src/test/java/org/apache/samza/sql/avro/schemas/ComplexRecord.java
samza-sql/src/test/java/org/apache/samza/sql/planner/TestSamzaSqlValidator.java
samza-sql/src/test/java/org/apache/samza/sql/system/TestAvroSystemFactory.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

Code changes involve the following:
1. AvroTypeFactoryImpl: Change API access modifiers from private to protected to be called from derived classes.
2. SamzaSqlValidator:
2.1 Change order of validation of select query fields and output fields so that the error messages make more sense.
2.2 Take care of the case where a field projected in select query is mentioned more than once and added tests for it. Eg: SELECT myUdf(id) as id, * from store.myTable. This type of pattern is typically followed when users want to just modify one field in the input table while keeping rest of the fields the same.
2.3 Add a short term isOptional API to take care of cases where RelSchemaProviders have a complex mechanism to determine if a given output field is optional. Once the RelSchemaProviders are fixed to …

SAMZA-2320: Samza-sql: Refactor validation to cover more cases and make it more extensible.

---

samza-api/src/main/java/org/apache/samza/system/StreamSpec.java
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemAdmin.java
samza-kafka/src/test/scala/org/apache/samza/system/kafka/TestKafkaSystemAdmin.scala

As part of this PR: https://github.com/apache/samza/pull/789/files#diff-52d8a92e9c8e3d26c4e595919566326aR519 the replicationFactor value defined in the config was dropped since with the kafka client update it cannot be passed to the configs. 
To preserve this config it should be passed to the checkpoint topic spec; this PR adds the change to preserve the value set by the config `task.checkpoint.replication.factor` in the checkpoint kafka topic spec.

SAMZA-2339 : Update KafkaSystemAdmin to adhere to the checkpoint replication factor

---

samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithoutHostAffinity.java

Some of these tests were failing due to expiry timeouts on some machines and being flaky. To fix this we have just increased the thread sleep time to ensure expiry of requests on allocator thread gets triggered.

SAMZA-2346: Fixing Test timeouts for Allocator testing

---

samza-api/src/main/java/org/apache/samza/util/BlockingEnvelopeMap.java
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemConsumer.java
samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaConsumerProxy.java
samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaConsumerProxyFactory.java

Notifying BEM about kafkaConsumerProxy failure via kafkaConsumer to prevent BEM poll blocking in case of proxy failures

SAMZA-2348 : Notifying BEM about kafkaConsumerProxy failure to prevent BEM poll-blockin in case of proxy failures

---

samza-kv-rocksdb/src/main/scala/org/apache/samza/storage/kv/RocksDbKeyValueStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStoreMetrics.scala

Reverts apache/samza#1158 since there was an uncaught issue with the CAS invocation infinite looping.

Revert "SAMZA-2324: Adding KV store metrics for rocksdb"

---

samza-core/src/main/java/org/apache/samza/config/StorageConfig.java
samza-core/src/test/java/org/apache/samza/config/TestStorageConfig.java
samza-kafka/src/main/scala/org/apache/samza/config/KafkaConfig.scala
samza-kafka/src/test/scala/org/apache/samza/config/TestKafkaConfig.scala

To enable transactional state, we will need to avoid the head of the changelog (the ones after last checkpoint) not being log-compacted so we can trim the rest of the updates. We use min.compaction.log.ms to control the compaction time.

SAMZA-2352: Use min.compaction.lag.ms to avoid compacting the Kafka changelog topic

---

samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/main/java/org/apache/samza/runtime/LocalContainerRunner.java

This is required because BeamContainerRunner also invokes ContainerLaunchUtil and this file-writing is useful for it.

SAMZA-2359 : Moving writeMetadataFile() invocation to ContainerLaunchUtil from LocalContainerRunner

---

samza-api/src/main/java/org/apache/samza/checkpoint/CheckpointId.java
samza-api/src/main/java/org/apache/samza/checkpoint/CheckpointedChangelogOffset.java
samza-api/src/main/java/org/apache/samza/storage/StorageEngine.java
samza-api/src/main/java/org/apache/samza/storage/kv/KeyValueStore.java
samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-core/src/main/java/org/apache/samza/operators/util/InternalInMemoryStore.java
samza-core/src/main/java/org/apache/samza/storage/TransactionalStateTaskRestoreManager.java
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/main/scala/org/apache/samza/storage/NonTransactionalStateTaskStorageManager.scala
samza-core/src/main/scala/org/apache/samza/storage/TaskStorageManager.scala
samza-core/src/main/scala/org/apache/samza/storage/TransactionalStateTaskStorageManager.scala
samza-core/src/test/java/org/apache/samza/operators/impl/store/TestInMemoryStore.java
samza-core/src/test/java/org/apache/samza/storage/MockStorageEngine.java
samza-core/src/test/java/org/apache/samza/storage/TestTransactionalStateTaskRestoreManager.java
samza-core/src/test/scala/org/apache/samza/container/TestTaskInstance.scala
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java
samza-core/src/test/scala/org/apache/samza/storage/TestTransactionalStateTaskStorageManager.java
samza-kv-inmemory/src/main/scala/org/apache/samza/storage/kv/inmemory/InMemoryKeyValueStore.scala
samza-kv-rocksdb/src/main/scala/org/apache/samza/storage/kv/RocksDbKeyValueStore.scala
samza-kv/src/main/java/org/apache/samza/storage/kv/LargeMessageSafeStore.java
samza-kv/src/main/scala/org/apache/samza/storage/kv/AccessLoggedStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/CachedStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/LoggedStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/NullSafeKeyValueStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStore.scala
samza-kv/src/test/scala/org/apache/samza/storage/kv/MockKeyValueStore.scala
samza-test/src/test/java/org/apache/samza/storage/kv/TransactionalStateIntegrationTest.java
samza-test/src/test/java/org/apache/samza/storage/kv/TransactionalStateMultiStoreIntegrationTest.java

In the current implementation for transactional state, if the checkpointed changelog offset gets compacted, (e.g. if the processor was down for more than min compaction lag), and the checkpointed changelog offset is b/w the oldest and newest post compaction, we will end up deleting part of the current state (potentially everything after checkpointed offset). We should not do this.
Instead, we should write the checkpoint timestamp along with the the checkpointed changelog offset, and not do a trim during restore if time since last checkpoint is older than (or close to) min.compaction.lag. We should instead restore to latest and log a warning that transactional state guarantee doesn't hold (i.e., same as the current behavior). The fix for users would then be to increase the …

SAMZA-2356: [Transactional State] Do not trim changelog if time since last checkpoint is greater than min.compaction.lag.

---

samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/test/java/org/apache/samza/runtime/TestLocalApplicationRunner.java

Null pointer exception is thrown when calling LocalApplicationRunner.kill() without setting a coordinator stream. My guess that the bug is a result of https://issues.apache.org/jira/browse/SAMZA-2294 forgetting to add the null check everywhere it's required. I added a test that exposes the exception.

SAMZA-2372:Null pointer exception in LocalApplicationRunner

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java

User specified side input processor should take precedence over the identity processor
Symptom: Standby containers on jobs using side-inputs will run into deserialization exceptions when side-inputs use a custom serde (while changelog uses byte serde).
Cause: If the changelog doesnt use byte serde, the custom serde and processor should be respected.
Fix: Added logic that enables user specified side input processor to take precedence over the identity processor.
Tests: Samza test job that uses standby containers with side-inputs, with side-inputs using a custom serde.

SAMZA-2382: User specified side input processor should take precedence over the identity processor

---

samza-core/src/main/java/org/apache/samza/util/DiagnosticsUtil.java
samza-core/src/main/scala/org/apache/samza/job/JobRunner.scala
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/scala/org/apache/samza/util/TestCoordinatorStreamUtil.scala

Issues:
JobRunner#run is composed of three parts, persisting config in coordinator stream, creation of diagnostics stream when applicable and submit the job. It is not easy to read when all of them are combined in a single method and it cannot be reused when a subset of the functionality is needed elsewhere. For example, when we move planning to AM, we will only need to submit job on runner but the rest on AM.
Changes:
1. Move coordinator stream related logic to CoordinatorStreamUtil#writeConfigToCoordinatorStream
2. Move diagnostics stream related logic to DiagnosticsUtil#createDiagnosticsStream
3. Move job submission related logic to JobRunner#submit()
Tests:
1. Add unit tests to test CoordinatorStreamUtil#writeConfigToCoordinatorStream

SAMZA-2381: Refactor JobRunner#run and split into multiple util methods.

---

samza-core/src/main/java/org/apache/samza/config/StorageConfig.java
samza-core/src/test/java/org/apache/samza/config/TestStorageConfig.java

**Symptom**: Enabling side inputs for low level jobs using configuration will throw an exception during job start up.
**Cause**: `getStoreNames()` uses pattern matching to infer store names from the config. The pattern matching conflicts with `side.inputs.processor.factory` and returns incorrect store names.
**Fix**: Handle side inputs processors factory prefix correctly within `getStoreNames()`
**Tests**: Added unit test for `getStoreNames()`
**API Change**: None

SAMZA-2386: Get store names should return correct store names in the presence of side inputs

---

samza-kv-rocksdb/src/main/scala/org/apache/samza/storage/kv/RocksDbKeyValueStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStore.scala
samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStoreMetrics.scala

**Design:** Adding a metric to track the maximum serialized value size written to rocksdb. This provides value to customers using logged stores backed by kafka. As kafka has configurable message size limits, the addition of this metric will allow users to understand how their records are approaching that limit.
**Changes:** Adds a new metric "max-record-size-bytes" to SerializedKeyValueStoreMetrics, which is tracked in SerializedKeyValueStore.
**Tests:** Built a version of samza locally which included this commit, then ran a test job that wrote consistently sized records to rocksdb and verified that the metric emitted matched that size.
**API Changes:** none
**Upgrade Instructions:** No manual steps other than upgrading to the samza version containing this commit. Once upgraded the new …

SAMZA-2324: Adding KV store metrics for rocksdb

---

docs/startup/hello-samza/versioned/index.md

**Symptom:** kafka-console-consumer.sh throws "zookeeper" is not a recognized option and that bootstrap-server is a required option
**Fix:** remove zookeeper and add bootstrap-server option
**Tests:** build and deploy hello-samza locally and use deploy/kafka/bin/kafka-console-consumer.sh  --bootstrap-server localhost:9092 --topic wikipedia-raw and it shows events in the kafka topic.

DOCS: Update kafka consumer command for hello-samza to use bootstrap-server

---

samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
samza-sql/src/main/java/org/apache/samza/sql/interfaces/SqlIOConfig.java
samza-sql/src/main/java/org/apache/samza/sql/util/SamzaSqlQueryParser.java

Currently, relRecord is populated with cached schema only at the top-level fields while the nested fields are populated with the schema of the incoming record. This ticket is to fix that inconsistency and always consider cached schema (schema that is fetched when the job starts).
As a by-product of considering only cached schema, Sql job will keep running even though the input schema has evolved, let's say a new field is added. We will keep dropping the new field. As a separate effort, we need to consider adding metrics to flag whenever we detect that the input schema has evolved.
**Symptom**: Container sometimes fails with exception when the schema of input stream(s) evolves.
**Cause**: Currently, relRecord is populated with cached schema only at the top-level fields while the nested …

SAMZA-2415: Fix AvroRelConverter to only consider cached schema while populating SamzaSqlRelRecord for all the nested records.

---

samza-api/src/main/java/org/apache/samza/storage/StorageEngine.java
samza-core/src/main/java/org/apache/samza/processor/StreamProcessor.java
samza-core/src/main/java/org/apache/samza/storage/NonTransactionalStateTaskRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/StorageRecovery.java
samza-core/src/main/java/org/apache/samza/storage/TaskRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/TransactionalStateTaskRestoreManager.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/main/scala/org/apache/samza/system/SystemProducers.scala
samza-core/src/test/java/org/apache/samza/processor/TestStreamProcessor.java
samza-core/src/test/scala/org/apache/samza/container/TestSamzaContainer.scala
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala
samza-kv/src/test/scala/org/apache/samza/storage/kv/TestKeyValueStorageEngine.scala

**Symptom**: Duplicate processing, Inconsistent checkpoints for inputs, Inconsistent changelog state
**Cause**: We have a bug in the state machine inside stream processor that can result in processors running containers with old job model version after rebalances in Standalone deployment model. 
**Fix**: We interrupt the container and wait for container to shutdown gracefully within a timeout (task.shutdown.ms) and fail the stream processor if the container doesn’t shut down within the timeout
**Tests**: Added unit tests for StreamProcessor and SamzaContainer. Working on integration tests.
**API Changes** `restore`  methods on `TaskRestoreManager` and `StorageEngine` now throws `InterruptedException`. Please refer to java docs to get additional implementation notes. 
**Upgrade …

SAMZA-2305: Stream processor should ensure previous container is stopped during a rebalance

---

samza-kv/src/main/scala/org/apache/samza/storage/kv/SerializedKeyValueStore.scala

Adding null-check before incrementing metrics for bytesSerialized
Symptom: User serde-serialization logic can choose to serialize non-null objects to a null, which implies delete the value. In this case, current code tries to increment the metrics using the size of the null and fails with an NPE.
Cause: Current code tries to increment the bytesSerialized metrics using the size of the null and fails with an NPE.
Fix: Added logic to skip metric value update if serde returns null.

SAMZA-2416 : Adding null-check before incrementing metrics for bytesSerialized

---

samza-core/src/main/java/org/apache/samza/container/ContainerHeartbeatMonitor.java
samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java

**Symptom:** 
When a container heartbeat fails, the container shutdown
sequence is triggered and the Container is never restarted.
**Cause:**
When a container heartbeat fails, the container shutdown
sequence exists the Container with an exit code of `0` which
marks the container as `Completed` - preventing the JobCoordinator
from restarting the container.
The bug is caused by `containerException` overwritten with the value
returned by `listener.getContainerException` without checking if 
`containerException` was already set by the heartbeat monitor
**Changes:** 
The container can shutdown exceptionally in the following two ways:
1) Exception in the container
2) Heartbeat Expired
In both paths the ContainerLaunchUtil previously expected a
shared static variable to hold the exception. The …

SAMZA-2423: Heartbeat failure causes incorrect container shutdown

---

samza-sql/src/main/java/org/apache/samza/sql/translator/JoinTranslator.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

**Symptom**: Using sub-query with a join fails today with an unsupported exception. 
**Cause**: We have never supported sub-query in joins due to the way we have been parsing sql statements which was fixed recently.
 **Fix**: A simple code enhancement to handle logical filter while traversing the calcite logical plan to get the table IO. 
**Tests**: Added a Sql End-To-End test for sub-query and join.

SAMZA-2425: Add support for sub-query in joins

---

samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java

Issues: LocalApplicationRunner has multiple constructors and follows different initialization logic.
Changes:
1. Refactor all constructors to end up with the same private constructor.
2. Align "static final" and "final static" to "static final"
3. Group class variales based on accessibility
4. Minor fixs on inconsistent styling, return etc.
API Changes:
None
Upgrade Instructions: 
None
None
Tests:
Unit Tests

Refactor LocalApplicationRunner

---

samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemAdmin.java
samza-kafka/src/test/java/org/apache/samza/system/kafka/TestKafkaSystemAdminJava.java

Symptom: Currently the coordinator kafka topic of a samza job is created with cleanup.policy set to 'delete' instead of 'compact' for certain cases. This potentially leads to losing all the metadata(JobModel/Config) stored in coordinator stream for some samza jobs. 
Cause: The control-flow in KafkaSystemAdmin.createStream to build the coordinator stream spec swallows the essential kafka-topic configurations and passes along the empty configuration bag to the kafka-broker when creating the coordinator stream. This issue was introduced in [SAMZA-1868](https://issues.apache.org/jira/browse/SAMZA-1868). 
Changes: Fix the topic-creation control-flow for the coordinator topics and generate the correct topic-configurations.
Tests: Added unit tests to validate that the expected topic …

SAMZA-2434: Fix the coordinator steam creation workflow

---

samza-api/src/main/java/org/apache/samza/system/StreamSpec.java
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemAdmin.java
samza-kafka/src/main/scala/org/apache/samza/config/KafkaConfig.scala
samza-kafka/src/test/java/org/apache/samza/system/kafka/TestKafkaSystemAdminJava.java
samza-kafka/src/test/scala/org/apache/samza/config/TestKafkaConfig.scala

Symptom: Checkpoint and changelog kafka topics of a samza job may be created with cleanup.policy set to 'delete' instead of 'compact' for certain cases.
Cause: 
- *Checkpoint:* The control-flow in KafkaStreamSpec to build checkpoint spec swallows the essential kafka-topic configuration rather it passes empty configuration bag to kafka-broker. This behavior was introduced in SAMZA-2339. 
- *Changelog:* The change-log topic configurations were incorrectly generated when the RocksDB store TTL is set to -1 by the user. This behavior was introduced in SAMZA-1929.
Changes: Fix the topic-creation control-flow for the metadata topics and generate the correct topic-configurations.
Tests: Added unit tests to validate that the expected topic configuration bag was generated for both checkpoint and …

SAMZA-2431: Fix the checkpoint and changelog topic auto-creation.

---

samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

\> Task :samza-test_2.11:test
testEndToEndDisableSystemMessages FAILED
java.lang.AssertionError: expected:<10> but was:<0>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at org.apache.samza.test.samzasql.TestSamzaSqlEndToEnd.testEndToEndDisableSystemMessages(TestSamzaSqlEndToEnd.java:129)
testEndToEndStreamTableJoinWithSubQuery FAILED
java.lang.AssertionError: expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at org.apache.samza.test.samzasql.TestSamzaSqlEndToEnd.testEndToEndStreamTa …

Disable flaky tests in TestSamzaSqlEndToEnd that cause builds to fail

---

build.gradle
gradle/dependency-versions.gradle
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobBasicMetrics.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobConfig.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobSystemAdmin.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobSystemFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriter.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriterFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobOutputStream.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/compression/Compression.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/compression/CompressionFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/compression/CompressionType.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/compression/GzipCompression.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/compression/NoneCompression.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobSystemProducer.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobSystemProducerMetrics.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobWriter.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobWriterFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobWriterMetrics.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobAvroWriter.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobOutputStream.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/compression/TestGzipCompression.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/producer/TestAzureBlobSystemProducer.java

**Feature:** [SEP-26: Azure Blob System Producer](https://cwiki.apache.org/confluence/display/SAMZA/SEP-26%3A+Azure+Blob+Storage+Producer)
**Changes:** New "azureblob" package added that contains the new AzureBlobSystemProducer and its components. This new AzureBlobSystemProducer implements the existing SystemProducer interface. There are no changes made to existing API and existing implementations in any manner.
**Tests:** Unit tests added for all components. A sample job in hello-samza was successfully configured to use this producer and create blobs on Azure Blob Storage.
**Upgrade instructions:** Backwards compatible change as its a completely new component and hence no upgrade needed.
**Usage instructions:** Configure a Samza job to use this producer by setting the following configs …

SAMZA-2421: Add SystemProducer for Azure Blob Storage

---

samza-kafka/src/main/scala/org/apache/samza/config/KafkaConfig.scala
samza-kafka/src/test/scala/org/apache/samza/config/TestKafkaConfig.scala

Symptom: Launching a stateful samza job with high RocksDB TTL(around 28 days) results in the following exception:
```java
Exception in thread "main" org.apache.samza.SamzaException: Failed to run application
at org.apache.samza.runtime.RemoteApplicationRunner.run(RemoteApplicationRunner.java:79)
at org.apache.samza.runtime.ApplicationRunnerUtil.invoke(ApplicationRunnerUtil.java:54)
at org.apache.samza.runtime.ApplicationRunnerMain.main(ApplicationRunnerMain.java:53)
Caused by: java.lang.NumberFormatException: For input string: "2419200000"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:583)
at java.lang.Integer.parseInt(Integer.java:615)
at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272) …
```

SAMZA-2438: Fix the change log topic properties generation.

---

samza-yarn/src/main/scala/org/apache/samza/job/yarn/YarnJob.scala
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnJob.java

Design:
Changes:
1. Depending the on the existence of job.config.loader.factory, YarnJob will alternatively wraps job submission configs to Yarn.
2. In a separate PR, ClusterBasedJobCoordinator will be updated to read full job config from loader or coordinator stream based on the existence of submission config environment variable.
API Changes:
N/A. This is part of a series PRs, detailed information will be provided in the last/main PR.
N/A. This is part of a series PRs, detailed information will be provided in the last/main PR.
N/A. This is part of a series PRs, detailed information will be provided in the last/main PR.
Tests:
Unit Tests

SAMZA-2409: Update YarnJob to construct job submission env varible

---

gradle/dependency-versions-scala-2.11.gradle
gradle/dependency-versions-scala-2.12.gradle
gradle/dependency-versions.gradle

Symptom: AM Process runs out of file descriptors and gets stuck during deployment of jobs with a large number of containers. Containers are unable to start since they can’t fetch the JobModel and configs from the AM endpoint.
Cause: This seems to be a Jetty bug that’s fixed in the latest versions. For more details, see: https://docs.google.com/document/d/1RFf_3_lJHHdoZHQlikSDHcm55GYbp7ObA8qVUwr-6p0/edit#
Changes: Bump Jetty version to 9.4.20.v20190813
Tests: Reproduced locally using the test harness in https://github.com/prateekm/samza/commit/6d7e01b5b9d0d38a7766357a870ba7daeadd828e. All unit and integration tests pass with the version bump. Verified that Samza jobs are able to deploy correctly on a YARN cluster with the version bump.
API Changes: Jetty version upgraded from …

SAMZA-2443: Upgrade Jetty version to prevent AM file descriptor leak

---

samza-core/src/main/scala/org/apache/samza/checkpoint/OffsetManager.scala
samza-core/src/test/scala/org/apache/samza/checkpoint/TestOffsetManager.scala

**Symptom:** Since introducing changelog SSP checkpointing in 1.3, onCheckpoint will be invoked for changelog SSPs if job.changelog.system is configured to be the same as an input system which implements CheckpointListener. This can be problematic because the types of checkpoints being written for changelog SSPs and input SSPs are different.
**Cause:** OffsetManager.writeCheckpoint is called with a Checkpoint parameter that includes changelog SSP checkpoints.
**Changes:** OffsetManager will now only invoke onCheckpoint for SSPs that are registered with it.
**Tests:** Wrote a test which attempts to write a Checkpoint with OffsetManager.writeCheckpoint which includes an SSP which was not registered with the OffsetManager. The test verifies that the callback is invoked only for those SSPs …

SAMZA-2446: Invoke onCheckpoint only for registered SSPs

---

samza-core/src/main/scala/org/apache/samza/storage/TransactionalStateTaskStorageManager.scala
samza-core/src/test/scala/org/apache/samza/storage/TestTransactionalStateTaskStorageManager.java

**Symptom:** NPE when attempting to remove old checkpoint directories.
**Cause:** Removal of old checkpoints assumes every file in the logged store base directory is also a directory, which may not be true if the user has configured it to a path that is not exclusive to store contents.
**Changes:** Check that the result of `listFiles` is non-null before attempting to delete.
**Tests:** Wrote a test to mimic the behavior of a non-directory file in the logged store base directory. Test fails without the patch, passes with it.
**Upgrade Instructions:** None

SAMZA-2447: Checkpoint dir removal should only search in valid store dirs

---

samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/test/java/org/apache/samza/runtime/TestLocalApplicationRunner.java

Design:
Changes:
1. Update unit test only public constructor of LocalApplicationRunner to take SamzaApplication and Config as well to be consistent with other constructors.
2. Update private constructor of LocalApplicationRunner to take SamzaApplication and Config.
3. Update private constructor of LocalApplicationRunner to load full job config when config loader is present.
API Changes:
LocalApplicationRunner's constructor now allows initial config/job submission config only instead of full job config, this is backward compatible as full job config is still supported.
This is part of a series PRs, detailed information will be provided in the last/main PR.
This is part …

SAMZA-2429: Update LocalApplicatoinRunner to load full job config from config loader when present.

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobConfig.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobSystemAdmin.java

**Symptom**: 
1. Samza High level job using this SystemProducer gets UnsupportedOperationException from AzureBlobSystemAdmin.
2. Azure account details of the samza job are logged. 
**Cause**:
1. getSystemStreamMetadata throws unsupported exception. 
2. Account details configs are not marked sensitive.
**Changes**
1. getSystemStreamMetadata returns an empty map.
2. "sensitive" prefixed to the account details configs.
**Tests**: Sample High level job in hello-samza (https://github.com/apache/samza-hello-samza/pull/71) works correctly with these changes.

SAMZA-2275: Azure Blob System Producer: fixes for high level jobs

---

samza-core/src/main/java/org/apache/samza/runtime/ApplicationRunnerMain.java
samza-core/src/main/scala/org/apache/samza/job/JobRunner.scala
samza-core/src/test/java/org/apache/samza/runtime/TestApplicationRunnerMain.java

Design:
Changes:
1. Override ApplicationRunnerCommandLine#loadConfig not to invoke config loader as ApplicationRunners handles initial config and full job config themselves.
2. Add JobRunnerCommandLine to load full job config for JobRunner to keep consistent with previous behavior as it still needs full job config for special use cases.
API Changes:
None
None
None
Tests:
1. Unit Tests

SAMZA-2441: Update ApplicationRunnerMain#ApplicationRunnerCommandLine not to load local file

---

samza-core/src/main/java/org/apache/samza/clustermanager/container/placement/ContainerPlacementMetadataStore.java
samza-core/src/main/java/org/apache/samza/container/LocalityManager.java
samza-core/src/main/java/org/apache/samza/container/grouper/task/TaskAssignmentManager.java
samza-core/src/main/java/org/apache/samza/container/grouper/task/TaskPartitionAssignmentManager.java
samza-core/src/main/java/org/apache/samza/coordinator/RunIdGenerator.java
samza-core/src/main/java/org/apache/samza/coordinator/metadatastore/CoordinatorStreamStore.java
samza-core/src/main/java/org/apache/samza/execution/LocalJobPlanner.java
samza-core/src/main/java/org/apache/samza/job/model/JobModelUtil.java
samza-core/src/main/java/org/apache/samza/startpoint/StartpointManager.java
samza-core/src/main/java/org/apache/samza/storage/ChangelogStreamManager.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala
samza-core/src/test/java/org/apache/samza/container/grouper/task/TestTaskAssignmentManager.java
samza-core/src/test/java/org/apache/samza/container/grouper/task/TestTaskPartitionAssignmentManager.java
samza-core/src/test/java/org/apache/samza/coordinator/TestJobModelManager.java
samza-core/src/test/java/org/apache/samza/coordinator/TestRunIdGenerator.java
samza-core/src/test/java/org/apache/samza/coordinator/metadatastore/TestCoordinatorStreamStore.java
samza-core/src/test/java/org/apache/samza/runtime/TestLocalApplicationRunner.java

When Samza's job creates lots of tasks/partitions, it can take over a long time for AM to save the metadata in a run which may cause timeout exception.
We observed if the Samza's job has over 37k tasks/partitions, it takes over 10 min for AM to save it in a run.
JobModelManager uses CoordinatorStreamStore.put() to save job metadata information which does flush for each message, and the flush operation is heavy especially when the remote server suffering the performance issues. 
None
None

SAMZA-2444: JobModel save in CoordinatorStreamStore resulting flush for each message

---

samza-core/src/main/java/org/apache/samza/config/ClusterManagerConfig.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/util/DiagnosticsUtil.java
samza-core/src/main/scala/org/apache/samza/config/ShellCommandConfig.scala
samza-core/src/main/scala/org/apache/samza/diagnostics/DiagnosticsManager.java
samza-core/src/main/scala/org/apache/samza/diagnostics/DiagnosticsStreamMessage.java
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/java/org/apache/samza/config/TestJobConfig.java
samza-core/src/test/java/org/apache/samza/diagnostics/TestDiagnosticsManager.java

Adding internal autosizing related configs, can be used by an external controller. 
These sizing-related configs (e.g., container-count, etc) take precedence when job.autosizing.enabled is set, otherwise existing behavior is retained.
Symptom: Sizing configs set by a controller need to be different from user-facing configs.
Cause: --
Fix: Added internal configs for sizing related configs. Added tests. 
The enabled config is also needs to be emitted by the DiagnosticsManager.
API Changes: Adding internal autosizing related configs (job.autosizing.enabled, job.autosizing.container.count, job.autosizing.container.thread.pool.size, job.autosizing.maxheap.mb, job.autosizing.cpu.cores) , can be used by an external controller. These sizing-related configs (e.g., container-count, etc) take …

SAMZA-2452 : Adding internal autosizing related configs

---

samza-core/src/main/java/org/apache/samza/runtime/ApplicationRunnerMain.java
samza-core/src/main/scala/org/apache/samza/job/JobRunner.scala
samza-core/src/test/java/org/apache/samza/runtime/TestApplicationRunnerMain.java

This reverts commit 5a58877897fae4a0e819c70ee48ee2d7edcb01a2.
Reverting this change for the 1.4.0 branch since it is backwards
incompatible and we don't want to release this for 1.4.

Revert "SAMZA-2441: Update ApplicationRunnerMain#ApplicationRunnerCommandLine not to load local file (#1265)"

---

samza-core/src/main/scala/org/apache/samza/job/local/ProcessJobFactory.scala
samza-core/src/main/scala/org/apache/samza/job/local/ThreadJobFactory.scala

Design:
Changes:
1. Update ProcessJobFactory to load full job config, execute planning and write full job config back to coordiantor stream, which was done by RemoteApplicationRunner
2. Update ThreadJobFactory to load full job config, execute planning and write full job config back to coordiantor stream, which was done by RemoteApplicationRunner
These are needed as RemoteApplicationRunner no longer get full job config, no longer execute planning and no longer persist full job config in coordinator stream anymore.
API Changes:
None.
See https://github.com/apache/samza/pull/1256 for more detailed instructions.
See https://github.com/apache/samza/pull/1256 for more …

SAMZA-2458: Update ProcessJobFactory and ThreadJobFactory to load full job config

---

docs/learn/documentation/versioned/container/metrics-table.html
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala

Adding metric for container thread pool size.
Symptom: Currently it is not possible to track the container-thread-pool size using metrics, even though its possible to configure it similar to container-memory-mb, vcore, etc.
Cause: No metric for this configurable
Fix: Added metric for container thread pool size, updated metrics reference sheet.
API changes: Added new metric for container-thread-pool-size.
Usage Instructions: See the metrics reference sheet for details on the metric.

SAMZA-2462 : Adding metric for container thread pool size

---

gradle/dependency-versions.gradle

Symptom:  Currently Samza is using RocksDB 5.7.3 version. This would cause a segment fault if the dependency order is not properly provisioned. This was reported in https://github.com/tensorflow/tensorflow/issues/22307
Cause: For example, if RockDB library is loaded before Tensorflow library, segment fault is triggered. In contrast, if Tensorflow library is loaded first, then there is no run-time error. Please see the following experiments for more details.
public class RocksDBTest{
public static void main(String[] args) throws InterruptedException
{ //System.load("/home/yangzhan/libs/librocksdbjni7259590262328036607.so"); // RocksDB v=5.0.1 => Failed // System.load("/home/yangzhan/libs/librocksdbjni575105474288895339.so"); // RocksDB v=5.7.3 => Failed …

SAMZA-2456: Upgrade Rocksdb to 6.5.3

---

samza-core/src/main/java/org/apache/samza/scheduler/EpochTimeScheduler.java

**Symptom**: Duplicate firing of processing timers
**Cause**: In EpochTimeScheduler, the `removeReadyTimers`  returns the timers that are ready to be fired and also remove them from local book-keeping. We operate on the SetView returned by entrySet() to remove the timers. Since the iterator of the SetView is weakly consistent, there is possibilities in timers surviving the remove and results in duplicate timers being fired.
**Changes**: Remove the keys from the local book keeping map directly instead of using the `keySet()` and `removeAll()`
**Tests**: Tested using the Nexmark beam benchmark test suite. Will explore a way to unit test this change and follow it up on a separate PR.

SAMZA-2463: Duplicate firings of processing timers

---

samza-core/src/main/java/org/apache/samza/storage/TransactionalStateTaskRestoreManager.java
samza-core/src/test/java/org/apache/samza/storage/TestTransactionalStateTaskRestoreManager.java

**Issues:** Code block for cleaning logged stores according to config value is duplicated and references incorrect & incomplete pathnames.
**Changes:** Removing duplicate code block, and correcting the directories marked for deletion. When the clean.on.container.start config is true for a store and transactional state is enabled, the current _and_ checkpoint directories should be deleted. Previously only the current directory was marked for deletion, but at the wrong path.
**Tests:** Added unit test to confirm deletion of appropriate store directories
**Upgrade instructions:** None
**Usage instructions:** None

SAMZA-2419: removing duplicate cleaning of stores

---

samza-core/src/main/java/org/apache/samza/system/inmemory/InMemoryManager.java

Symptom: There is a chance to run into ConcurrentModificationException using InMemorySystem.
Cause: The returned list of InMemoryManager#poll is a sublist of the original list. While iterating the sublist, if the original list is modified, ConcurrentModificationException will be thrown.
Changes: We need to make the returned list of InMemoryManager#poll to be a new copy.
Tests: Tested with a samza beam job. Didn't see the exception any more.

SAMZA-2461: Fix Concurrent Modification Exception in InMemorySystem

---

build.gradle

**Symptom:**
Samza job using the new AzureBlobSystemProducer requires to explicitly pin  jackson-core dependency to be 2.10.0. Other wise, NoClassDefFoundError is thrown for com.fasterxml.jackson.core.TSFBuilder needed by com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient which is used by the SystemProducer to setUpAzureContainer.
**Cause:**
samza-azure's build gradle has jackson-core:2.8.8. Without this explicit pinning, sample samza job's maven resolves jackson-core to 2.6.0 that is pulled in by com.microsoft.azure:azure-storage:5.3.1. However, azure-storage-blob:12.0.1 used by the SystemProducer needs jackson-core:2.10.0. 
**Changes:**
Upgrade jackson-core to 2.10.0
**Tests:** Sample High level job in hello-samza (apache/samza-hello-samza#71) works correctly with these …

SAMZA-2459: Upgrade Jackson-core dependency for samza-azure

---

samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/test/scala/org/apache/samza/container/TestSamzaContainer.scala

**Issues:** Currently, standby containers don't spin up run loop and do an infinite wait after starting the container storage manager. In the event of a shutdown request from LocalApplicationRunner, these containers don't respond since the shutdown request is coordinator through runloop and it leaves us with the only option of forcefully killing it.
**Changes:** Add a countdown latch to signal the main thread to make standby containers to respond to shutdown instead of infinite sleeping
**Improvement:** StandbyContainer invoke a clean shutdown within a few seconds rather than waiting to be killed for 30 secs
**Tests:** Manually tested the shutdown sequence
**Upgrade instructions:** None
**Usage instructions:** None

SAMZA-2468: Make Standby containers respond to shutdown request

---

bin/setup-int-test.sh
samza-core/src/main/java/org/apache/samza/coordinator/stream/CoordinatorStreamWriter.java
samza-core/src/main/java/org/apache/samza/runtime/ApplicationRunnerMain.java
samza-core/src/main/scala/org/apache/samza/util/CommandLine.scala
samza-core/src/test/java/org/apache/samza/runtime/TestApplicationRunnerMain.java
samza-core/src/test/scala/org/apache/samza/job/TestJobRunner.scala

Design:
Changes:
1. Simplify CommandLine by removing unnecessary arguments.
API Changes:
1. config-loader-factory removed in CommandLine
2. config-loader-properties removed in CommandLine
Upgrade Instruction:
1. Usage of --config-factory and --config-loader-factory will be switched to --config job.config.loader.factory
2. Usage of --config-path and --config-loader-properties will be switched to --config job.config.loader.properties
Usage Instruction
--config-factory=org.apache.samza.config.factories.PropertiesConfigFactory --config-path=file:///location/file.txt
and
--config-loader-factory=org.apache.samza.config.loaders.PropertiesConfigLoaderFactory --config-loader-properties path=file:///location/file.txt …

SAMZA-2471: Simplify CommandLine

---

samza-core/src/main/java/org/apache/samza/classloader/DependencyIsolationUtils.java
samza-core/src/main/java/org/apache/samza/classloader/IsolatingClassLoaderFactory.java
samza-shell/src/main/bash/run-class.sh

**Symptom**: When running in YARN and job coordinator dependency isolation is enabled, the framework infrastructure is unable to access the correct YARN configurations. This means that when it tries to interact with YARN, it is not using the correct configurations, and that results in issues. The observed issue was that the YARN client from the Samza side did not follow the RM HA config correctly, and so there was an issue in connecting to the RM.
**Cause**: The YARN client reads configurations from certain resource files on the classpath. In `run-class.sh`, the `HADOOP_CONF_DIR` is directly used and added to the classpath. In job coordinator dependency isolation mode, the classpath in `run-class.sh` is not used for the framework infrastructure, since `IsolatingClassLoaderFactory` builds …

SAMZA-2472: Use runtime-framework-resources-pathing.jar to specify part of the runtime classpath and leverage it in IsolatingClassLoaderFactory

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobOutputStream.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobOutputStream.java

Symptom:
Travis builds occasionally fail with org.mockito.exceptions.misusing.UnfinishedStubbingException for org.apache.samza.system.azureblob.avro.TestAzureBlobOutputStream.testCloseMultipleBlocks. 
Cause: 
Seems to be due to using PowerMockito.doAnswer for mocking com.azure.storage.blob.specialized.BlockBlobAsyncClient.commitBlockListWithResponse
Changes:
pull call to commitBlockListWithResponse into a package private method of AzureBlobOutputStream and verify that method.
Tests: 
Rerun of TestAzureBlobOutputStream in original code cause 240 failures in 10K runs
Rerun of TestAzureBlobOutputStream with this fix causes 0 failures in 10K runs

SAMZA-2476:Fix flaky tests in TestAzureBlobOutputStream

---

gradle.properties

**Symptom**: `gradle -b bootstrap.gradle` will download the wrapper for Gradle 5.2.1, but there are some other parts of Samza which are not compatible with Gradle 5.2.1. Trying to use the `gradlew` wrapper will fail.
**Cause**: https://github.com/apache/samza/pull/1203 did not fully migrate Samza to Gradle 5.2.1 (see https://github.com/apache/samza/pull/1295 for a more complete migration)
**Changes**: Reverted https://github.com/apache/samza/pull/1203, so that Samza is on Gradle 4.8.
**Tests**: Ran `./gradlew clean sourceRelease`, unpacked it, ran `gradle -b bootstrap.gradle` from within the unpacked source, and then verified that `gradle/wrapper/gradle-wrapper.properties` referred to Gradle 4.8.
**API changes**: None
**Usage changes**: None
This will only be applied to the 1.4.0 branch. …

Revert "Upgrade Gradle to 5.2.1 (#1203)"

---

samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/scala/org/apache/samza/container/TestTaskInstance.scala

**Symptom:** Container shuts down with exception on invocation of TaskStorageManager.removeOldCheckpoints from TaskInstance.commit
**Cause:** Concurrent modification of checkpoint directories by other processes / threads may cause FileNotFoundException to be thrown and shutdown the container. IOException may be thrown for other miscellaneous failures; these should not cause the container to shutdown but be logged and allow processing to continue.
**Tests:** Added a unit test which fails when exception from removeOldCheckpoints is not caught.
**Upgrade instructions:** None
**Usage instructions:** None

SAMZA-2464: Container shuts down when task fails to remove old state checkpoint dirs

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterResourceManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerAllocator.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/SamzaResource.java
samza-core/src/test/java/org/apache/samza/clustermanager/MockClusterResourceManager.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java
samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java

**Changes:** Today if samza apps are not able to use an allocated resource within
yarn.resourcemanager.rm.container-allocation.expiry-interval-ms
start of the container fails with this exception, this can be avoided by just setting an allocated resource timeout check before issuing a start
**API Changes:** Added isResourceExpired to ClusterResourceManager
**Upgrade Instructions:** None

SAMZA-2475: Add a allocated resource expiry timeout in samza yarn type of apps

---

build.gradle

Symptom: `./gradlew build` does not consistently succeed. Observed failures include tests reported as failing and/or running out of memory.
Cause: Recently, we upgraded to Gradle 5. Gradle 5 lowered some memory allocation defaults (https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#rel5.0:default_memory_settings), and it looks like the lower memory isn't sufficient for some tests.
Changes: Increase the memory for running tests for samza-core, which seems to be the impacted module.
Tests: Ran `./gradlew build`

[Test fix]: Increasing heap allocation for test executor for samza-core tests after Gradle 5 upgrade

---

samza-core/src/main/java/org/apache/samza/coordinator/metadatastore/CoordinatorStreamStore.java
samza-core/src/main/scala/org/apache/samza/job/local/ProcessJob.scala
samza-core/src/main/scala/org/apache/samza/job/local/ProcessJobFactory.scala
samza-core/src/test/scala/org/apache/samza/job/local/TestProcessJob.scala

Symptom: Users when deploying a job in dev will see an error message from the kafka consumer finalizer complaining about "kafka consumer allocated and not closed"
This error message will appear multiple times in their job and doesn't actually affect the job's performance or correctness. This leads to users falsely believing that any job failures is because of this message.
Cause:
All Kafka consumers have a finalize method in them. This means when the garbage collector determines that there's no more references to the consumer, it will try to close the consumer and find that the consumer wasn't closed properly yet. This happens because in the ProcessJobFactory, a CoordinatorStreamStore is initialized. It is then wrapped around a NamespaceAwareCoordinatorStreamStore. Later on when the …

SAMZA-2317: ProcessJob does not call CoordinatorStreamStore.close()

---

samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnClusterResourceManager.java

**Bug/Changes:** Yarn allocated resource expiry time default config is in ms, this was getting incorrectly declared using Duration.ofMinutes(...) instead of Duration ofMillis(...)
**Upgrade Instructions:** None
**Usage Instructions:** Instantiate ContainerPlacementMetadataStore to write Container placement messages to Metastore, query it by the UUID generated

SAMZA-2475: Fix allocated resource expiry bug

---

build.gradle

Symptom: CI build fails transiently with an error that looks like:
```
Execution failed for task ':samza-core_2.11:test'.
> Process 'Gradle Test Executor 6' finished with non-zero exit value 1
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.2.1/userguide/java_testing.html#sec:test_execution
```
Cause: Recently, we upgraded to Gradle 5. Gradle 5 lowered some memory allocation defaults (https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#rel5.0:default_memory_settings), and it looks like the lower memory isn't sufficient for some tests. We tried using 3g of memory in https://github.com/apache/samza/pull/1307, but it still looks like that is not enough.
Changes: …

[Test fix] removing minHeapSize and increasing maxHeapSize to 4g

---

samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerPlacementActions.java

**Symptom:**
Noticed a few runs being flaky with:
org.apache.samza.clustermanager.TestContainerPlacementActions > testAlwaysMoveToAnyHostForHostAffinityDisabled FAILED
java.lang.AssertionError: expected:<IN_PROGRESS> but was:<SUCCEEDED>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.apache.samza.clustermanager.TestContainerPlacementActions.testAlwaysMoveToAnyHostForHostAffinityDisabled(TestContainerPlacementActions.java:746)
**Cause:**
A race between main thread expects to read a success message from metastore and am-rm thread to write a success messages  
Changes:
Make the main thread busy loop on metastore success message, since a …

SAMZA-2484: Fix flaky tests for Container Placements

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobOutputStream.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobOutputStream.java

Symptom:
Travis builds occasionally fail with AssertionError for org.apache.samza.system.azureblob.avro.TestAzureBlobOutputStream.testFlushFailed.
Example: https://travis-ci.org/apache/samza/builds/658407113?utm_source=github_status&utm_medium=notification
Cause:
Seems to be due to using stubbing com.azure.storage.blob.specialized.BlockBlobAsyncClient.stageBlock throw an exception to make flush fail for AzureBlobOutputStream
Changes:
pull call to all of Blob client into package private methods of AzureBlobOutputStream and verify that method.
Tests:
Rerun of TestAzureBlobOutputStream in original code cause 230 failures in 60K runs
Rerun of TestAzureBlobOutputStream with this fix causes 0 failures in 60K runs

Fix new flaky test

---

samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala
samza-core/src/test/java/org/apache/samza/coordinator/TestJobModelManager.java

JobModelManager provides readJobModel() function to let `JobCoordinator`, `ClusterBasedJboCoordinator` and etc know the latest JobModel information.
If the users enable regex topic rewriter in their config, `readJobModel()` function will dynamically load the latest Kafka topic list and generate new TaskModel with new topic partition mappings.
However, it doesn't update the `task.inputs` in JobModel's Config. So other services depend on `task.inputs` information will still see stale data.
`JobModelManager.readJobModel()` uses the original config instead of the updated config to build `JobModel`.
Use updated config to build final `JobModel`.
None
None
None

SAMZA-2477: JobModel isn't updated with latest "task.inputs" if enabled regex topic rewriter

---

build.gradle
samza-core/src/test/resources/moreEnter.txt
samza-core/src/test/resources/noEnter.txt
samza-core/src/test/resources/oneEnter.txt
samza-core/src/test/resources/twoEnter.txt
samza-core/src/test/scala/org/apache/samza/system/filereader/TestFileReaderSystemAdmin.scala

Symptom:
samza-core:test are randomly failing.
Cause:
TestFileReaderSystemAdmin and TestFileReaderSystemConsumer are creating and deleting the same set of files, when runnig in parallel, FileNotFoundException could happen depending on the timing.
Changes:
1. Update TestFileReaderSystemAdmin to use test resource files.
2. Update assert conditions as we removed tailing spaces and newlines in the files.
3. Keep TestFileReaderSystemConsumer as it is because it is also appending data to test files, thus cannot share to use the same test resource file.
Tests:
./gradlew test
API Changes:
None
None
None

SAMZA-2486: Update TestFileReaderSystemAdmin to use test resource files

---

docs/_config.yml
docs/_menu/index.html
docs/learn/tutorials/versioned/hello-samza-high-level-code.md
docs/learn/tutorials/versioned/hello-samza-high-level-yarn.md
docs/learn/tutorials/versioned/hello-samza-high-level-zk.md
docs/learn/tutorials/versioned/samza-rest-getting-started.md
docs/startup/hello-samza/versioned/index.md

Changes: Updated website on 1.4.0 branch according to `docs/README.md`. This involves updating some references in the tutorials regarding the usage of a SNAPSHOT version and the "latest" branch of samza-hello-samza.
Testing: Deployed website locally and verified some of the documentation links.
API/Usage changes: N/A

Update versions on website for 1.4 release branch

---

docs/_blog/2020-03-17-announcing-the-release-of-apache-samza--1.4.0.md
docs/_config.yml
docs/_menu/index.html
docs/_releases/1.4.0.md
docs/archive/index.html
docs/startup/download/index.md

Changes: Updated master branch according to docs/README.md. Wrote the blog post for the 1.4 release and added some links to 1.4.0 to the website.
Testing: Deployed website locally and verified some of the documentation links.
API/Usage changes: N/A

SAMZA-2487: blog and other website updates for Samza 1.4.0 release

---

docs/_releases/1.0.0.md
docs/_releases/1.1.0.md
docs/_releases/1.2.0.md
docs/_releases/1.3.0.md
docs/_releases/1.4.0.md

Symptom: The horizontal RELEASES menu on the website pages do not show any options other than LATEST.
Cause: If the versioned page link can't be found, then the page will not show that version in the menu. The version property which is used to generate the versioned page links only has two parts (e.g. "1.0", "1.1"), but the pages are organized with 3-part versions (e.g. "1.0.0"), so the page links aren't found.
Changes: Use the 3-part version for the version property.
Tests: Deployed the website locally and saw the "1.0.0" entry in the horizontal menu. Note that the entries for "1.1.0"/"1.2.0"/"1.3.0" don't show up because no one published those versioned pages.
API/Usage changes: N/A

[minor] fix version property in releases pages

---

samza-core/src/main/java/org/apache/samza/operators/impl/AsyncFlatmapOperatorImpl.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestAsyncFlatmapOperatorImpl.java

Symptom: In beam samza runner, Op#close is not invoked during shutdown, which is not expected.
Cause: AsyncFlatmapOperatorImpl#handleClose() doesn't call transformFn.close(). Therefore the underlying transform function will never be closed.
Changes: Just invoke transformFn.close inside handleClose method should be enough.
Tests: Tested with a samza beam job. After the change, Op#close is able to function properly.

SAMZA-2490: AsyncFlatmapOperatorImpl#handleClose should call transformFn.close()

---

build.gradle
gradle/dependency-versions.gradle

Symptom: `samza-core` requires `maxHeapSize` set to 4g when running unit tests. Otherwise, the test suite may hang or fail (especially in the CI pipeline).
Cause: `TestZkMetadataStore` has some tests around large values being written to zookeeper. That test uses an embedded zookeeper which does a lot of debug logging. The current logging impl for samza-core unit tests is the log4j v1 impl, which somehow defaults to DEBUG logging.
Changes: Use log4j2 logging impl for unit tests, since it seems to default to ERROR logging. We don't need the unit tests of the committed code to report DEBUG logging.
Tests: `./gradlew :samza-core:test` no longer hangs with a lower memory allocation. Before this change, it would hang.
API changes: log4j2 version increased from `2.11.0` to `2.12.0`, so any apps …

SAMZA-2481: Improve memory usage in samza-core unit tests

---

samza-core/src/test/java/org/apache/samza/table/batching/TestBatchProcessor.java

Note - This seemed trivial enough to not create a ticket, but let me know if there should be a ticket
Symptoms: Currently in Linkedin internal, when building Samza with the latest open source changes on Mac, TestBatchProcessor tests keep failing.
Causes: Currently this TestSuiteAnnotation used in TestBatchProcessor is causing the tests to be ran twice when building using gradle (documented in gradle/gradle#5484). This seems to be causing issues internally where because we cap the memory used for testing to 1.5gb (in a recent commit) currently, leads to this test failing. The current theory is that Mac seems to be using more memory as building on Linux passes.
Fix: By removing the TestSuiteAnnotation, these tests are only ran once and leads to the build passing. As it seems like running …

Remove TestSuiteAnnotation from TestBatchProcessor

---

samza-core/src/main/java/org/apache/samza/container/ContainerHeartbeatMonitor.java
samza-core/src/test/java/org/apache/samza/container/TestContainerHeartbeatMonitor.java

Symptom: In some environments, the samza-core unit test suite fails with `Process 'Gradle Test Executor N' finished with non-zero exit value 1 This problem might be caused by incorrect test process configuration.`
Cause: `ContainerHeartbeatMonitor` submits a delayed "force shutdown" task (uses `System.exit(1)`) to shut down the process when the job coordinator dies. In `TestContainerHeartbeatMonitor`, this "force shutdown" task is not cancelled when the test is complete. If the remainder of the samza-core tests last longer than the shutdown timeout (2 minutes), then the shutdown task will kill the test suite process with an exit code of 1. In some environments, `TestContainerHeartbeatMonitor` runs late enough in the test suite (it seems like the ordering of test classes is …

SAMZA-2496: TestContainerHeartbeatMonitor does not properly stop the ContainerHeartbeatMonitor

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java

**Symptom**: A job deployment timed out waiting for application attempt to transition from New to Running.
**Cause**: ClusterBasedJobCoordinator threw an exception during startup due to a misconfiguration, but did not kill the AM process (likely due to non-daemon threads).
 Tests: manual tests

SAMZA-2491: log uncaught exceptions in JC

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/config/ClusterManagerConfig.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/processor/StreamProcessor.java
samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/main/java/org/apache/samza/startpoint/StartpointManager.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/main/scala/org/apache/samza/job/local/ProcessJobFactory.scala
samza-core/src/main/scala/org/apache/samza/job/local/ThreadJobFactory.scala

Symptom: Currently the startpoint manager queries metastore for task-ssps and for each ssp queries coordinator-store, issuing a re-read on the coordinator store. This causes increased AM startup time and depending on the number of input SSPs to a job (thousands in case of regex), YARN may timeout the AM.
Cause: Above.
Fix: This change reduces to number of metastore reads to 2; one for startpoints keyed by ssp and the other for startpoints keyed by ssp+taskname.

SAMZA-2501 : Optimizing startpoint manager to not make successive bootstrapMessage calls to coordinator-store

---

samza-core/src/main/java/org/apache/samza/runtime/ApplicationRunnerMain.java

Feature:
https://cwiki.apache.org/confluence/display/SAMZA/SEP-23:+Simplify+Job+Runner
Changes:
1. Add config-path option in ApplicationRunnerCommandLine.
2. Update loadConfig() to read property file specified by config-path as submission config.
Tests:
Followed https://samza.apache.org/startup/hello-samza/latest/ to test against Hello Samza example:
1. Update wikipedia-feed.properties to include the following properties:
job.config.loader.factory=org.apache.samza.config.loaders.PropertiesConfigLoaderFactory
job.config.loader.properties.path=./__package/config/wikipedia-feed.properties
2. Deploy the job:
deploy/samza/bin/run-app.sh --config-path=$PWD/deploy/samza/config/wikipedia-feed.properties
API Changes:
1. Add --config-path option support when running run-app.sh …

SAMZA-2499: Add submission config file support

---

samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-kafka/src/main/scala/org/apache/samza/checkpoint/kafka/KafkaCheckpointManager.scala
samza-kafka/src/test/scala/org/apache/samza/checkpoint/kafka/TestKafkaCheckpointManager.scala

**Feature:** Allow control of whether the underlying consumer backing a checkpoint manager will be left open (until stopped), or closed after the initial read of checkpoints
**Changes:** Introduces an internal config, injected by SamzaContainer, that is injected dependent on whether the container is standby or not, to control whether the container's checkpoint manager should have it's underlying consumer stopped after initial read or not.
 **Tests:** Added a unit test each for the config set to true / false
**Upgrade Instructions:** None 

SAMZA-2493: Keep checkpoint manager consumer open for repeated polling

---

samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-core/src/test/java/org/apache/samza/config/TestTaskConfig.java

**Feature:** Disable transactional state for use cases that are not yet supported
**Changes:** Modifies the logic to accessing the `task.transactional.state.restore.enabled` by returning false if standby or async commit are enabled.
 **Tests:** Added a unit test each for each permutation of configuration.
**Upgrade Instructions:** None 

SAMZA-2336: Disable transactional state restore when not supported

---

samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemAdmin.java
samza-kafka/src/test/java/org/apache/samza/system/kafka/TestKafkaSystemAdminWithMock.java

Currently, we only fetch ssp metadata from kafka only once, ideally we should add retry:
- to be consistent with function getSystemStreamMetadata()
- avoid any unexpected failure due to transient errors.
Issue:
Currently Samza will only fetch ssp metadata from kafka once. So some transient errors may cause the job dies.
Fix:
Adding retry to getSSPMetadata function to avoid issue happens.
Test:
Unit test.

SAMZA-2503 : Adding retry when getting ssp metadata from kafka

---

samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java

**Symptom**: A race between the process callback thread and the runloop thread can result in incorrect shutdown status for shutdown triggered by end of stream.
**Issue**: Currently runloop performs message choosing and dispatching in a loop indefinitely until interrupted by a shutdown request or an exception during processing. In async mode, message completion is notified by the process callback thread using `onComplete()` and `onFailure()` to represent corresponding success and failure. The failure callback updates the exception code within the runloop to notify processing failures. Similarly, shutdown can be requested by user code or end of stream messages through various scopes(task level, container level). These requests are notified to the runloop through shutdownNow flag.
Currently …

SAMZA-2510: Incorrect shutdown status due to race between runloop and process callback thread

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterResourceManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerAllocator.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/StandbyContainerManager.java
samza-core/src/main/java/org/apache/samza/clustermanager/container/placement/ContainerPlacementMetadata.java
samza-core/src/test/java/org/apache/samza/clustermanager/MockClusterResourceManagerCallback.java
samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java

Problem: The standby container manager does not handle container-stop-failures.
These events can happen as a result of certificate/authentication issue during the execution of the container-stop. The problem is the standby-container-failover flow relies on a stop-container succeeding and in this case does not complete the failover. This means the active container, for which a failover was initiated, is never started again.
In case of a container-placement action, that runs into container-stop-fail, the action is declared as failed. 
Cause: Above.
Fix: The fix is for standby-container-manager to intercept and handle these events by continuing the failover by either selecting another standby container (if one is present i.e., rf > 2) or using a standby host or using any-host.
API changes: …

SAMZA-2511 : Adding logic to handle container stop fail 

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/config/ShellCommandConfig.java
samza-core/src/test/java/org/apache/samza/config/TestJobConfig.java
samza-yarn/src/main/scala/org/apache/samza/job/yarn/YarnJob.scala
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnJob.java

Currently, we are using `samza.cluster.based.job.coordinator.dependency.isolation.enabled` to show if Samza application enables split deployment on job coordinator.
However, we also need one similar config for the job container with the same purpose. 
So we'd better consolidate them to one generic config `job.split.deployment.enabled`.
1. Renamed `ShellCommandConfig.ENV_CLUSTER_BASED_JOB_COORDINATOR_DEPENDENCY_ISOLATION_ENABLED` to `ShellCommandConfig. ENV_SPLIT_DEPLOYMENT_ENABLED `
2. Renamed `JobConfig. CLUSTER_BASED_JOB_COORDINATOR_DEPENDENCY_ISOLATION_ENABLED ` to `JobConfig. JOB_SPLIT_DEPLOYMENT_ENABLED `
None
None
None

SAMZA-2509: New config name to represent if split deployment feature is enabled

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/util/SplitDeploymentUtil.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestClusterBasedJobCoordinator.java
samza-core/src/test/java/org/apache/samza/util/TestSplitDeploymentUtil.java

Currently, we define the `runWithClassLoader` method in `ClusterBasedJobCoordinator` to support split deployment. However, the job container needs a similar `runWithClassLoader` method to support split deployment. So we'd better make the `runWithClassLoader` method more generic, then `LocalContainerRunner` can just use it.
Add new util class `SplitDeploymentUtil ` to define generic `runWithClassLoader` method.
None
None 
None

SAMZA-2514: Refactor codes to make runWithClassLoader method more generic

---

samza-core/src/main/java/org/apache/samza/storage/StorageManagerUtil.java
samza-core/src/main/java/org/apache/samza/storage/TaskSideInputStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/java/org/apache/samza/storage/TestTaskSideInputStorageManager.java

Problem: When a Kafka broker returns null for oldest-offset, because of a OpenJDK bug (https://bugs.openjdk.java.net/browse/JDK-8148463), the collect() operation in TaskSideInputStorageManager can fail with a misleading null-pointer-exception message.
Note however that, Kafka broker cannot return null for oldest-offset. 
Cause: Above.
Fix: The fix is to use the suggested workaround for the bug https://bugs.openjdk.java.net/browse/JDK-8148463
And update the exception and log messages in case the oldest-offset are returned as null from Kafka.

SAMZA-2517 : Adding handling and relevant exception message for null in oldest offset from system-admin

---

samza-core/src/main/java/org/apache/samza/clustermanager/JobCoordinatorLaunchUtil.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/java/org/apache/samza/clustermanager/TestJobCoordinatorLaunchUtil.java
samza-core/src/test/scala/org/apache/samza/util/TestCoordinatorStreamUtil.scala

Design:
Changes:
1. Add readLaunchConfigFromCoordinatorStream() in CoordinatorStreamUtil
2. Add an extra step in JobCoordinatorLaunchUtil to invoke readLaunchConfigFromCoordinatorStream()
API Changes:
None
None
None
Tests:
Unit Tests

SAMZA-2518: Update JobCoordinatorLaunchUtil to fetch launch config from metadata store.

---

samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-core/src/test/java/org/apache/samza/system/MockSystemFactory.java
samza-kafka/src/test/scala/org/apache/samza/config/TestKafkaConfig.scala

**Feature:** Turning transactional state restore on by default in order to roll out at-least-once fixes.
**Changes:** Changes the default value of `task.transactional.state.restore.enabled` from `false` to `true`.
 **Tests:** Wrote a test job that writes two sets of data, with a commit in between. Verified that on restart, only the first set of data (which is committed) gets restored.
**Upgrade Instructions:** Please reference the [samza configuration page](https://samza.apache.org/learn/documentation/latest/jobs/samza-configurations.html#advanced-storage-configurations) for notes on configuring compaction lag for store changelogs that are backed by Kafka. For existing stores, the store specific configuration (`stores.store-name.changelog.min.compaction.lag.ms`) must …

Setting transactional state restore to default enabled

---

build.gradle

Dependency Version Alignment between Samza Sql and Calcite of the[ janino compiler](https://github.com/apache/calcite/blob/e3fe745a4e8e5e15ae5e04345975c98ab737b31b/gradle.properties#L96), moving to commons-compiler 3.0.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/samza/1357)

SAMZA-2521: Dependency Version Alignment between Samza Sql and Calcite of the janino compiler

---

samza-core/src/main/java/org/apache/samza/scheduler/EpochTimeScheduler.java
samza-core/src/test/java/org/apache/samza/scheduler/TestEpochTimeScheduler.java

**Issue**: In EpochTimeScheduler, when the caller tries to register a duplicate timer with new callback, Samza throws an exception. This behavior prevents callers from updating the callbacks for a given timer key. 
**Changes**: Allow registration for duplicate timer key where the newer callback will overwrite the previous callback provided it can be canceled. Refer to API changes section for semantics change to the existing API.
**Tests**: Added unit tests to validate scenarios where duplicate registration succeeds vs no-ops.
**API Changes**: `setTimer` API now allows duplicate timer registration. The semantics of the duplicate registration is as follows
1. Duplicate registrations will attempt the cancel the previously registered callbacks. If its unsuccessful, the new request to register …

SAMZA-2519: Support duplicate timer registration

---

samza-core/src/main/java/org/apache/samza/util/Util.java
samza-core/src/test/java/org/apache/samza/util/TestUtil.java

Symptom: Job to fail to launch.
Cause: Backslash and grave accent in submission config is not properly escaped, causing launch.sh to break.
Changes: Update Util#envVarEscape to escape backslash as well as grave accent.
Tests: Unit tests updated to test such cases.

SAMZA-2523: Update Util#envVarEscape to escape more characters

---

samza-core/src/main/java/org/apache/samza/util/Util.java
samza-core/src/test/java/org/apache/samza/util/TestUtil.java

Symptom: Job to fail to launch.
Cause: apostrophe in config is escaped causing SamzaObjectMapper.getObjectMapper().readValue to fail on AM when reading env var.
Changes: Update Util#envVarEscape not to escape apostrophe.
Tests: Unit tests updated to test such cases.

SAMZA-2524:Fix Util#envVarEscape not to escape apostrophe

---

docs/learn/documentation/versioned/jobs/samza-configurations.md
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobConfig.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriter.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriterFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobOutputStream.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobSystemProducer.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobWriterFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/utils/BlobMetadataContext.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/utils/BlobMetadataGenerator.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/utils/BlobMetadataGeneratorFactory.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/utils/NullBlobMetadataGenerator.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/utils/NullBlobMetadataGeneratorFactory.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobAvroWriter.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobOutputStream.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/producer/TestAzureBlobSystemProducer.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/utils/TestNullBlobMetadataGenerator.java

**Feature:** This PR extends the existing AzureBlobSystemProducer by adding the ability to enhance an azure storage blob with metadata - basically key-value pairs to the blob's metadata (sits outside of the blob's actual content). This aids tremendously in ingesting these blobs into Kusto (Azure's data explorer). 
**Changes:** New interfaces BlobMetadataGeneratorFactory, BlobMetadataGenerator and class BlobMetadataContext added where the user needs to implement BlobMetadataGeneratorFactory and BlobMetadataGenerator which takes in a BlobMetadataContext containing the stream name and the size of the current blob being committed. An instance of the generator will be created when the blob is about to be committed. Generator is invoked to get metadata and the returned metadata is attached to …

SAMZA-2522: Add metadata generator for azure storage blob

---

samza-yarn/src/main/scala/org/apache/samza/job/yarn/ClientHelper.scala

Symptom:Incorrect job status reported, which is previous deployed job status instead of current job.
Cause:ClientHelper#isActiveApplication is invoking toAppStatus twice when comparing status to Running or New. It could happen that 1st time, the status is New which failed Running check, and 2nd invocation returns Running, which failed New check, this will result in the current app to be classified as non active causing ClientHelper to return job status of a previous deployed app.
Changes: Update ClientHelper#isActiveApplication to invoke toAppStatus once and compare both status against this single result.
Tests: None

SAMZA-2525:Fix race condition in ClientHelper#isActiveApplication

---

samza-core/src/main/java/org/apache/samza/system/inmemory/InMemoryManager.java
samza-core/src/test/java/org/apache/samza/system/inmemory/TestInMemoryManager.java

I found this when refactoring side input restore to use RunLoop (https://github.com/apache/samza/pull/1343); this patch is necessary to prevent integration tests from failing after that refactor as marking side inputs as caught up relies on newest offset.
**Symptom:** When an end of stream message is present in an in memory SSP, the new and upcoming offset are reported as 1 higher than they should be.
Example:
| E0, offset: 0 | E1, offset: 1 | ... | E3, offset: 3 | EndOfStream |
In the above case, InMemoryManager will report a newestOffset of 4 and an upcomingOffset of 5; they should be 3 and 4 respectively.
See the jira ticket for a more in depth analysis of semantics of end of stream as it relates to offset metadata.
**Cause:** InMemoryManager treats end of stream as any other envelope …

SAMZA-2506: Inconsistent end of stream semantics in SystemStreamPartitionMetadata

---

samza-core/src/main/java/org/apache/samza/clustermanager/JobCoordinatorLaunchUtil.java

Symptom: Job failed to launch.
Cause: Metadata store is not initialized before invoking readLaunchConfigFromCoordinatorStream()
Changes: Init metadata store before invoking readLaunchConfigFromCoordinatorStream
Tests: None

SAMZA-2527:MetadataStore is not initialized before reading in JobCoordinatorLaunchUtil

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriter.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobAvroWriter.java

**Bug fix**
**Symptom:** No visible symptoms seen yet. Potential symptom is invalid blobs created.
**Cause:** When Avro's DataFileWriter.close fails, blob is committed with uploaded blocks which means the sync marker flushed by DataFileWriter.close is absent potentially causing invalid blobs.
**Changes:** No commit of blob if DataFileWriter.close fails. This means uploaded blocks are discarded in this scenario and user of the SystemProducer should catch this exception and retry to avoid data loss.
**API changes:** Behavior change: Blob not committed if DataFileWriter.close fails discarding all uploaded blocks.
**Upgrade Instructions:** Catch exceptions arising out of AzureBlobSystemProducer.flush and retry messages since previous flush. Do not advance checkpoint if flush fails.
**Usage …

SAMZA-2526: Azure blob system producer: do not commit blobs if avro DataFileWriter.close fails

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriter.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobOutputStream.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/utils/BlobMetadataContext.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobAvroWriter.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobOutputStream.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/utils/TestNullBlobMetadataGenerator.java

Feature: Enable addition of number of records in a blob to the blob's metadata. 
Changes: BlobMetadataContext passed as input to BlobMetadataGenerator interface now have an additional field giving the number of records in the blob. This can be used as needed by the generator.
API changes: BlobMetadataContext passed as input to BlobMetadataGenerator interface now have an additional field giving the number of records in the blob. This can be used as needed by the generator.
Tests: unit test updated.

SAMZA-2534: AzureBlobSystemProducer: Enable adding of number of records in blob as metadata of the blob

---

samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/java/org/apache/samza/container/RunLoopFactory.java
samza-core/src/main/java/org/apache/samza/container/RunLoopTask.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java
samza-core/src/test/scala/org/apache/samza/container/TestTaskInstance.scala

**Issues**: Hard to reuse RunLoop for non-TaskInstance use cases because of coupling
**Changes**: This PR extracts the existing contract between `TaskInstance` and `RunLoop` into a new interface `RunLoopTask`. `RunLoopTask` will allow other implementers from `TaskInstance` to also leverage `RunLoop`, something we anticipate doing with side input processing after this PR is merged.
This is largely a refactor. However, I also clean up the unneeded use of `TaskInstance.isAsyncTask`. Because in `SamzaContainer` we will always wrap any supplied `StreamTask` with `AsyncStreamTaskAdapter`, this method returns true in all cases. This makes it possible to clean up some validation from `RunLoopFactory`, and the control flow within `TaskInstance.process`
**Tests**: I've re-written all unit tests in …

SAMZA-2529: Extract interface from TaskInstance for reuse of RunLoop

---

samza-core/src/main/scala/org/apache/samza/metrics/reporter/MetricsSnapshotReporter.scala
samza-core/src/main/scala/org/apache/samza/metrics/reporter/MetricsSnapshotReporterFactory.scala
samza-core/src/test/java/org/apache/samza/metrics/TestMetricsSnapshotReporter.java

Changes:
The refactoring is done to make the reporter stable when
exceptions are encountered. The patch also breaks down
MetricsSnapshotReporterFactory#getMetricsReporter into
smaller overridable pieces to make it more extendable/re-usable.
Tests: Unit test

SAMZA-2532: Refactor MetricsSnapshotReporter and MetricsSnapshotReporterFactory

---

samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala

**Symptom:** State restore logs trimmed incorrectly
**Cause:** Log statement references variable for restored rather than trimmed messages
**Tests:** none
**Upgrade instructions:** None
**Usage instructions:** None

SAMZA-2520: Log statement for trimmed messages is incorrect

---

samza-core/src/main/java/org/apache/samza/execution/JobPlanner.java
samza-core/src/test/java/org/apache/samza/execution/TestJobPlanner.java

**Symptom [Bug fix]:** 
- LegacyTaskApplication (ones that do not use descriptors) are missing app.run.id config which makes container placements nonusable with them
- Ideally app.run.id should be injected for all types of apps
**Changes:** Make all kinds of app generate app.run.id
**API changes:** None
**Upgrade Instructions:** None

Samza-2540: Legacy Task application are missing app.run.id for both batch & stream jobs

---

samza-core/src/main/java/org/apache/samza/storage/TaskSideInputHandler.java
samza-core/src/main/java/org/apache/samza/storage/TaskSideInputStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/java/org/apache/samza/storage/TestTaskSideInputHandler.java
samza-core/src/test/java/org/apache/samza/storage/TestTaskSideInputStorageManager.java

**Issues**: `TaskSideInputStorageManager` conflates both processing and storage logic. This is problematic as adding support of transactional state in standby containers requires heavy additions to both. Refactoring is necessary in order to avoid `TaskSideInputStorageManager` from becoming a difficult to maintain behemoth (like `ContainerStorageManager` is now). After this change, introduction of support for transactional state in standby containers can evolve cleanly.
**Changes**: Processing logic is moved out of `TaskSideInputStorageManager` and into a new class `TaskSideInputHandler`. This includes: coordination of oldestOffsets, lastProcessedOffsets, startingOffsets, and processing behavior for a given SSP envelope.
Management of stores' StorageEngines remains in …

SAMZA-2530: Split out processing logic from TaskSideInputStorageManager

---

samza-rest/src/test/java/org/apache/samza/rest/resources/BaseJerseyTest.java
samza-rest/src/test/java/org/apache/samza/rest/resources/TestJobsResource.java
samza-rest/src/test/java/org/apache/samza/rest/resources/TestTasksResource.java

By default, Jersey uses the default port "9998" to start the test HTTP server. If the port "9998" is used by other processes, the test cases will face "java.net.BindException: Address already in use".
The Jersey test framework provides the ability to dynamically choose an available port by setting `jersey.config.test.container.port` as 0 explicitly.
Example exception:
```
"org.glassfish.jersey.test.spi.TestContainerException: java.net.BindException: Address already in use
at org.glassfish.jersey.test.grizzly.GrizzlyTestContainerFactory$GrizzlyTestContainer.start(GrizzlyTestContainerFactory.java:112)
at org.glassfish.jersey.test.JerseyTest.setUp(JerseyTest.java:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```

SAMZA-2546: Make Jersey test server use dynamic ports instead of default port

---

samza-core/src/main/java/org/apache/samza/execution/JobGraphJsonGenerator.java
samza-core/src/test/java/org/apache/samza/execution/TestJobGraphJsonGenerator.java

There is `tableId` information for `StreamTableJoinOperatorSpec` in Samza job execution plan:
```json
"samza-hello-fluent-api-remote-table-venice-i001-alazhang-join-1": {
"opId": "samza-hello-fluent-api-remote-table-venice-i001-alazhang-join-1",
"tableId": "table-id",
"opCode": "JOIN",
"sourceLocation": "VeniceRemoteTableJoinApp.java:69",
"nextOperatorIds": [
"samza-hello-fluent-api-remote-table-venice-i001-alazhang-send_to-2"
]
}
```
However, there is no `tableId ` information for `SendToTableOperatorSpec`.
```json
"samza-hello-fluent-api-remote-table-venice-i001-alazhang-send_to-2": {
"opId": "samza-hello-fluent-api-remote-table-venice-i001-alazhang-send_to-2",
"opCode": "SEND_TO",
"sourceLocation": "VeniceRemoteTableJoinApp.java:70",
"outputStreamId": "PageViewUserAgentTypeEvent", …
```

SAMZA-2547: Add missing "tableId" for SendToTableOperatorSpec in Samza job execution plan

---

samza-kafka/src/test/scala/org/apache/samza/checkpoint/kafka/TestKafkaCheckpointManager.scala

Symptom: `TestKafkaCheckpointManager.testWriteCheckpointShouldRecreateSystemProducerOnFailure` was not enabled. It also did not pass when it was enabled. It doesn't seem like this was a disabled flaky test; just seems like the author forgot to enable it.
Cause:
1. Missing the `@Test` annotation.
2. Retry timeout was set too low, so the test never had the chance to recreate the system producer.
Tests: `./gradlew :samza-kafka:test --tests TestKafkaCheckpointManager`
API/Usage changes: N/A

[Minor test fix] Enabled and fixed a TestKafkaCheckpointManager test

---

samza-sql/src/test/java/org/apache/samza/sql/util/SampleRelTableKeyConverter.java
samza-sql/src/test/java/org/apache/samza/sql/util/SampleRelTableKeyConverterTest.java

This PR is a **Bug fix**
**Symptom:** When one of the value for filter condition is null.
**Cause:**  Will lead to an NPE
**Changes:** Added handling for null case 
**Tests:** Added more tests and run current tests end to end.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/samza/1388)

SAMZA-2553: Fix NPE when one of the condition value is null

---

checkstyle/checkstyle-suppressions.xml
checkstyle/checkstyle.xml

- By using exact DTD definitions, checkstyle tool will locate resources from within its own jar, avoiding download.
- Using exact values from checkstyle 6.11.2 release, see:
- configuration: https://github.com/checkstyle/checkstyle/blob/checkstyle-6.11.2/src/main/resources/com/puppycrawl/tools/checkstyle/configuration_1_3.dtd#L6
- suppressions: https://github.com/checkstyle/checkstyle/blob/checkstyle-6.11.2/src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_1.dtd#L6

SAMZA-2555: Prevent downloading checkstyle DTD over the internet

---

samza-sql/src/main/java/org/apache/samza/sql/translator/FilterTranslator.java

This happens when the filter expression is evaluated over a null column.
**Symptom:** Logging an error message on each record when the actual state is correct leads to a false positive alerts and will flood the log files for no reason.
**Cause:** handling of null case when the class is not correct.
**Changes:** Removed the logging when the value is null.
**Tests:** Run the Samza SQL tests end to end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/samza/1387)

SAMZA-2552: Avoid logging false positive error message on each record.

---

samza-sql/src/main/java/org/apache/samza/sql/translator/JoinTranslator.java
samza-sql/src/test/java/org/apache/samza/sql/translator/TestJoinTranslator.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlRemoteTable.java

- **Bug Fix:** SAMZA-2554
- **Symptom:** When the join condition has more than one predicate, current impls just ignore part of the join predicate and returns wrong results.
- **Changes:** This PR does:
1. Block any query  with more than one predicate from running and returning wrong results to user. In a follow up work will add some handling for a conjunction of join predicate.
2. Another Item added by this PR is the checking for an existing input reference that is Expression Free and it point directly to the primary key of remote table. As of Today the convention is to call such column `__key__`. In the future will be better to allow the table implementation chose what every name/type
- **Tests:** Added more tests and run current tests end to end.
I did remove one of the very complex …

SAMZA-2554: Fix the handling of join condition against remote table

---

build.gradle
checkstyle/checkstyle-suppressions.xml
samza-elasticsearch/src/main/java/org/apache/samza/config/ElasticsearchConfig.java
samza-elasticsearch/src/main/java/org/apache/samza/system/elasticsearch/ElasticsearchSystemAdmin.java
samza-elasticsearch/src/main/java/org/apache/samza/system/elasticsearch/ElasticsearchSystemProducerMetrics.java
samza-elasticsearch/src/test/java/org/apache/samza/config/ElasticsearchConfigTest.java
samza-elasticsearch/src/test/java/org/apache/samza/system/elasticsearch/ElasticsearchSystemProducerMetricsTest.java
samza-elasticsearch/src/test/java/org/apache/samza/system/elasticsearch/ElasticsearchSystemProducerTest.java
samza-elasticsearch/src/test/java/org/apache/samza/system/elasticsearch/indexrequest/DefaultIndexRequestFactoryTest.java
samza-hdfs/src/main/java/org/apache/samza/system/hdfs/descriptors/HdfsSystemDescriptor.java
samza-hdfs/src/test/java/org/apache/samza/system/hdfs/TestHdfsSystemConsumer.java
samza-hdfs/src/test/java/org/apache/samza/system/hdfs/partitioner/TestDirectoryPartitioner.java
samza-hdfs/src/test/java/org/apache/samza/system/hdfs/reader/TestAvroFileHdfsReader.java
samza-kv-couchbase/src/test/java/org/apache/samza/table/remote/couchbase/TestCouchbaseBucketRegistry.java
samza-kv-inmemory/src/test/java/org/apache/samza/storage/kv/inmemory/TestInMemoryKeyValueStore.java
samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbOptionsHelper.java
samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbReadingTool.java
samza-kv-rocksdb/src/test/java/org/apache/samza/storage/kv/TestRocksDbKeyValueStoreJava.java
samza-tools/src/main/java/org/apache/samza/tools/GenerateKafkaEvents.java
samza-tools/src/main/java/org/apache/samza/tools/RandomValueGenerator.java
samza-tools/src/main/java/org/apache/samza/tools/SamzaSqlConsole.java
samza-tools/src/main/java/org/apache/samza/tools/avro/AvroSchemaGenRelConverterFactory.java
samza-tools/src/main/java/org/apache/samza/tools/avro/AvroSerDeFactory.java
samza-tools/src/main/java/org/apache/samza/tools/benchmark/AbstractSamzaBench.java
samza-tools/src/main/java/org/apache/samza/tools/benchmark/ConfigBasedSspGrouperFactory.java
samza-tools/src/main/java/org/apache/samza/tools/benchmark/SystemConsumerBench.java
samza-tools/src/main/java/org/apache/samza/tools/benchmark/SystemConsumerWithSamzaBench.java
samza-tools/src/main/java/org/apache/samza/tools/benchmark/SystemProducerBench.java

Issues: Several modules never had checkstyle enabled, so they were inconsistent with Samza checkstyle.
Changes: Enable checkstyle for all modules automatically through `subprojects` in `build.gradle` and make the code consistent with checkstyle. This will automatically apply checkstyle to new modules in the future as well.
Tests: Ran compilation and unit tests.
API/Upgrade/Usage changes: None
Note for reviewers: There is no expected change in functionality.

SAMZA-2551: Upgrade all modules to automatically use checkstyle 6.11.2 (part 6: enable for all modules)

---

samza-sql/src/main/java/org/apache/samza/sql/dsl/SamzaSqlDslConverter.java
samza-sql/src/main/java/org/apache/samza/sql/planner/QueryPlanner.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlFilterRemoteJoinRule.java
samza-sql/src/main/java/org/apache/samza/sql/planner/SamzaSqlValidator.java
samza-sql/src/main/java/org/apache/samza/sql/runner/SamzaSqlApplicationConfig.java
samza-sql/src/main/java/org/apache/samza/sql/translator/JoinInputNode.java
samza-sql/src/main/java/org/apache/samza/sql/translator/JoinTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/translator/QueryTranslator.java
samza-sql/src/main/java/org/apache/samza/sql/util/SamzaSqlQueryParser.java
samza-sql/src/test/java/org/apache/samza/sql/planner/TestQueryPlanner.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlRemoteTable.java

**Feature:**
Samza Sql currently does not have a query optimizer. As a result, we rely on users to write their queries in such a way that the sql execution is optimized which is often clumsy and non-intuitive. Adding Query optimization will make sql query more intuitive at the same time making the plan optimized.
**Changes**
This change adds rule based optimizer (HepPlanner) to Samza Sql query planner. As part of this commit, FilterJoinRule is added for remote table joins.
Added remote table join tests to ensure the plan is optimized.

SAMZA-2549 - Samza-sql: Add query optimizations for remote table joins

---

samza-sql/src/main/java/org/apache/samza/sql/translator/ProjectTranslator.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

**Currently:** Flatten udf return a wrong type
```sql
SELECT FLATTEN(ARRYA[1,2]), 'value' form table;
-- expected result is 
1,value
2,value
-- current result is 
[1],value
[2],value
```
**Fix:** return the actual inner value and add more tests

[SAMZA-2575] Fix the flatten output values and add more tests

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java
samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppenderMetrics.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/TestStreamAppender.java

Feature:
1. Make StreamAppender extend-friendly. 
2. Add metrics reporter into StreamAppender to report collected local metrics.
3. Add log message count and bytes metrics in StreamAppender
Changes:
1. Rewrite StreamAppender to expose private members/functions as protected and split some heavy functions into small trunks.
2. Add metrics reporter to report the metrics we collect locally
3. Add those new metrics into StreamAppender
Tests:
1. Unit tests pass for updated StreamAppender
2. ./gradlew build.
API Changes: two new metrics will be introduced in StreamAppender and will get reported if metrics reporter is set. This applies to application that uses StreamAppender in log4j2.xml
Upgrade/usage instructions:
1. If users write new appender or extends existing StreamAppender for own use …

SAMZA-2569: Add features into StreamAppender

---

samza-core/src/main/java/org/apache/samza/coordinator/StreamPartitionCountMonitor.java

The monitor needs to shutdown whenever the applications shuts down regardless of its state.

make MonitorPartition thread a daemon

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/MockSystemProducerAppender.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/TestStreamAppender.java

Problem: 
In both StreamAppender for log4j1 and log4j2 a blocking queue is used to coordinate between the append()-ing threads and a single thread send()-ing to Kafka.
This is a bounded, blocking, lock-synchronized queue.
To avoid deadlock scenarios (see SAMZA-1537), the append()-ing threads have a timeout of 2 seconds, after which the log message is discarded and the queue is drained. 
This means in case of message bursts, threads calling append() may block for upto 2 seconds, and may continually be stuck in this pattern, leading to processing stalls and lowered throughput. 
Solutions for Log4j2 
Solution 1. Enable async logger in log4j2, since they are supported and provided in log4j2.https://logging.apache.org/log4j/2.x/manual/async.html.
In using this capability, the blocking-queue in …

SAMZA-2577 : Adding support for Async-Logger in Log4j2 Stream Appender

---

samza-api/src/main/java/org/apache/samza/metrics/SamzaHistogram.java

Symptom: Missing metrics. EventSystemConsumer consumer lag latency
metrics are missing.
Cause: Histogram update and percentile gauges are updated in two
different functions. Percentiles are internal to Samza histogram and
hence should be updated internally as part of update.
Changes: Histogram update also updates internal gauges.

SAMZA-2581: Fix Samza Histogram update to update percentile Gauge values

---

samza-api/src/main/java/org/apache/samza/system/BoundedSSPIterator.java
samza-api/src/main/java/org/apache/samza/system/ChangelogSSPIterator.java
samza-api/src/test/java/org/apache/samza/system/TestBoundedSSPIterator.java
samza-core/src/main/java/org/apache/samza/storage/TransactionalStateTaskRestoreManager.java
samza-core/src/test/java/org/apache/samza/system/MockSystemFactory.java

**Symptom:** On transactional state restore, trimming may execute indefinitely.
**Cause:** Newly trimmed messages of the changelog are passed back to the trim process (and are then re-trimmed) by the changelog ssp iterator.
**Changes:** Introduce a bounded iterator which can be given an end offset to stop after.
**Tests:** Unit tests for the new class.
**API Changes:** none
**Upgrade Instructions:** none
**Usage Instructions:** none

SAMZA-2578: Excessive trimming during transactional state restore

---

samza-api/src/main/java/org/apache/samza/metrics/SamzaHistogram.java
samza-api/src/test/java/org/apache/samza/metrics/TestSamzaHistogram.java

SamzaHistogram gauges are instantiated via passed in metric registry
newGauge api. The new Gauge api in turn tries to instantiate
HistogramGauge. The newGauge api calls getValue on HistogramGauge
which in turn tries to update the Histogram Gauge values. This means
we are updating Histogram Gauge values in process of creating it.
As a fix, we add  null check in Gauge getValue to avoid NPE.

SAMZA-2583: Fix NPE in update SamzaHistogram Gauge values

---

samza-core/src/main/java/org/apache/samza/clustermanager/ContainerManager.java

**Changes**: The current restart ability for container placements works in the following way:
1. Tries to fetch resources on a host
2. Stops the active container if resources are accrued
3. Tried to start the container on host accrued
In production, we have seen the following observation at Linkedin
1. Some jobs are configured to use resources for the peak which leads to no headroom left on a host for requesting additional resources
2. This leads to restart requests failing due to not able to get resources on that host
A fix to this is to implement a force-restart utility , in this version we will stop the container first and then accrue resources. The upside being we will at least free up the resources on the host before issuing resource request, the downside being it will be a …

SAMZA-2579: Force restart feature for Container Placements

---

samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java
samza-yarn/src/main/scala/org/apache/samza/job/yarn/SamzaYarnAppMasterLifecycle.scala
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnClusterResourceManager.java

**Changes**: Modified the shutdown sequence inside YarnClusterResourceManager in order to bring down the AM when the NM on which it resides dies. This prevents the existence of orphaned AMs.
**Tests**: Tested the change by manually bringing down the NM on which the AM resided with a yarn job deploy and LXC

SAMZA-2585: Modify shutdown sequence to handle orphaned AMs

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/serializers/LoggingEventJsonSerde.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/TestStreamAppender.java

Issues: Currently, the log4j2 StreamAppender emits the log message as an Object instead of a String
Changes: Extracted the logging message as a String from the LoggingEvent instead of Object
Upgrade instructions: None
Usage instructions: None
Tests: Modified existing tests to work with this change. Also tested with a test job and checked the result on ELK.

SAMZA-2588: Fix log4j2 StreamAppender output to emit String instead of Object

---

gradle/dependency-versions.gradle
samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinatorRunner.java
samza-core/src/main/java/org/apache/samza/clustermanager/DefaultApplicationMain.java
samza-core/src/main/java/org/apache/samza/config/ApplicationConfig.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestDefaultApplicationMain.java

Issues: app.main.class is only set for Beam apps which causes different workflow on AM when launching a job.
Changes:
1. Introduce DefaultApplicationMain to capture launch workflow for High/Low level jobs so on AM, all jobs are launched in the same way: ClusterBasedJobCoordinatorRunner#main -> app.main.class -> JobCoordinatorLaunchUtil
2. Update ApplicationConfig#getAppMainClass to default to DefaultApplicationMain
Tests:
1. Unit Tests
2. Deployed hello samza job successfully with the change following instructions on http://samza.apache.org/startup/hello-samza/latest/

SAMZA-2589: Consolidate Beam and High/Low Samza Apps launch workflow

---

samza-api/src/main/java/org/apache/samza/table/descriptors/RemoteTableDescriptor.java
samza-core/src/test/java/org/apache/samza/table/remote/descriptors/TestRemoteTableDescriptor.java

Issues: currently the table api read/write rate limit is not emitted by samza
Changes:
1. Emit table API read/write rate limit in RemoteTableDescriptor. The names of the new metrics are:
**tables.table-id.io.read.credits** and **tables.table-io.write.credits**
Tests:
1. Unit Tests

Adding internal table-api config for table-api rate limits

---

samza-api/src/main/java/org/apache/samza/system/SystemAdmin.java
samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/config/SystemConfig.java
samza-core/src/main/java/org/apache/samza/execution/StreamManager.java
samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/main/java/org/apache/samza/standalone/PassthroughJobCoordinator.java
samza-core/src/main/java/org/apache/samza/system/SystemAdmins.java
samza-core/src/main/java/org/apache/samza/util/DiagnosticsUtil.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/main/scala/org/apache/samza/config/RegExTopicGenerator.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemAdmin.java

This is second pr to supplement commit: 4d97a8d
Changes: Added addition label info to SystemAdmin to help user provide more information to SystemFactory.
API Changes: Added several new functions to help provide more parameter. Won't impact current users.

SAMZA-2574 : improve flexibility of SystemFactory interface

---

samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/java/org/apache/samza/task/TaskCallbackImpl.java
samza-core/src/test/java/org/apache/samza/task/TestTaskCallbackManager.java

**Problem**: TaskCallbackImpl currently stores the entire message envelope. In case of jobs that have 1000s of pending callbacks, this adds up to significant memory pressure. The only use for message envelope is to trace the SSP information and the offset associated with it so that we commit the right offset during our commit cycle.
**Changes**: Modify TaskCallbackImpl to only store SSP and Offset information.
**Tests**: None

SAMZA-2593: Update task callback to store only necessary fields instead of the message envelope

---

samza-core/src/main/java/org/apache/samza/serializers/IntermediateMessageSerde.java
samza-core/src/test/java/org/apache/samza/serializers/model/serializers/TestIntermediateMessageSerde.java

Symptom: The user provided serde failed to deserialize a message. Then, IntermediateMessageSerde tried to deserialize the message for the second time, which caused OOM and container died.
Direct cause: The user provided serde would construct an array based on the encoded array size. Given wrong size, the serde constructed a huge array and caused OOM. The exception was hidden by OOM and it was hard to debug.
Root cause: In samza 0.13.1, we added a byte to the head of the payload. The byte represents the message type (event|watermark|EOS). During deserialization, IntermediateMessageSerde will read the first byte, then deserialize the message according to the message byte. For compatibility, if it fails to read the message type, it will try to deserialize again with all bytes (including the …

SAMZA-2587: IntermediateMessageSerde exception handling

---

samza-core/src/main/java/org/apache/samza/table/caching/CachingTable.java
samza-core/src/main/java/org/apache/samza/table/remote/RemoteTable.java

Symptom: String.format("..." + key) would through MissingFormatArgumentException if the key string contains something like "%3A" or "%d". And original exception would be hidden by this new exception.
Cause: We have no control on what the key can be. Should avoid using String.format().
Changes: Simply remove the String.format() should be enough.
Tests: No test since it's a minor change.
API Changes: No API change.
Upgrade Instructions: No backward-compatibility issue. No need to upgrade.
Usage Instructions: User won't use this code directly.

SAMZA-2596: Replace String.format() calls to avoid MissingFormatArgumentException

---

samza-core/src/main/java/org/apache/samza/clustermanager/ContainerAllocator.java
samza-core/src/test/java/org/apache/samza/clustermanager/MockContainerAllocatorWithoutHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithoutHostAffinity.java

Problem: If YARN does not immediately allocate resources for a container and host affinity is disabled for the job, then the container allocator will spam the logs with messages about the request, even if the request is considered expired. This is because the allocator loops over the pending requests to check if they have been allocated, but there is no delay between loop iterations, so it might just keep checking the same pending request over and over as fast as possible. A metric is also incremented in this flow, so that metric is extremely high, which is probably not the intention.
Changes: Avoid infinite loop by breaking the loop if host affinity is disabled
Tests: new unit test
API changes: N/A
Usage instructions: N/A
Upgrade instructions: None

SAMZA-2601: avoid infinite loop on container allocation

---

samza-core/src/main/java/org/apache/samza/container/ContainerHeartbeatMonitor.java
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/java/org/apache/samza/container/TestContainerHeartbeatMonitor.java

Symptom: When new AM takes a long time to to start up, already running container's heartbeat thread silently dies and does not make any heartbeat requests to the new AM. 
Cause: AM url (yarn.am.tracking.url) key-value is removed from Coordinator stream when new AM is starting up - as this config is present in old config (aka coordinator stream) but not in the new AM generated config. This causes the running container to fetch a null when its constantly fetching value for this key and thus throws NPE.
Changes: When AMHA is enabled, do not remove this config
Tests: works with hello-samza. Trying to write a unit test but CoordinatorStreamUtil  is tricky to mock and inject stuff.
Usage Instructions: N/A
Upgrade Instructions: N/A

SAMZA-2611: [AM-HA] heartbeat reestablish causes container's heartbeat thread to die

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java
samza-core/src/main/java/org/apache/samza/coordinator/JobCoordinatorMetadataManager.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestClusterBasedJobCoordinator.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerPlacementActions.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerProcessManager.java
samza-core/src/test/java/org/apache/samza/coordinator/TestJobCoordinatorMetadataManager.java
samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnClusterResourceManager.java

AM performs planning and job model generation for every incarnation. With AM-HA, the new job model or configuration may invalidate the containers from the previous attempt. In order to ensure correctness, we handle this by detecting these changes and restart all the containers in case of any changes to metadata (job model or configuration).
**Changes**:
- Detect changes in metadata by reading older metadata from coordinator stream and signal the CPM
- As part of resource request & orchestration, ignore the containers that are already running from the previous attempt and proceed to release them if metadata changed.
- Releasing the container will signal RM through AMRM client and RM will orchestrate killing the processing container. It is different from the normal …

SAMZA-2610: Handle Metadata changes for AM HA orchestration

---

samza-kafka/src/main/scala/org/apache/samza/checkpoint/kafka/KafkaCheckpointManager.scala
samza-kafka/src/test/scala/org/apache/samza/checkpoint/kafka/TestKafkaCheckpointManager.scala

Symptom: 
Met error when standby container is starting:
SamzaContainer [ERROR] Caught exception/error while initializing container.
java.lang.NullPointerException: null at org.apache.samza.checkpoint.kafka.KafkaCheckpointManager.start(KafkaCheckpointManager.scala:113)
Cause: Standby containers don't really checkpoint or consume input so its possible that there is no checkpointing going on. So the SSP may not be registered by kafkaCheckpointManager after creating kafkaCheckpointManager, which caused the error.
Changes: Creating kafka clients when initializing the kafkaCheckpointManager.
Tests: Unit tests and running local test jobs.
API Changes: N/A
Upgrade Instructions: N/A
Usage Instructions: N/A

SAMZA-2614:Fix NPE at KafkaCheckpointManager.start in standby containers

---

docs/learn/documentation/versioned/operations/monitoring.md
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala

Feature: Add a metric to measure the fraction of physical memory used out of the total memory of the container. During autosizing, the container-count and size can change as traffic changes, so only monitoring the phsical-memory-mb does not provide enough information for alerting. We need a fraction or % metric to allow for easy monitoring and alerting
Changes: Add a metric to measure the fraction of physical memory used out of the total memory of the container.
Tests: unit tests; end-to-end test with samza-hello-samza and inspect the metrics MBean with JMX Reporter

SAMZA-2618: Add per-container metric for memory-utilization

---

samza-kv-inmemory/src/main/java/org/apache/samza/storage/kv/inmemory/InMemoryKeyValueStore.java
samza-kv-inmemory/src/test/java/org/apache/samza/storage/kv/inmemory/TestInMemoryKeyValueStore.java

Symptom: Calling InMemoryKeyValueStore.delete will double count the deletes in metrics.
Cause: InMemoryKeyValueStore.delete is implemented by calling InMemoryKeyValueStore.put with a null value. InMemoryKeyValueStore.delete explicitly increments the delete metric. InMemoryKeyValueStore.put also explicitly increments the delete metric when passed a null value.
Changes: Remove incrementing the delete metric in InMemoryKeyValueStore.delete
Test: unit tests

SAMZA-2563: Fix double counting of InMemoryKeyValueStore deletion

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriter.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobAvroWriter.java

**Bug fix**
**Symptom:**  NPE thrown during SystemProducer.flush if AzureBlobAvroWriter earlier threw an IllegalStateException.
**Cause:** First message passed into AzureBlobAvroWriter is a bad record without schema then the avro objects are not created due to IllegalStateException. However, if the user of the system producer still invokes a flush (either directly or through stop), NPE is thrown as flush of producer invokes flush of the writer which inturn accesses the non-existent avro objects.
**Changes:** check if the avro components are not null before accessing.
Tests: existing tests pass

SAMZA-2556:AzureBlob SystemProducer: Fix NPE thrown during flush. NPE caused by unhandled previous exceptions

---

samza-yarn/src/main/scala/org/apache/samza/job/yarn/YarnJob.scala
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnJob.java

**Symptom**: Samza Sql apps with custom UDFs fail with Samza 1.5 and above.
**Cause**: With Samza 1.5, planning has moved to AM. Planning for Samza Sql apps with custom UDFs requires the UDF lib to be localized and added to the class path of AM container. The latter part is not being done currently resulting in the app to not come up.
**Changes**: Add UDF lib to class path of AM container.
**Tests**: Added unit tests

SAMZA-2628: Include the localized resource lib directory in the classpath of AM container

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java

Issue: StreamAppender sets both partition key and record key = container name for OutgoingMessageEnvelope sent to underlying SystemProducer. This restricts how the classes extending StreamAppender send to SystemProducer.
Change: Mark sendEventToSystemProducer as protected.
Tests: existing tests pass, no functionality change.
API changes: none
Usage, upgrade instructions: none

SAMZA-2627: Make StreamAppender extensible for sending messages to SystemProducer

---

gradle/dependency-versions.gradle
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaConsumerProxy.java
samza-kafka/src/main/java/org/apache/samza/system/kafka/KafkaSystemConsumer.java
samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaSystemConsumerMetrics.scala
samza-kafka/src/test/java/org/apache/samza/system/kafka/MockKafkaProducer.java
samza-kafka/src/test/java/org/apache/samza/system/kafka/TestKafkaSystemConsumerMetrics.java
samza-sql-shell/src/main/java/org/apache/samza/sql/client/impl/SamzaExecutor.java
samza-test/src/test/java/org/apache/samza/test/processor/TestStreamProcessor.java
samza-test/src/test/scala/org/apache/samza/test/harness/AbstractKafkaServerTestHarness.scala
samza-test/src/test/scala/org/apache/samza/test/harness/AbstractZookeeperTestHarness.scala

Issues: The current Kafka version sits at 2.0.1 migrated up to 2.3.1. We get all the bug fixes, enhancements and security upgrades from the Kafka community.
2.4.1 is highest we can go to as it is the last supporting version of Scala 2.11. Done this partial upgrade as going higher TestZkLocalApplication runner becomes flaky and need to investigate why. Want the benefits of 2.3.1 to begin as first step.
Changes: Upgrade Kafka version to 2.3.1. Use TopicPartition as TopicAndPartition will be removed by Kafka 2.4. 
Tests: Run the check-all tests.
API Changes: KafkaSystemConsumer protected method toTopicAndPartition removed as no longer required.

SAMZA-2617: Upgrade Kafka Client to 2.3.1

---

samza-core/src/main/java/org/apache/samza/job/model/JobModelUtil.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/test/java/org/apache/samza/job/model/TestJobModelUtil.java

**Problem**:
Processors update the task locality for all the tasks in the job model with their own locality regardless of whether the tasks belong to their container model or not.
As part of SEP 11, host affinity for standalone was introduced. For this feature, we persist the task locality in zookeeper so that subsequent rebalances take this locality into account when generating job model. During job model consensus, we update the task locality for all the tasks and this results in incorrect locality depending on the order of writes.
**Changes**:
Only update the locality for the tasks that belong to the processor.
**Tests**: Added unit tests

SAMZA-2632: Processors should only write their own task locality to zookeeper

---

samza-core/src/main/java/org/apache/samza/operators/impl/OperatorImpl.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestOperatorImpl.java

**Problem**: Currently, we have a deterministic way of creating the operator DAG by having a `LinkedHashMap` so that during our runtime, we ensure the lifecycle of operators follow a deterministic order.
While we use the same order to traverse the graph and create the DAG, we lose the order within the sub DAG as the registered operators is a `HashSet`. The implication is result of an operator is dispatched non-deterministically to its sub-DAG. i.e
```
Op A --> Op B --> Op C
   | --> Op D --> Op E
```
Output of Op A can be dispatched to Op B or Op D depending how we iterate the `registeredOperators` set of Op A. 
While this is not a guarantee Samza provides to applications, we want to be consistent with graph traversal order, DAG insertion order and DAG traversal order.
**Change**: Use …

SAMZA-2597: Maintain traversal order for registered operators

---

docs/learn/documentation/versioned/operations/monitoring.md
samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala

Feature: Add a metric to track the number of active threads of a container's thread pool. This will be used to calculate the thread pool utilization of a job, which will be used as a signal for the autosizing controller to scale up or down the job thread pool size and number of containers.
Changes: 
- Add a metric to track the number of active threads of a container's thread pool.
- Update the existing container thread pool size metric to reflect the pool size from the thread pool instead of emitting the static `job.container.thread.pool.size`
Tests: unit tests; end-to-end test with samza-hello-samza and inspect the metrics MBean with JMX Reporter

Add a metric to track the number of active threads of a container's thread pool

---

samza-sql/src/main/java/org/apache/samza/sql/planner/Checker.java

**Problem**: With fix for SAMZA-2637, we introduced a bug where when the parsed UDF args are for some reason detected as ANY type, the checker fails.
**Fix**: In addition to checking the annotated udf arg types, also check the parsed arg types to see if it belongs to ANY type and skip checks on such types.
**Tests**: Existing functional tests catch this.

SAMZA-2639: Samza-sql: Fix ANY type validation for the parsed args

---

docs/learn/documentation/versioned/api/high-level-api.md

**Issue:**
The Window Types section in the High Level API documentation has a few mistakes:
1. Missing variable name for a Tumbling window example
2. Incorrect example for Session windows (seems like a copy paste issue from Tumbling window example)
**Changes:**
1. Added missing variable name for the Tumbling window example
2. Incorrect code was removed from the Session window section and a new example was added in its place.
**Tests**
NA. Since this is only a doc fix.

SAMZA-2640: Fixing errors in WindowType examples in High Level API doc

---

samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala

Problem: when thread pool size is 0 and thread pool is null, hostStatisticsMonitor will throw NullPointerException when calculating containerActiveThreads and containerThreadPoolSize metrics. This will subsequently lead to the physical memory metrics to be missing as well, which can trigger alerts, lead to undesirable autosizing, etc.
Solution: add a null check for the thread pool before calculating containerActiveThreads and containerThreadPoolSize metrics

Fix NullPointerException when thread pool size is 0 and thread pool is null for containerActiveThreads and containerThreadPoolSize metrics

---

samza-core/src/main/java/org/apache/samza/job/model/JobModelUtil.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/test/java/org/apache/samza/job/model/TestJobModelUtil.java
samza-core/src/test/java/org/apache/samza/zk/TestZkJobCoordinator.java

**Problem**:
As part of rebalance, we always expire the current work assignment and proceed to signal consensus and start the container with new work assignment. It is inefficient for the processors to do the above when there is no changes in the work assignment between the active job model & the proposed job model.
**Changes**:
- Processors perform onJobModelExpired and onNewJobModel only if there are changes to their work assignment across the active and proposed job model.
- Processors no longer shutdown if they are not part of job model. Refer to the [SAMZA-2638](https://issues.apache.org/jira/browse/SAMZA-2638) for explanations
- Add helper methods in `JobModelUtil` for work assignment comparison
**Tests**:
- Unit tests for job model expiration
- Unit tests for on new job model
- …

SAMZA-2638: Skip container stop/restart for processors that have same work assignment across rebalances

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-kv/src/main/java/org/apache/samza/storage/kv/BaseKeyValueStorageEngineFactory.java
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala

***Feature/Issue:***
BaseKeyValueStorageEngineFactory assumes non-null serdes for k,v of stores using it and applies check/ ContainerStorageManager also applies redundant check to verify the same, however, this might not hold true for some StorageEngine use cases, since some stores may elect to not expose serdes but just use Java Objects as K, V
***Changes:***
- Remove the redundant check from ContainerStorageManager that assumes each store should have non-null serdes
- Add docs to BaseKeyValueStorageEngineFactory on serde assumption
- Add more docs on assumptions for serdes and existence between wrappedStore & rawStore in KeyValueStorageEngine API
***API Changes: None***
 
***Upgrade instructions: None***
 

SAMZA-2643: Cleanup redundant null serde checks in ContainerStorageManager and add docs for Storage Layer

---

docs/learn/documentation/versioned/jobs/samza-configurations.md
samza-core/src/main/java/org/apache/samza/config/ZkConfig.java
samza-core/src/main/java/org/apache/samza/job/model/JobModelUtil.java
samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/main/java/org/apache/samza/zk/ZkKeyBuilder.java
samza-core/src/main/java/org/apache/samza/zk/ZkUtils.java
samza-core/src/test/java/org/apache/samza/job/model/TestJobModelUtil.java
samza-core/src/test/java/org/apache/samza/zk/TestZkJobCoordinator.java
samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java

**Description**: During rolling upgrades, the current debounce timer gets extended every time when there is a quorum change notification. As a result, processors that were upgraded earlier in the deployment window remain unavailable waiting for work assignment. In some scenarios, this cause processors to be unavailable for 20 minutes or so depending on the size of the quorum and the debounce time configuration. Refer to [SAMZA-2633](https://issues.apache.org/jira/browse/SAMZA-2633) for more information.
**Changes**:
- Optimize the leader workflow to skip rebalance if there is no changes to work assignment
- Make processors start with most recent agreed job model on startup
- Leader persists the active job model version in ZK to enable change [2]
- Introduce config for applications to …

SAMZA-2633: Rolling upgrades cause downtime to upgraded processors for the entire deployment window

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java

Issue: StreamAppender is restrictive in explicitly using byte[] for the serialized log event in the OutgoingMessageEnvelope(OME) sent to underlying SystemProducer. This restricts how the classes extending StreamAppender send to SystemProducer as it prevents sending objects (like avro records) to OME.
Change: Introduce a protected interface to hold the encoded log event and a private impl of it for streamappender.
Tests: existing tests pass, no functionality change.
API changes: none
Usage, upgrade instructions: none

SAMZA-2646: Minor refactor of StreamAppender to support sending formats other than byte[] to SystemProducer

---

samza-core/src/main/java/org/apache/samza/coordinator/JobCoordinatorMetadataManager.java
samza-core/src/test/java/org/apache/samza/coordinator/TestJobCoordinatorMetadataManager.java
samza-yarn/src/main/scala/org/apache/samza/job/yarn/SamzaAppMasterMetrics.scala

Issue: some of the AM HA metrics introduced in PR #1455 are counters. these get incremented correctly but go back to 0 and can not be measured a little later in time.
Changes: making these counters as gauges.
1. container-from-previous-attempt
2. application-attempt-count
3. metadata-generation-failed-count
4. metadata-read-failed-count
5. metadata-write-failed-count
API changes: none
Usage instructions: none
upgrade instructions: if AM HA is enabled, these metrics are now gauges instead of counters

SAMZA-2652: Application Master High Availability metric - change counter to gauge

---

samza-core/src/main/java/org/apache/samza/config/ClusterManagerConfig.java
samza-core/src/main/scala/org/apache/samza/coordinator/JobModelManager.scala

Issues: Currently, the port for the job coordinator url (for accessing job model) is always dynamically allocated. In some cases, it is helpful to be able to hardcode a port.
Changes: When `JobModelManager` is setting up the `HttpServer` which serves the coordinator url, read a config to set the port.
Tests:
1. `./bin/integration-tests.sh /tmp/samza-tests yarn-integration-tests --nopassword`
2. Ran a job with `ProcessJobFactory` and verified the job started up.
API changes:
Set the config `cluster-manager.jobcoordinator.url.port` to the port number to use for the coordinator url. This is backwards compatible because the default is to use a value of 0 (to dynamically allocate an unused port), and a value of 0 was the value used before this change was made.
If the specified port is …

SAMZA-2654: Allow coordinator url port to be configurable

---

samza-core/src/main/java/org/apache/samza/metrics/reporter/LoggingMetricsReporter.java
samza-core/src/main/java/org/apache/samza/metrics/reporter/LoggingMetricsReporterConfig.java
samza-core/src/main/java/org/apache/samza/metrics/reporter/LoggingMetricsReporterFactory.java
samza-core/src/test/java/org/apache/samza/metrics/reporter/TestLoggingMetricsReporter.java
samza-core/src/test/java/org/apache/samza/metrics/reporter/TestLoggingMetricsReporterConfig.java

Issues: In environments without an external metrics system, it can sometimes be hard to access any metrics from a Samza job. It can be useful to have a MetricsReporter which logs metrics so that they can be accessed in a simple way with minimal dependencies. This can be used to help verify certain flows are working. An example case for using this is when testing Samza on a bare-bones Kubernetes cluster in minikube.
Changes: Added `LoggingMetricsReporter` which periodically logs metrics to a log file.
Tests: Deployed a Samza job on my local machine and configured it to use the new reporter. Verified that logs showed some metrics.
API changes and usage/upgrade instructions:
Add a new metrics reporter in the config which uses `org.apache.samza.metrics.reporter.LoggingMetricsReporterFactory`. …

SAMZA-2649: Add MetricsReporter which logs metrics to log file

---

docs/learn/documentation/versioned/jobs/configuration-table.html
samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbOptionsHelper.java
samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/descriptors/RocksDbTableDescriptor.java
samza-kv-rocksdb/src/test/java/org/apache/samza/storage/kv/descriptors/TestRocksDbTableDescriptor.java
samza-test/src/test/java/org/apache/samza/processor/TestZkStreamProcessorBase.java

This PR contains changes to expose maxOpenFiles & maxFileOpeningThreads as Samza job parameters.
Changes build & pass tests
```
$ ./gradlew clean build
...
> Task :samza-yarn_2.11:compileTestScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
BUILD SUCCESSFUL in 28m 9s
209 actionable tasks: 208 executed, 1 up-to-date
```

[SAMZA-2655] Expose RocksDB maxOpenFiles setting as Samza parameter

---

samza-core/src/main/java/org/apache/samza/config/StorageConfig.java
samza-core/src/test/java/org/apache/samza/config/TestStorageConfig.java
samza-kafka/src/main/scala/org/apache/samza/config/KafkaConfig.scala
samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaSystemFactory.scala
samza-kafka/src/test/scala/org/apache/samza/system/kafka/TestKafkaSystemFactory.scala
samza-test/src/test/java/org/apache/samza/test/framework/StreamApplicationIntegrationTestHarness.java

Issues: KafkaSystemProducer has enforced compression of `NONE` for topics with the name `changelog`. Clients of Samza using topics named changelog are forced to have no compression. This was due to a bug in a very old Kafka version. This JIRA was raised to remove this in 2014 for `0.9.0.0` Kafka. We are now at `2.3.1`.
Tests: Existing Tests. Checked running locally to ensure that the config remains the same. Integration tests now have `snappy` style compression. 

SAMZA-398: Remove force NONE compression for changelog topic producer

---

samza-kafka/src/main/java/org/apache/samza/checkpoint/kafka/KafkaCheckpointLogKey.java
samza-kafka/src/main/java/org/apache/samza/checkpoint/kafka/KafkaCheckpointLogKeySerde.java
samza-kafka/src/main/scala/org/apache/samza/checkpoint/kafka/KafkaCheckpointManager.scala
samza-kafka/src/test/java/org/apache/samza/checkpoint/kafka/TestKafkaCheckpointLogKeySerde.java
samza-kafka/src/test/scala/org/apache/samza/checkpoint/kafka/TestKafkaCheckpointManager.scala

Removed precondition for key value in KafkaCheckpointLogKeySerde and KafkaCheckpointLogKey to support different checkpoint key types for forwards compatibility.
Added tests validating unknown keys are skipped in KafkaCheckpointManager.

SAMZA-2658: KafkaCheckpointLogKeySerde should support deserializing unknown keys

---

samza-core/src/main/java/org/apache/samza/config/StorageConfig.java
samza-core/src/main/java/org/apache/samza/storage/KafkaChangelogStateBackendFactory.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/test/java/org/apache/samza/config/TestStorageConfig.java

Description:
Newly introduced config `store.restore.factory` falls in the same pattern as StorageEngine config defined by `store.<store_name>.factory`. This fix ignores `store.restore.factory` from `getStorageFactoryClassName` for now. A follow up TODO is added to change this later when restore factory is changed to restore factories.

Fix StorageConfig bug from newly introduced BlobStoreRestore factory config

---

build.gradle
gradle.properties

Symptom: Parallel builds did not work, so we had it disabled, which slowed down build time.
Cause: There was a cryptic `NullPointerException` which sometimes had no additional context and sometimes showed a stack trace for a "progress tracking" flow in Gradle. It looks like this issue was related to the usage of `logging.setLevel` in `build.gradle`. Removing `logging.setLevel` causes the `NullPointerException` to go away. This `logging.setLevel` has been deprecated since Gradle 2 (https://docs.gradle.org/2.14/release-notes.html), and it doesn't look like it makes any difference in logging anymore anyways. I didn't dig further into Gradle to see exactly why `logging.setLevel` was causing the issue, but my guess is that there is some race condition that is triggered when turning on parallel …

SAMZA-1885: Enable parallel task execution for build

---

build.gradle
docs/learn/documentation/versioned/jobs/samza-configurations.md
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobClientBuilder.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/AzureBlobConfig.java
samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobSystemProducer.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/producer/TestAzureBlobSystemProducer.java

Feature: Providing an alternate form of authenticating with Azure Storage to set up the connection. Existing form of authentication is via account name and account key for the Azure Storage. Note that this impacts only the authentication and not the actual blob creation which happens later in the lifecycle of the system producer.
Changes: New way of authenticating via TokenCredential (specifically ClientSecretCredential) provided - it uses other required configs like client.id, client.secret, tenant.id, proxy for authenticating.
Tests: existing tests pass. As this is an authentication with Azure, can not tested in unit tests. Full end-to-end functional testing performed.
API changes: new configs introduced.
- systems.**_system-name_**.azureblob.useTokenCredentialAuthentication default = …

SAMZA-2660: Add authentication via TokenCredential for AzureBlobSystemProducer

---

samza-core/src/main/java/org/apache/samza/context/InternalTaskContext.java
samza-core/src/main/java/org/apache/samza/context/TaskContextImpl.java
samza-core/src/main/java/org/apache/samza/operators/impl/OperatorImplGraph.java
samza-core/src/main/java/org/apache/samza/system/inmemory/InMemoryManager.java
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/java/org/apache/samza/context/TestTaskContextImpl.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestWindowOperator.java
samza-core/src/test/java/org/apache/samza/system/inmemory/TestInMemorySystem.java
samza-test/src/main/java/org/apache/samza/test/framework/TestRunner.java
samza-test/src/test/java/org/apache/samza/test/table/TestLocalTableEndToEnd.java
samza-test/src/test/java/org/apache/samza/test/table/TestLocalTableWithSideInputsEndToEnd.java
samza-test/src/test/java/org/apache/samza/test/table/TestTableData.java

Symptom:
1. End-of-stream and watermarks are not properly propagated through Samza when side inputs are used.
2. This prevents many tests from using the `TestRunner` framework, since the `TestRunner` framework relies on having tasks shut themselves down based on end-of-stream messages. Being able to use `TestRunner` is helpful because it significantly decreases test times.
Cause:
OperatorImplGraph builds EndOfStreamStates and WatermarkStates objects with all of the input SSPs from the job model. That includes side-input SSPs. However, high-level operator tasks aren't given messages from side-input SSPs, so high-level operators should not need to include handling for end-of-stream and watermarks. The result of this issue is that end-of-stream and watermark handling tries to include …

SAMZA-2303: Exclude side inputs when handling end-of-stream and watermarks for high-level

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobOutputStream.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobOutputStream.java

Symptom: interrupted thread stays stuck for a long time.
Cause: retry several times for all exceptions during block upload. 
Changes: for interrupted exception, stop retry and throw exception that will be bubbled up.
Tests: added unit test
Usage/upgrade instructions: N/A
Backwards compatible:  yes

Samza-2665: AzureBlob SystemProducer: stop block upload retrying when InterruptedException is thrown

---

build.gradle

Fix for recent build issues on Jenkins, it seems that azure-storage-blob 12.0.1 is no longer in mvn central
```
* What went wrong:
Execution failed for task ':samza-azure_2.11:compileJava'.
> Could not resolve all files for configuration ':samza-azure_2.11:compileClasspath'.
> Could not find com.azure:azure-storage-blob:12.0.1.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/com/azure/azure-storage-blob/12.0.1/azure-storage-blob-12.0.1.pom
- https://repo.maven.apache.org/maven2/com/azure/azure-storage-blob/12.0.1/azure-storage-blob-12.0.1.jar
- file:/home/travis/.m2/repository/com/azure/azure-storage-blob/12.0.1/azure-storage-blob-12.0.1.pom
- file:/home/travis/.m2/repository/com/azure/azure-storage-blob/12.0.1/azure-storage-blob-12.0.1.jar
Required by:
project …
```

SAMZA-2675: Fix Jenkins build for Azure-blob-store version not found

---

gradle/dependency-versions-scala-2.11.gradle
gradle/dependency-versions-scala-2.12.gradle
samza-yarn/src/main/resources/scalate/WEB-INF/views/index.scaml

Bumped to the latest Scalatra version so to we have to latest versions; Scalatra 2.5.0 depends on log4j:1.2.14 which has security vulnerability (More details in ticket).
Although we pin log4j:1.2.17, this still prevent our internal automated dependency validation to allow samza-yarn to pass the security check.
Testing: Passing existing tests after scalatra dashboard template is fixed to work with new version.
@xinyuiscool @prateekm @kw2542

SAMZA-2683: Bump Scalatra Version

---

samza-core/src/main/java/org/apache/samza/config/StreamConfig.java

There is an unused parameter on this format string. Removing it should
preserve the existing behavior.

SAMZA-2676: Pass parameter into subset, not format  (StreamConfig.getSerdeStreams)

---

samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java
samza-core/src/test/java/org/apache/samza/zk/TestZkJobCoordinator.java

**Problem**:
As part of  SAMZA-2638, we introduced skipping container restart and stops on no changes to work assignment for processors across rebalances. However, we only update the active job model with the proposed job model on starting the container as part of `onNewJobModel`. This leads to a scenario where the processor is stopped but the future rebalances assume the container is still running. More information on scenario below.
**Description**: 
Imagine the quorum is in steady state with job model version v1. A new rebalance occurs and the leader generates v2. Processor P1 has changes in work assignment and as a result stops the container as part of job model expiration. However, in the event of the rebalance being unsuccessful (barrier times out), a new rebalance occurs which …

SAMZA-2663: Handle job model expiration and new job model flows for multiple incomplete rebalances

---

.github/workflows/ci.yml

This introduces CI using Github Actions. Note that this will run concurrently with travis-ci on pull requests -- removing travis-ci support (or not) should be a separate change.
It appears to be free for public projects. Details on pricing may be found at:
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
Example runs of this change may be found at:
https://github.com/bringhurst/samza/actions (note that some of the failures shown are unrelated to this change)

SAMZA-2678: Configure Github Actions for CI

---

build.gradle
gradle/stacktrace.gradle

CI build failures are more useful when they show stack traces by default.

SAMZA-2694: Always show stack traces on gradle failures

---

.github/workflows/ci.yml

The Github Actions CI timeout is currently set to 6 hours by default.
However, a typical successful run will take around 30 minutes.
This change lowers the timeout from 6 hours to 60 minutes.

SAMZA-2696: Set CI timeout to 60 minutes

---

build.gradle

Github actions uses the Adopt JDK. The Adopt JDK appears to use a bit
more memory than Hotspot. This change increases the Xmx for the build by
1 GB.

SAMZA-2697: Increase build time max heap

---

samza-core/src/main/java/org/apache/samza/container/host/PosixCommandBasedStatisticsGetter.java
samza-core/src/test/java/org/apache/samza/container/host/TestStatisticsMonitorImpl.java

Symptom: CI is broken by https://github.com/apache/samza/pull/1530
Changes: Fix by changing fetching children process RSS memory in 1 process instead of multiple processes. Otherwise, when there are a lot of children processes, it will take too long to spin up all the processes to fetch RSS memory for each child process
Test:Tested with samza-hello-samza

Fix container physical memory monitoring to fetch all children process RSS memory with 1 process

---

samza-api/src/main/java/org/apache/samza/storage/StorageEngine.java
samza-api/src/main/java/org/apache/samza/storage/kv/KeyValueStore.java
samza-core/src/test/java/org/apache/samza/storage/MockStorageEngine.java
samza-kv/src/main/scala/org/apache/samza/storage/kv/KeyValueStorageEngine.scala

Update the StorageEngine and KeyValueStore apis to only use Context parameter for custom store types
@Sanil15 @prateekm

SAMZA-2674: Change StorageEngine and KeyValueStore init call parameters

---

build.gradle

Issues: CI runs have been flaky lately, and I have seen OOM errors more frequently. This issue might be related to https://github.com/apache/samza/pull/1538 (which bumped memory for https://github.com/apache/samza/pull/1525) or https://github.com/apache/samza/pull/1545.
Changes: Increase the heap memory for `samza-core` tests

[Tests] Updating memory for test task for samza-core and samza-test

---

samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java
samza-core/src/main/java/org/apache/samza/processor/StreamProcessor.java
samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/main/java/org/apache/samza/util/DiagnosticsUtil.java
samza-core/src/main/java/org/apache/samza/util/MetricsReporterLoader.java
samza-core/src/test/java/org/apache/samza/util/TestDiagnosticsUtil.java

Issues: Specific checks for the `diagnosticsreporter` metrics reporter were making the code for setting up diagnostics and the `diagnosticsreporter` metrics reporter a bit harder to work with. For the new `StaticResourceJobCoordinator`, it made object wiring harder for diagnostics-related components. https://github.com/apache/samza/pull/1021 initially had a reason to have special logic for creating the `diagnosticsreporter` metrics reporter, but https://github.com/apache/samza/pull/1369 made that special logic unnecessary.
Changes:
1. Changed `DiagnosticsUtil.buildDiagnosticsManager` to only return a `DiagnosticsManager` instead of `Pair<DiagnosticsManager, MetricsSnapshotReporter>`.
2. `MetricsReporterLoader.getMetricsReporters` no longer excludes the `diagnosticsreporter` metrics …

SAMZA-2706: Clean up specific handling of diagnostics-specific metrics reporter

---

samza-test/src/test/java/org/apache/samza/test/operator/TestAsyncFlatMap.java

Issues: `TestAsyncFlatMap.testProcessingFutureCompletesAfterTaskTimeout` fails transiently when running the CI build due to the `rootCause` exception type not being the expected `SamzaException`. It's unclear what the actual type of `rootCause` is when the test fails.
Changes: Add extra context message to figure out why this is failing when it does show up again.
Tests: Ran CI build multiple times, but I couldn't reproduce the failure. We can commit this change so that we have the information if it does fail in the future.
API changes: N/A

[Tests] add more context on flaky testProcessingFutureCompletesAfterTaskTimeout test

---

build.gradle
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithoutHostAffinity.java
samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerProcessManager.java

Issues:
1. `TestContainerAllocatorWithHostAffinity.testExpiredRequestsAreCancelled` fails transiently due to seeing a value of 4 for `cancelledRequests.size()` instead of 3.
2. `samza-core` tests take a lot of heap to run (3GB), but it seems like they shouldn't need that much.
Changes:
1. Change the `cluster-manager.container.request.timeout.ms` to be 500ms instead of 3ms in `TestContainerAllocatorWithHostAffinity` in order to prevent the test from cancelling requests too quickly and causing an extra cancellation to happen before the validation is done.
2. Stop the `ContainerAllocator` and `ContainerPlacementManager` objects in tests so that their corresponding threads can exit. Before, I believe the threads just kept running, and that may have eaten up memory.
3. Reduce the heap needed …

[Tests] Fix flaky tests and memory leak related to ContainerAllocator tests

---

build.gradle
gradle/dependency-versions.gradle
samza-test/src/main/config/join/README
samza-test/src/main/python/configs/tests.json
samza-test/src/main/python/stream_processor.py
samza-yarn/src/test/java/org/apache/samza/job/yarn/util/MockNMClient.java
samza-yarn/src/test/scala/org/apache/samza/job/yarn/TestSamzaYarnAppMasterLifecycle.scala

Issues: 
The version of YARN used by the Samza project is outdated and needs to be updated.
https://issues.apache.org/jira/browse/SAMZA-2708
Changes: 
1. Update yarn from 2.7.1 to 2.10.1. Other minor fixes to get this to work.
2. Use https rather than http to avoid a build hang when the build script references "repo.typesafe.com/typesafe/releases".
3. Update references of "samza-test_2.11-1.6.0-SNAPSHOT.tgz" to "samza-test_2.11-1.7.0-SNAPSHOT.tgz" to be consistent with the file actually produced by the integration tests.
Tests: 
'build test' and run yarn integration tests

SAMZA-2708: Update yarn from 2.7.1 to 2.10.1

---

samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java

Issue: `TestContainerAllocatorWithHostAffinity.testExpiredRequestAllocationOnAnyHost` transiently fails. The test comments say it should check for "at least 2" cancelled resource requests and "at least 2" `ANY_HOST` requests, but the actual logic checks for "greater than 2". Usually, the test passes, because the 2 preferred host requests get cancelled, and then there is time for the follow up `ANY_HOST` request to also get cancelled. Parts of the test seem to indicate that it is not the intention to check on the follow up `ANY_HOST` requests, but the validation logic relied on the follow up `ANY_HOST` expirations. In https://github.com/apache/samza/pull/1556, the test was updated to wait 1000ms with an expiration timeout of 500ms, so this barely left enough time for the follow-up …

[Tests] fix flaky TestContainerAllocatorWithHostAffinity.testExpiredRequestAllocationOnAnyHost

---

samza-test/src/test/java/org/apache/samza/test/operator/TestAsyncFlatMap.java

Issues: `TestAsyncFlatMap.testProcessingFutureCompletesAfterTaskTimeout` fails transiently. It looks like the task timeout gets triggered (which would set the error to the expected error for the test), but occasionally, before the `RunLoop` exits, the actual processing task completes, and then the final error is overridden to be `Callback complete was invoked after completion...` (which is not the expected error). The difference between the timeout and the actual processing time is 100ms, so if the `RunLoop` doesn't exit within 100ms, then this test will fail.
Changes: Increase the delay time in the test so that the `RunLoop` has more time to exit before the actual processing task completes.
Tests: `TestAsyncFlatMap.testProcessingFutureCompletesAfterTaskTimeout` passes
API changes: N/A

[Tests] Add longer delay time to mitigate flaky test in TestAsyncFlatMap

---

samza-core/src/main/java/org/apache/samza/container/host/PosixCommandBasedStatisticsGetter.java

Problem: User log is flooded by logging in `PosixCommandBasedStatisticsGetter`
Changes: change the log from info to debug

[Minor] Change log level to debug in PosixCommandBasedStatisticsGetter

---

samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java

Issues: 
TestZkLocalApplicationRunner.shouldStopNewProcessorsJoiningGroupWhenNumContainersIsGreaterThanNumTasks asserts
A) JobModel generated before and after the addition of appRunner2 should be equal.
B) Second stream application(appRunner2) should not join the group and process any message.
Assertion A is good, but the test can not guarantee Assertion B.
The reason is that the test kill appRunner1 then kill appRunner2, but after appRunner1 got killed and before appRunner2 gets killed, ZkJobCoordinator could generate a new JobModel with appRunner 2
That leads to appRunner2 status change from New->Running->SuccessfulFinish
instead of New->UnsuccessfulFinish, which result in the test failure
Changes: 
kill appRunner2 and do assertion before kill appRunner1
Tests: ./gradlew build
API …

SAMZA-2711: Fix flaky TestZkLocalApplicationRunner

---

samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/test/java/org/apache/samza/config/TestJobConfig.java

Issues: `ContainerHeartbeatMonitor` is used when the `EXECUTION_ENV_CONTAINER_ID` environment variable is set. However, the current implementation of `ContainerHeartbeatMonitor` is coupled with YARN while `EXECUTION_ENV_CONTAINER_ID` is not. For Kubernetes, we don't need `ContainerHeartbeatMonitor` since we don't need to deal with orphaned containers, but we would like to still fill in `EXECUTION_ENV_CONTAINER_ID`. Therefore, we need another way to disable the `ContainerHeartbeatMonitor`.
Changes: Add a config flag (`job.container.heartbeat.monitor.enabled`) for enabling `ContainerHeartbeatMonitor`.
Tests: Deployed application in minikube for following situations:
1. Monitor enabled, `EXECUTION_ENV_CONTAINER_ID` specified -> monitor runs and is expected to kill the container since there …

SAMZA-2713: Add flag to disable container heartbeat monitor

---

gradle/dependency-versions.gradle

See https://blog.cloudflare.com/cve-2021-44228-log4j-rce-0-day-mitigation/

SAMZA-2714: Bump log4j2 to mitigate CVE-2021-44228

---

gradle/dependency-versions.gradle

The log4j2 2.15.0 is still vulnerable, we will need to bump up to 2.16.0: https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0

SAMZA-2715: Bump up log4j2 version to fix CVE-2021-44228

---

samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-kafka/src/main/scala/org/apache/samza/checkpoint/kafka/KafkaCheckpointManager.scala
samza-test/src/test/java/org/apache/samza/checkpoint/CheckpointVersionIntegrationTest.java

Symptom: Checkpoint v2 preference could cause stale checkpoints to get picked up when newer v1 checkpoints are available
Cause: Kafka checkpoint manager selects the checkpoints based on the `task.checkpoint.read.versions` priority list. This does not account for the fact that the prioritized checkpoint may be stale and a new checkpoint lower on the priority list is present in the checkpoint topic. This will cause the job to silently use the stale checkpoint and cause more reprocessing than the most recent commit. 
An example case where this could happen is when the users upgrades to a v2 checkpoint commits a v2 checkpoint and rollbacks to a previous version using only v1 checkpoint version then upgrading to the newest version again, using that stale v2 checkpoint from the initial upgrade. …

Fix rollback stale checkpoints

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/util/BlobStoreUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/TestBlobStoreBackupManager.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestBlobStoreUtil.java
samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbOptionsHelper.java

Symptoms: Containers some times taking a longer than usual to restore checkpoint. 
Cause: RocksDB stalls write operations in order to perform compaction if there are large number of level 0 SST files. The default thread count of RocksDB compaction thread is 1. We saw that some jobs were blocked on container restore with RocksDb taking long time to complete compaction. Similar issue and some background [here](https://github.com/facebook/rocksdb/issues/3717).
Fix: We set the `rocksdb.compaction.max.background.compactions` config for Samza jobs to 4. 
Additional changes: Added a warning instead of an exception on first backup when Checkpoint v2 is enabled for a job.

Set default RocksDB compaction threads to 4

---

samza-core/src/main/java/org/apache/samza/context/TaskContextImpl.java
samza-core/src/main/java/org/apache/samza/table/ReadWriteTableDelegate.java

**Issue:**
TaskContext.getTable currently upcasts ReadWriteUpdateTable to ReadWriteTable. This is incorrect as update(), updateAsync() calls to the returned table (ReadWriteUpdateTable) will work when it is not intended to work.
**Changes:**
Create a delegate class implementing ReadWriteTable which is composed of ReadWriteUpdateTable. All method calls are delegated to ReadWriteUpdateTable's methods except for update methods.
**Tests**
./gradlew build

SAMZA-2718: TaskContext.getTable should not upcast ReadWriteUpdateTable to ReadWriteTable

---

gradle/dependency-versions.gradle
samza-test/src/test/java/org/apache/samza/checkpoint/CheckpointVersionIntegrationTest.java
samza-test/src/test/java/org/apache/samza/storage/kv/TransactionalStateIntegrationTest.java
samza-test/src/test/java/org/apache/samza/storage/kv/TransactionalStateMultiStoreIntegrationTest.java
samza-test/src/test/java/org/apache/samza/test/framework/StreamApplicationIntegrationTestHarness.java
samza-test/src/test/java/org/apache/samza/test/framework/TestStreamApplicationIntegrationTestHarness.java
samza-test/src/test/java/org/apache/samza/test/operator/TestRepartitionJoinWindowApp.java
samza-test/src/test/java/org/apache/samza/test/processor/TestZkLocalApplicationRunner.java

1. Upgrade Kafka version in dependency-versions.gradle
2. 
Issue:
StreamApplicationIntegrationTestHarness is flaky because in the test 
there is a Kafka consumer subscribes to input topic and consumes from it
then, the same consumer subscribes to the changelog topic. 
During this change, Kafka needs to revoke the previous assignments and do rebalancing which causes the changelog topic is not assigned to any member. 
Change:  create a separate consumer of a different consumer group to consume changelog topic, so it can avoid Kafka consumer group rebalance
3.
Issue:
Apache Kafka 2.4 introduces sticky partition strategy:https://www.confluent.io/blog/apache-kafka-producer-improvements-sticky-partitioner/
which causes TestZkLocalApplicationRunner tests flaky.
The reason is that in some of the …

Upgrade to Kafka 2.4 and fix flaky tests

---

samza-api/src/main/java/org/apache/samza/system/IncomingMessageEnvelope.java
samza-api/src/main/java/org/apache/samza/system/SystemStreamPartition.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/serializers/model/SamzaObjectMapper.java
samza-core/src/test/java/org/apache/samza/config/TestJobConfig.java
samza-core/src/test/java/org/apache/samza/serializers/model/TestSamzaObjectMapper.java

**Feature:** Elasticity (SAMZA-2687) for a Samza job allows job to have more tasks than the number of input SystemStreamPartition(SSP). Thus, a job can scale up beyond its input partition count without needing the repartition the input stream.
- This is achieved by having elastic tasks which is the same as a task for all practical purposes. But an elastic task consumes only a subset of the messages of an SSP. 
- With an elasticity factor F (integer), the number of elastic tasks will be F times N with N = original task count. 
- The F elastic tasks per original task all consume subsets of same SSP as the original task. There will be F subsets (aka key bucket) per SSP and a message falls into an SSP bucket 'i' if its message.key.hash()%F == i. 
**Changes:**
1. introduce the config for …

SAMZA-2688 [Elasticity] introduce elasticity factor config and key bucket within SSP

---

samza-core/src/main/java/org/apache/samza/serializers/model/SamzaObjectMapper.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreBackupManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/index/serde/SnapshotIndexSerde.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/util/BlobStoreUtil.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/TestBlobStoreBackupManager.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestBlobStoreUtil.java

Problems addressed:
1. During init, SnapshotIndex blobs of stores that were previously configured and has blob ID in the checkpoint topic are being downloaded and deserialized. This may create problems if the blob is missing in the blob store or if the blob is incorrectly serialized. This causes the container to fail during init and the subsequently the job to fail. 
2. SnapshotIndexSerde was incorrectly serializing the SnapshotIndex blob possibly due to missing Jackson-datatype-JDK8 module not loading during the run time. 
Fix:
1. Backup/Restore managers already have a set of stores currently configured passed to them through ContainerStorageManager (CSM). We pass this set to BlobStoreUtil and download the blobs only relevant to this current set thus avoiding the problem of missing or …

Fix - filter only configured stores in backup/restore init 

---

samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/test/java/org/apache/samza/runtime/TestContainerLaunchUtil.java

**Problem**:
ContainerLaunchUtil during its launch sequence swallows exception and proceeds to shutdown with 0 status code. This causes AM to not restart the container.
With the run method, as part of launch sequence we have various initialization steps before kicking off the container. In case of exceptions during this step, the run method catches all erros but only logs them and proceeds to shutdown as usual. 
Due to normal exit, AM treats the container completed successfully and hence doesn't restart causing the failed container to remain failed.
**Changes**:
- Exit with status code 1 in case of exception during launch
- Fix the error log to include both actual failure and container exception
**Tests**:
- Added unit test to validate if the system is exiting with the …

SAMZA-2721: Container should exit with non-zero status code in case of errors during launch

---

bin/check-all.sh
gradle/dependency-versions-scala-2.12.gradle
samza-test/src/main/python/tests/standalone_failure_tests.py

Fix for observed failures in release testing
1. Symptom: 
```
> Task :samza-yarn_2.11:compileTestScala FAILED
Pruning sources from previous analysis, due to incompatible CompileSetup.
/Users/dchen1/code/samza212/samza/samza-yarn/src/test/scala/org/apache/samza/job/yarn/TestSamzaYarnAppMasterLifecycle.scala:57: type ResourceTypeInfo is not a member of package org.apache.hadoop.yarn.api.records
override def setResourceTypes(types: java.util.List[org.apache.hadoop.yarn.api.records.ResourceTypeInfo]): Unit = ()
```
Cause: we have updated (https://github.com/apache/samza/pull/1557) the yarn version but did not change it in release tests
Fix: Update ./bin/check-all.sh yarn verison
2. Fix scalate and scala 2.12 version compatibility
We need to update the scala version from 2.12.1 -> 2.12.11 for …

SAMZA-2723: Fix yarn version and scala version for scalate

---

samza-core/src/main/scala/org/apache/samza/util/FileUtil.scala
samza-core/src/test/scala/org/apache/samza/util/TestFileUtil.scala

**Symptom**: We see the following when writing a large checkpoint to disk
```
Caused by: java.io.UTFDataFormatException
at java.io.ObjectOutputStream$BlockDataOutputStream.writeUTF(ObjectOutputStream.java:2164) ~[?:1.8.0_282]
at java.io.ObjectOutputStream$BlockDataOutputStream.writeUTF(ObjectOutputStream.java:2007) ~[?:1.8.0_282]
at java.io.ObjectOutputStream.writeUTF(ObjectOutputStream.java:869) ~[?:1.8.0_282]
at org.apache.samza.util.FileUtil.writeWithChecksum(FileUtil.scala:45) ~[samza-core_2.11-317.1071.9.4.jar:317.1071.9.4]
at org.apache.samza.storage.StorageManagerUtil.writeCheckpointV2File(StorageManagerUtil.java:245)
```
**Cause**: FileUtil uses `ObjectOutputStream$BlockDataOutputStream.writeUTF` which limits the size to 0xFFFF and throws `UTFDataFormatException` if the length is …

SAMZA-2727: Fix UTFDataFormatException for FileUtil

---

samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java
samza-core/src/test/scala/org/apache/samza/system/TestSystemConsumers.scala

Symptom: Certain container level metrics have incorrect values when elasticity is enabled. Metrics affected: chose-object, process-calls, messages-chosen.
Cause: With elasticity enabled, a container may process only some of the messages of an SSP and not all of the messages in the SSP. the messages processed belong to the key buckets within the container's model. However, pre-elasticity container level metrics counted the messages per ssp. 
Changes: Adapt SystemConsumers and RunLoop to account for key buckets. SystemConsumers keeps track of all the SSP(with key buckets) registered with it by the RunLoop and increments only the metrics only if the message belongs to this SSP set. new metric skipped-envelopes added for those messages in an ssp but not processed by runloop
Tests: added unit …

SAMZA-2719: [Elasticity] fix container level metrics when elasticity is enabled

---

gradle/wrapper/gradle-wrapper.properties
samza-api/src/main/java/org/apache/samza/task/TaskExecutorFactory.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/task/DefaultTaskExecutorFactory.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/test/java/org/apache/samza/task/TestDefaultTaskExecutorFactory.java

Feature: [SAMZA-2720](https://issues.apache.org/jira/browse/SAMZA-2720)
Changes: Allow custom task executor to be injected and used.
 Tests: Added unit testing and verified working on local deployment.
API Changes: This backwards compatible change introduces a way to inject custom task executor. The default behavior is unchanged - use plain java executor.
Usage:
1. Implement TaskExecutorFactory interface.
2. Configure config key “job.container.task.executor.type” with implementation class name (eg "org.apache.samza.task.DefaultTaskExecutorFactory")

SAMZA-2720: Allow custom task executor to be injected and used.

---

samza-api/src/main/java/org/apache/samza/system/IncomingMessageEnvelope.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/test/java/org/apache/samza/config/TestJobConfig.java
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java

**Symptom:** When elasticity is enabled, for certain kind of input streams, some of the containers are not processing anything when container count = elastic task count = elasticity factor X original task count.
**Cause:** The input stream where this was observed had its message keys such that key.hashcode()%elasticiyFactor was always even for some partitions and odd for other partitions. lead to some of the elastic tasks no getting any messages. This is not a bug in the elasticity code but rather a skew in the input stream’s key distribution.
**Changes:** 
1. to distribute the messages to elastic tasks more evenly, the key bucket computation aka key.hashCode()%elasticityFactor is modified to (key.hashCode%31)%elasicityFactor and max value for elasticity factor is limited to 16 to be able …

SAMZA-2728: [Elasticity] improve distribution of messages across elastic tasks

---

samza-core/src/main/java/org/apache/samza/util/FutureUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestBlobStoreUtil.java

Symptoms: On receiving a retriable failure for blob operations (like 503 - service temporarily not available), the async operations were only retrying 3 times (including the first failed attempts and 2 retries). This is not expected behavior. The async blob operations are expected to be retried up to 10 minutes (with backoff).
Cause: On receiving a retriable failure from blob store, the operations are retried with a backoff, as defined by RetryPolicy in executeAsyncWithRetries method [here](https://github.com/apache/samza/blob/master/samza-core/src/main/java/org/apache/samza/util/FutureUtil.java#L145). The intention was to limit the retry by max duration (10 minutes). However, the default count of retries in [RetryPolicy is 3,](https://frontbackend.com/java/failsafe-retry-policy) unless …

Change retry counts limit of 3 to unlimited for async blob store operations

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreBackupManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/index/DirIndex.java
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala

- Update some debug/trace logs to info logs to better track delete operations. 
- Check to verify that a file is not added in files deletes as well as files added/deleted of `DirIndex`

Add info logs for delete operations

---

samza-core/src/main/java/org/apache/samza/config/JobCoordinatorConfig.java
samza-core/src/test/java/org/apache/samza/config/TestJobCoordinatorConfig.java

Issues: The first PR for SAMZA-2685 (PR #1529) only used `ClusterBasedJobCoordinator` when `job.coordinator.factory` was not specified. Some apps may prefer to use the empty string instead to indicate using the default `ClusterBasedJobCoordinator`.
Changes: `getOptionalJobCoordinatorFactoryClassName` now returns "empty" when the value of `job.coordinator.factory` is the empty string. `getOptionalJobCoordinatorFactoryClassName` is used in `JobCoordinatorLaunchUtil`; the `ClusterBasedJobCoordinator` flow is used when `getOptionalJobCoordinatorFactoryClassName` returns "empty".
Tests: Added unit test
API/usage changes: Using the empty string as the value for `job.coordinator.factory` when running in a cluster-based system (e.g. YARN) results in using `ClusterBasedJobCoordinator` instead of …

SAMZA-2685: fall back to ClusterBasedJobCoordinator when job.coordinator.factory is the empty string for cluster-based deployments

---

docs/learn/documentation/versioned/container/metrics-table.html
samza-core/src/main/scala/org/apache/samza/metrics/JvmMetrics.scala

Issues: Currently, "process-cpu-usage" is only reported as a percentage of the available CPU on the whole host. In some cases, it is useful to know the actual number of processors being used. For example, external systems (like an autosizer) or application owners can directly access the current processor count instead of needing to also query the total number of processors on a host in order to calculate the processor count.
Changes: Add a metric `process-cpu-usage-processors` which reports the number of processors being used.
Tests: Ran a container in minikube and used `LoggingMetricsReporter` to print out the values of `process-cpu-usage` and `process-cpu-usage-processors`. Verified that these values were consistent with the total processor count from running `lscpu` inside the …

SAMZA-2730: Add process CPU usage metric using units of processor count instead of percentage

---

samza-api/src/main/java/org/apache/samza/checkpoint/CheckpointManager.java
samza-kafka/src/main/scala/org/apache/samza/checkpoint/kafka/KafkaCheckpointManager.scala
samza-kafka/src/test/java/org/apache/samza/checkpoint/kafka/TestKafkaCheckpointManager.java

**Improvement:** add functionality in CheckpointManager to return the last recorded checkpoint for all tasks present in the checkpoint stream.
Elasticity (SAMZA-2687) is a new feature which enables scaling up task count beyond the input partition count. When the task count changes, it is necessary to compute the starting offsets of the new tasks from the old tasks. Due to task name change (as count has changed), the earlier mechanism of fetching checkpoint by task name does not work. Hence computing the starting offsets for a new task requires looking at all the previous deploy's tasks' checkpoints. This PR exposes that functionality of fetching all checkpoints within the checkpoint stream and it will be leveraged in the later PRs for elasticity (PR #1598).
**Changes:**
1. Update …

SAMZA-2731: Add readAllCheckpoints to CheckpointManager and implement for KafkaCheckpointManager

---

samza-core/src/main/java/org/apache/samza/runtime/RemoteApplicationRunner.java
samza-core/src/main/scala/org/apache/samza/job/local/ProcessJobFactory.scala
samza-core/src/main/scala/org/apache/samza/job/local/ThreadJobFactory.scala
samza-core/src/test/java/org/apache/samza/runtime/TestRemoteApplicationRunner.java
samza-shell/src/main/bash/run-framework-class.sh

Changes: 
- Add checks in RemoteApplicationRunner to proceed with the legacy planning step if we are using ProcessJob or ThreadJob
- Remove the planning from the processJob and ThreadJob
Tests: Tested with local job, Added unit test to verify behavior
Upgrade instructions: None
Usage instructions: None
Backwards compatible: yes. Does not change any existing interface methods

SAMZA-2737: Change RemoteAppRunner to plan for local deployments

---

samza-rest/src/main/java/org/apache/samza/rest/SamzaRestService.java

Crashes in monitor threads potentially cause resource leaks. Let's crash by default on uncaught exceptions.

SAMZA-2729: samza-rest: Crash on uncaught exceptions in monitor threads

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/diff/DirDiff.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/index/DirIndex.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/index/TestDirIndex.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestBlobStoreUtil.java

Issue: Current validation for DirIndex checks if the same file _name_ is present in both filesAdded and filesRemoved. For mutable files like CURRENT this is valid since the metadata and blob ids are different.
Changes: Fixed the check for files to compare FileIndex instead of file name, which accounts for the blobs and metadata associated with the file too. Also added a similar check for all blobs added and removed in the DirIndex too. Made both checks recursive to account for subdirs.
API/usage changes: None
Tests: Added a couple of unit tests.

Fixed check for files both present and removed in DirIndex. Added a check for blobs too.

---

samza-core/src/main/java/org/apache/samza/serializers/model/SamzaObjectMapper.java
samza-core/src/test/java/org/apache/samza/serializers/model/TestSamzaObjectMapper.java

**Improvement**: Improve the deserialization logic used for SSP key. Existing logic expects two ‘.’ & 3 [fields/parts in](http://fields.in/) the serialized format of SSP. The logic looks for index of ‘.’ and uses substring to fetch the fields of SSP. this prevents the addition of a 4th field (KeyBucket introduced in https://github.com/apache/samza/pull/1576) to the SSP serialized format in a backwards compatible manner.
**Changes**: New logic for deser SSP uses String.split(‘.’) which makes it feasible to later add the Keybucket into the SSP serde.
**Tests**: Added one test in TestSamzaObjectMapper for serde of SSP as key
**API changes**: None.
**Upgrade instructions**: None
**Usage instructions**: None
**Backwards compatible**: yes. Does not change any existing serde format of the SSP as …

SAMZA-2739: Improve SystemStreamPartition key deserializer to not be rigid about ssp having only 3 fields

---

samza-core/src/main/scala/org/apache/samza/checkpoint/OffsetManager.scala
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/scala/org/apache/samza/checkpoint/TestOffsetManager.scala

Feature: Elasticity (SAMZA-2687) for a Samza job allows job to have more tasks than the number of input SystemStreamPartition(SSP). Thus, a job can scale up beyond its input partition count without needing the repartition the input stream.
This current PR is to update the last processed offsets maintained by the OffsetManager during processing stage of the container correctly when elasticity is enabled.
Changes:
1. Modify OffsetManager.udpate to correctly identify the ssp even with keyBucket info is not present in the given parameter ssp
2. Modify SystemConsumers to provide the ssp,offset to Chooser after all the registrations are done. This is because, chooser is given an ssp without keyBucket but a container could be processing multiple keyBuckets within the same ssp. So after …

SAMZA-2734: [Elasticity] Update last processed offset after an envelope is finished processing when elasticity is enabled

---

samza-core/src/main/scala/org/apache/samza/checkpoint/OffsetManager.scala
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/scala/org/apache/samza/checkpoint/TestOffsetManager.scala

**Feature:** Elasticity (SAMZA-2687) for a Samza job allows job to have more tasks than the number of input SystemStreamPartition(SSP). Thus, a job can scale up beyond its input partition count without needing the repartition the input stream.
This current PR is to update the last processed offsets maintained by the OffsetManager during processing stage of the container correctly when elasticity is enabled.
**Changes:**
1. Modify OffsetManager.udpate to correctly identify the ssp even with keyBucket info is not present in the given parameter ssp
2. Modify SystemConsumers to provide the ssp,offset to Chooser after all the registrations are done. This is because, chooser is given an ssp without keyBucket but a container could be processing multiple keyBuckets within the same ssp. So after …

SAMZA-2734: [Elasticity] Update last processed offset after an envelopepe is finished processing when elasticity is enabled

---

samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/environment/EnvironmentVariables.java
samza-core/src/main/java/org/apache/samza/util/DiagnosticsUtil.java
samza-core/src/test/java/org/apache/samza/config/TestJobConfig.java

Issue: For environments in which apps run in isolated containers (e.g. Kubernetes), there is no need to have unique file names for container metadata files. It is much easier to find these files when they have static names instead of depending on the exec-env-container-id. A concrete Kubernetes use case for this is to be able to set the `terminationMessagePath` to this container metadata file in order to pass some information through to controllers.
Changes: Add a new environment variable `CONTAINER_METADATA_FILENAME` which specifies the name of the container metadata file.
API/usage changes: (backwards compatible) If `CONTAINER_METADATA_FILENAME` is specified, then use that for generating the container metadata file name. Otherwise, fall back to using the exec-env-container-id to …

SAMZA-2740: Provide a way to specify a static file name for container metadata file

---

samza-core/src/main/java/org/apache/samza/serializers/model/SamzaObjectMapper.java
samza-core/src/main/scala/org/apache/samza/serializers/CheckpointV1Serde.scala
samza-core/src/test/java/org/apache/samza/serializers/model/TestSamzaObjectMapper.java
samza-core/src/test/scala/org/apache/samza/serializers/TestCheckpointV1Serde.scala

**Feature:** Add KeyBucket into SSP serde for checkpoint. Elasticity (SAMZA-2687) allows consumption of part of SSP denoted by KeyBucket (introduced in #1576). This PR is to add the keybucket into SSP serde for checkpointv1 and when SSP is key in checkpointv2
**changes:**
1. add keybucket into CheckpointV1Serde
2. add keybucket for serde of SSP as Key in SamzaObjectMapper
**Tests:** updated and added new tests
**API Changes:** no public API changes
**Upgrade/usage instructions:** None
**Backwards compatible:** yes, new test added uses old serde and new serde together

SAMZA-2743: [Elasticity] Add keybucket into SSP serde for checkpoint

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java

**Summary**:
Standby feature is broken for jobs that don't have explicit side inputs
Change logged stores are treated as non-change logged for standby containers
[PR 1367](https://github.com/apache/samza/pull/1367) - Introduced a bug where jobs with no side inputs caused jobs to not bootstrap data for logged stores. The root cause was related to mutation of `taskSideInputStoreSSPs` as `changelogSSPs` that were added to it during initialization were ignored since the initialization of `hasSideInputs` happened before.
[PR 1491](https://github.com/apache/samza/pull/1491) - Introduced a bug where the logged stores were incorrectly classified as non-logged stores for standby container resulting in discarding of state at the end of container lifecycle. The root cause was …

SAMZA-2747: Standby bug fixes

---

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterBasedJobCoordinator.java
samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/drain/DrainMonitor.java
samza-core/src/main/java/org/apache/samza/drain/DrainNotification.java
samza-core/src/main/java/org/apache/samza/drain/DrainNotificationObjectMapper.java
samza-core/src/main/java/org/apache/samza/drain/DrainUtils.java
samza-core/src/main/java/org/apache/samza/processor/StreamProcessor.java
samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/job/local/ThreadJobFactory.scala
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/java/org/apache/samza/drain/DrainMonitorTests.java
samza-core/src/test/java/org/apache/samza/drain/DrainNotificationObjectMapperTests.java
samza-core/src/test/java/org/apache/samza/drain/DrainUtilsTests.java
samza-core/src/test/scala/org/apache/samza/container/TestSamzaContainer.scala
samza-core/src/test/scala/org/apache/samza/processor/StreamProcessorTestUtils.scala

**Feature:** 
[Pipeline Drain] SAMZA-2741 aims to support the ability to drain pipelines to allow incompatible intermediate schema changes.
This PR is a part of the Pipeline Drain work and aims to add some pipeline Drain components- DrainManager, DrainMonitor and DrainNotification and integrate them with Samza Container and JC. 
**Changes:**
This PR adds some pipeline Drain Components:
- DrainNotification: message in the metadata-store which acts as the trigger for Drain in samza containers and JC. 
- DrainManager: manages reads/writes of DrainNotifications to metadata-store
- DrainMonitor: looks for DrainNotifications on the DrainManager. Provides a callback
The PR will also integrate these components to SamzaContainer and JC. Changes to RunLoop, low level and high level API are not …

SAMZA-2742: [Pipeline Drain] Add Drain components and integrate them with SamzaContainer and JC

---

samza-core/src/main/java/org/apache/samza/startpoint/StartpointManager.java
samza-core/src/main/scala/org/apache/samza/checkpoint/OffsetManager.scala
samza-core/src/test/java/org/apache/samza/startpoint/TestStartpointManager.java
samza-core/src/test/scala/org/apache/samza/checkpoint/TestOffsetManager.scala

**Symptom**: 
Using startpoints to trigger full bootstrapping is not reliable in the current implementation, we observed that the bootstrapping only happened on the part of expected partitions. 
**Cause**:
Within Samza (the main class to pay attention to is OffsetManager.scala), there is a bug in which a startpoint can be deleted before the startpoint actually gets used for message consumption. If a container gets into this situation, then the result is that the startpoint is ignored and consumption will continue from the previous processed message from before the startpoint was applied.
- Load last processed offsets and startpoints
- Use startpoints to register starting offsets for consumers
- Message processing starts, but messages for only some of the partitions are received
- Write …

SAMZA-2749: Startpoint bug fix

---

.github/workflows/ci.yml

See: https://github.com/gradle/gradle/issues/9764 for additional details
For an example of how we might fix rat, see: https://github.com/apache/samza/pull/1619 (note that checkstyle, and maybe something else, also needs to be fixed)

SAMZA-2755: Pin jdk to 8.0.232 (fix up rat / broken master build)

---

samza-core/src/main/java/org/apache/samza/serializers/model/SamzaObjectMapper.java
samza-core/src/main/scala/org/apache/samza/serializers/CheckpointV1Serde.scala

Symptom: rolling back to versions which dont accept 4 parts in checkpoint serde can throw NPE exceptions.
Cause:
as part of elasticity, #1608 introduced keyBucket into checkpoint serde.
fix: remove keyBucket from checkpoint serde - aka do not add it when serializing checkpoint.
tests: existing pass.
usage/upgrade: N/A
backwards compatible: yes. 
Though checkpoints written after #1608 and before this PR will have 4 part SSP in checkpoint, serde, they can still be read by code in this PR and vice versa. 
elasticity will not work completely once this pr is merged.

remove keyBucket from checkpoint serde to allow for simpler rollback

---

samza-core/src/main/java/org/apache/samza/drain/DrainUtils.java
samza-core/src/main/java/org/apache/samza/runtime/LocalApplicationRunner.java
samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala
samza-core/src/test/java/org/apache/samza/drain/DrainMonitorTests.java
samza-test/src/test/java/org/apache/samza/test/drain/DrainHighLevelApiIntegrationTest.java
samza-test/src/test/java/org/apache/samza/test/drain/DrainLowLevelApiIntegrationTest.java

**Improvement:**
This PR is a part of the Pipeline Drain work and aims to improve `DrainUtils.writeDrainNotification` method which writes drain notifications to the metadata store. Currently, an external controller needs to supply the deployment id (runId).  The controller needs to have the knowledge of the current runId. For draining the current job, we should be able to retrieve the runId from the metadata store so it is not necessary for the caller of `DrainUtils.writeDrainNotification` to supply a runId for the current deployment.
**Changes:**
- Add a new method `DrainUtils.writeDrainNotification` which just takes the metadata store as the parameter. In cluster based deployments, configs (including the runId of a job) are written to the metadata store prior to starting the Job …

SAMZA-2741: [Pipeline Drain] Simplifying DrainUtils writeDrainNotification method and change tests

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java
samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppenderMetrics.java

Issues: 
Currently, StreamAppender is not extensible in terms of setting systemProducer and exposing sendEventToSystemProducer to child classes. It also makes it hard for child classes out of package to unit test any logic related to systemProducer
Changes: Make StreamAppender extensible
1.  Change method sendEventToSystemProducer from private to protected
2. Change member variable systemProducer from private to protected
Tests Done:
gradle build

Make StreamAppender extensible for sending event to SystemProducer

---

gradle/dependency-versions.gradle
samza-test/src/main/python/requirements.txt

Issues: We need to update the Zookeeper and Kazoo version to ensure the ZK client we are using is TLS compatible 
Changes:
Upgrade the dependency version
Tests: ./gradlew build 
Upgrade Instructions: All current users of Samza should be able to continue using Samza as usual, there is nothing required for upgrading to this new version.

Update zookeeper and kazoo version

---

samza-core/src/main/java/org/apache/samza/application/ApplicationUtil.java
samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/java/org/apache/samza/container/RunLoopFactory.java
samza-core/src/main/java/org/apache/samza/operators/impl/ControlMessageSender.java
samza-core/src/main/java/org/apache/samza/operators/impl/OperatorImpl.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/system/SystemConsumers.scala
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java
samza-test/src/test/java/org/apache/samza/test/drain/DrainHighLevelApiIntegrationTest.java
samza-test/src/test/java/org/apache/samza/test/drain/DrainLowLevelApiIntegrationTest.java

There were a few issues with the processing of drain messages that this PR attempts to fix. The following issues were encountered during the end-to-end testing with test pipelines.
1. It was observed that the `RunLoop` was running into an exception when a task was trying to consume from intermediate streams.
This was happening as we stop all consumers in `SystemConsumers` when we encounter drain. This also stops the consumers which ingest data from the intermediate streams. 
_After 1 was resolved, some additional issues were observed-_
2. The pipeline was getting stuck after partial consumption of data after the last shuffle stage. 
This was happening as we were removing the SSPs from the processing set of SSPs for a task for high-level API processing. This was leading to unprocessed …

SAMZA-2741: [Pipeline Drain] Fix processing of Drain messages for High-Level and Low-level API

---

samza-core/src/main/java/org/apache/samza/container/SamzaContainerMonitorListener.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/test/java/org/apache/samza/container/TestSamzaContainerMonitorListener.java

No data was emitted for the metric `container-active-threads`
This PR(#1501 ) removed the logic to emit data for metric accidently: https://github.com/apache/samza/pull/1501/files#diff-f79781ad4c55ae7860829b06fd9dfd15e8069c37e64f8854d8f27ca2cd1f3ee5L637 
- Add the deleted logic back in a new class`SamzaContainerMonitorListener` 
- Unit tests

SAMZA-2764: add the metric "container-active-threads" back

---

build.gradle
docs/learn/documentation/versioned/container/metrics-table.html
docs/learn/documentation/versioned/operations/monitoring.md
gradle/dependency-versions.gradle
samza-core/src/main/java/org/apache/samza/container/SamzaContainerMonitorListener.java
samza-core/src/main/java/org/apache/samza/container/host/DefaultSystemStatisticsGetter.java
samza-core/src/main/java/org/apache/samza/container/host/OshiBasedStatisticsGetter.java
samza-core/src/main/java/org/apache/samza/container/host/PosixCommandBasedStatisticsGetter.java
samza-core/src/main/java/org/apache/samza/container/host/ProcessCPUStatistics.java
samza-core/src/main/java/org/apache/samza/container/host/StatisticsMonitorImpl.java
samza-core/src/main/java/org/apache/samza/container/host/SystemStatistics.java
samza-core/src/main/java/org/apache/samza/container/host/SystemStatisticsGetter.java
samza-core/src/main/java/org/apache/samza/container/host/SystemStatisticsMonitor.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala
samza-core/src/test/java/org/apache/samza/container/TestSamzaContainerMonitorListener.java
samza-core/src/test/java/org/apache/samza/container/host/TestDefaultSystemStatisticsGetter.java
samza-core/src/test/java/org/apache/samza/container/host/TestOshiBasedStatisticsGetter.java
samza-core/src/test/java/org/apache/samza/container/host/TestStatisticsMonitorImpl.java

We have observed that some use cases used quasar(TensorFlow framework) to do model inference and this framework spawn child processes(non-JVM) to run TensorFlow serving. These child processes were using high CPU usage(200%) however their CPU usage can't be captured by the existing CPU usage metric `process-cpu-usage`
The existing metric `process-cpu-usage` metric was designed for capturing the [CPU usage for the JVM process](https://samza.apache.org/learn/documentation/1.6.0/operations/monitoring.html) only, it can't count the child processes(especially for non-JVM processes) usage.
- Reply on [oshi framwork](https://www.oshi.ooo/) to capture the CPU usage for the JVM process and all its child processes, and create a new metric to display the total CPU usage.
- The CPU usage percentage is …

SAMZA-2762: new cpu usage metric which counts child processes usage

---

samza-api/src/main/java/org/apache/samza/application/ApplicationApiType.java
samza-core/src/main/java/org/apache/samza/application/ApplicationUtil.java
samza-core/src/main/java/org/apache/samza/config/ApplicationConfig.java
samza-core/src/main/java/org/apache/samza/container/RunLoopFactory.java
samza-core/src/main/java/org/apache/samza/execution/JobPlanner.java
samza-core/src/test/java/org/apache/samza/application/TestApplicationUtil.java

`ApplicationUtil.isHighLevelApiJob` doesn't work for cases where `SamzaApplication` were created as an anonymous class or lambda
Anonymous class names and lambdas classes cannot be created using `Class forName()`. As a result, the current logic currently assumes that the class name was incorrect. 
Introduce an internal config `app.api.type` and we set the config using `AppDescriptor` in `JobPlanner`.
- Unit test for `ApplicationUtil.isHighLevelApiJob`
- Tested with a sample application

SAMZA-2741: [Pipeline Drain] Fix ApplicationUtil.isHighLevelApiJob to work for anonymous and lambda `SamzaApplication` classes

---

samza-api/src/main/java/org/apache/samza/system/IncomingMessageEnvelope.java
samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/java/org/apache/samza/container/RunLoopFactory.java
samza-core/src/main/java/org/apache/samza/task/TaskCallbackManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/java/org/apache/samza/config/TestTaskConfig.java
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java
samza-core/src/test/java/org/apache/samza/task/TestTaskCallbackManager.java

This PR is a part of the Pipeline Drain work and aims to provide a way to specify a task callback timeout to be used for pipeline drain. The standard `task.callback.timeout.ms` parameter might be too small for the drain operation to complete. Drain operation will involve clearing of intermediate state which might require a larger timeout for the task callback. We need a way to provide a configurable timeout to be used during drain operation.
- Add a new config `task.callback.drain.timeout.ms` in `TaskConfig`
- Added logic to override `TaskCallbackManager`'s timeout parameter in `TaskWorker`s on drain.
- Unit test changes for `TaskConfig`

SAMZA-2765: [Pipeline Drain] Adding config for task callback timeout during drain

---

samza-api/src/main/java/org/apache/samza/drain/DrainMode.java
samza-api/src/main/java/org/apache/samza/drain/DrainNotification.java
samza-core/src/main/java/org/apache/samza/drain/DrainNotificationObjectMapper.java
samza-core/src/main/java/org/apache/samza/drain/DrainUtils.java
samza-core/src/test/java/org/apache/samza/drain/DrainUtilsTests.java

The current `DrainNotification` is a class tasked with signaling samza engine to clear intermediate state. We need an additional field to indicate the type of drain operation.
- Add `DrainMode` drain operation type to `samza-api` and add drainMode to `DrainNotification`
- Change `DrainNotificationObjectMapper` 
- Alter `DrainUtils` to accommodate the above changes
- Tests for `DrainNotificationObjectMapper` 
- Tests for `DrainUtils`

SAMZA-2769: [PipelineDrain] Add drainMode to DrainNotification

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java
samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppenderMetrics.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/TestStreamAppender.java

Issue: 
We observed logging data loss happens in StreamAppender
The RC is the current implementation of the “[append()](https://github.com/apache/samza/blob/master/samza-log4j/src/main/java/org/apache/samza/logging/log4j/StreamAppender.java#L146)” method uses one AtomicBoolean variable to detect if the thread is called recursively, which could lead to race conditions when "append()" is invoked by multiple threads and could cause log data loss.
we have reproduced the data loss issue locally in the multithread logging scenarios.
When the current implementation was introduced in samza, log4j1 framework didn't have recursive call prevention logic at the framework layer. More context can be found in [SAMZA-723](https://issues.apache.org/jira/browse/SAMZA-723)
However, the current …

LISAMZA-27395 removing the current recursive call prevention logic

---

samza-api/src/main/java/org/apache/samza/storage/StateBackendFactory.java
samza-core/src/main/java/org/apache/samza/storage/KafkaChangelogStateBackendFactory.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreStateBackendFactory.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala

Bug
- We introduced blob store backed for state backup and restore in [this commit](https://github.com/apache/samza/commit/7cc4eaa96fff244f6dce9c18af804917db7c3b2b).
- `StateBackendFactory` implementations like for Kafka and BlobStore create systemAdmins every time `getBackupFactory` is called from `SamzaContainer`. This leads to creation of duplicate kafka admin threads. 
- This has impact on performance of large samza jobs as we have thousands of duplicate threads spawned.
Fix
- Pass `systemAdminsMap` to `getBackendFactory` method. This initializes the SystemAdmins with the system admin map rather than creating system admins every time the method is called. 
Test
- Tested with local jobs to verify the kafka admin threads are not duplicated.

Fix performance bug in kafka/blobstore commit lifecycle.

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java

Currently if a restore factory is missing due to a misconfiguration we exit due to a NPE
```
2022-12-13 18:23:07.794 [main] SamzaContainer [ERROR] Caught exception/error while initializing container.
java.lang.NullPointerException: null
at org.apache.samza.storage.ContainerStorageManager.lambda$createTaskRestoreManagers$15(ContainerStorageManager.java:485) ~[samza-core_2.12-320.1081.0.4.jar:?]
at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_282]
at org.apache.samza.storage.ContainerStorageManager.createTaskRestoreManagers(ContainerStorageManager.java:480) ~[samza-core_2.12-320.1081.0.4.jar:?]
at org.apache.samza.storage.ContainerStorageManager.lambda$restoreStores$27(ContainerStorageManager.java:857) ~[samza-core_2.12-320.1081.0.4.jar:?]
at …
```

Fix restore factory not configured log

---

docs/_blog/2023-01-17-announcing-the-release-of-apache-samza--1.8.0.md
docs/_config.yml
docs/_menu/index.html
docs/_releases/1.7.0.md
docs/_releases/1.8.0.md
docs/archive/index.html
docs/learn/tutorials/versioned/hello-samza-high-level-yarn.md
docs/learn/tutorials/versioned/hello-samza-high-level-zk.md
docs/learn/tutorials/versioned/samza-rest-getting-started.md
docs/startup/download/index.md
docs/startup/hello-samza/versioned/index.md
gradle.properties

This PR has all website/doc related changes w.r.t to samza 1.8.0 release. Since we did not add anything for 1.7.0 release, this PR adds a release.md and download links for 1.7.0 release.

[Docs] Samza 1.8.0 release website updates

---

samza-log4j2/src/main/java/org/apache/samza/logging/log4j2/StreamAppender.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/MockSystemAdmin.java
samza-log4j2/src/test/java/org/apache/samza/logging/log4j2/TestStreamAppender.java

Issue:
In StreamAppender, there is a synchronized block around setupSystem(), which should be called the first time (after loggingContext config is set up) any logger logs something.
It could lead to a deadlock situation. Because if during the setupSystem(), any other threads try to do LOG.xxx(), they will be blocked, and if the system setup depends on those threads, it leads to deadlock
Change:
Replace the synchronized block with a [tryLock](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/Lock.html#tryLock(long,%20java.util.concurrent.TimeUnit))(long time, [TimeUnit](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeUnit.html) unit)
so that other threads won't be blocked forever if setupSystem() stuck or timeout
Usage Change:
If any thread try to log …

Fix deadlock in StreamAppender

---

samza-core/src/main/java/org/apache/samza/config/StorageConfig.java
samza-core/src/main/java/org/apache/samza/storage/TaskStorageCommitManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreBackupManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/metrics/BlobStoreBackupManagerMetrics.java
samza-core/src/test/java/org/apache/samza/config/TestStorageConfig.java

Part 1 of 2. Follow up PR to restore side input stores using Blob Store backups coming soon.
Symptoms: 
1. Side input stores are uploaded twice when using Blob Store State Backend.
2. Store-level Gauges (but not Timers) in BlobStoreBackupManagerMetrics are broken for side input stores.
3. Task level Gauges in BlobStoreBackupManagerMetrics have incorrect value (count twice for side input stores).
Cause: 
1. StorageConfig#getStoreNames() returns side input stores twice in the list. 
2. BlobStoreBackupManager does not dedup storesToBackup list.
3. PR #1223 makes the duplicate-registration behavior between Gauges and Timers inconsistent.
Changes: 
1. Fixed StorageConfig#getStoreNames() to dedup store names.
2. Added defensive dedup in BlobStoreBackupManager.
3. Changed store level metrics …

Side Inputs + Blob Store Backups - Part 1 - Fix duplicate uploads and broken metrics

---

samza-core/src/main/java/org/apache/samza/storage/NonTransactionalStateTaskRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/TransactionalStateTaskRestoreManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManagerUtil.java
samza-core/src/main/scala/org/apache/samza/storage/SideInputsManager.java
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java

Issues: ContainerStorageManager has gotten very unwieldy with 1000+ LOC of highly complex and invocation-order dependent logic. It also does too much by trying to manage side inputs lifecycle along with regular state stores'.
Changes: 
1. Separated side inputs (and standby) related store creation and restore logic into a separate SideInputsManager class.
2. Separated helper methods into a ContainerStorageManagerUtil class, and made them all static to ensure that they don't mutate class fields. 
Most of the PR is simply moving code from one place to another. However a couple of places that introduce semantic changes or otherwise require careful review are called inline in "Refactor Note" comments.
There is a lot more room for improvement (e.g. more javadocs, more tests, simplifying method …

Refactored ContainerStorageManager for readability and manageability

---

samza-core/src/main/java/org/apache/samza/storage/NonTransactionalStateTaskRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/TransactionalStateTaskRestoreManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/SideInputsManager.java

Fixed line-length related formatting issues

---

samza-core/src/main/java/org/apache/samza/storage/TaskStorageCommitManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreRestoreManager.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/TestBlobStoreBackupManager.java
samza-rest/src/main/java/org/apache/samza/monitor/LocalStoreMonitor.java
samza-rest/src/test/java/org/apache/samza/monitor/TestLocalStoreMonitor.java
samza-test/src/test/java/org/apache/samza/storage/kv/BlobStoreStateBackendIntegrationTest.java
samza-test/src/test/java/org/apache/samza/storage/kv/KafkaNonTransactionalStateIntegrationTest.java
samza-test/src/test/java/org/apache/samza/storage/kv/KafkaTransactionalStateIntegrationTest.java

Symptom: Blob store state restore fails when verifying restored directory contents due to a mismatch between permissions of local vs remote files.
Cause: Apache Commons 2.11 (at least, more versions may be affected) FileUtils#deleteDirectory() has a bug where it changes the permissions of symlink/hardlink files to read-only after deletion. For more details, see https://issues.apache.org/jira/browse/IO-751. This means that TaskStorageCommitManager#deleteOldCheckpointDirs() causes the permissions for the original store files hard-linked from the checkpoint directory to be changed to read only. This causes the file to be considered different than the one already uploaded on next checkpoint and re-uploaded. Since restore recreates all files in rw mode, they fail post-restore verifications due …

Changed uses of Apache Commons IO FileUtils.deleteDirectory to PathUtils.deleteDirectory

---

samza-azure/src/main/java/org/apache/samza/system/azureblob/avro/AzureBlobAvroWriter.java
samza-azure/src/test/java/org/apache/samza/system/azureblob/avro/TestAzureBlobAvroWriter.java

Add support for `GenericFixed` types to `AzureBlobAvroWriter`, the Samza provided implementation for `AzureBlobWriter`. This allows the caller to provide the `Schema` **and** deserialized object in the `OutgoingMessageEnvelope`. Using `GenericFixed`, the caller can avoid the CPU overhead of deserialization and guarantee that the `Schema` is set in the writer instance.
The existing implementation requires that all messages are either of type `IndexedRecord` - a deserialized object with `Schema` - or an Avro-encoded `byte[]` - deserialized object without `Schema`. The writer aggregates these messages in an Avro file format which requires a `Schema`. Because the `Schema` is unset when the writer is initialized, it cannot aggregate the messages, until the caller sends an `IndexedRecord`. …

SAMZA-2777: Add support for GenericFixed to AzureBlobAvroWriter

---

samza-api/src/main/java/org/apache/samza/context/ContainerContext.java
samza-api/src/main/java/org/apache/samza/task/StreamOperatorTaskFactory.java
samza-core/src/main/java/org/apache/samza/context/ContainerContextImpl.java
samza-core/src/main/java/org/apache/samza/storage/StorageRecovery.java
samza-core/src/main/java/org/apache/samza/task/StreamOperatorTask.java
samza-core/src/main/java/org/apache/samza/task/TaskFactoryUtil.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/test/java/org/apache/samza/storage/TestKafkaChangelogStateBackendFactory.java
samza-core/src/test/java/org/apache/samza/task/TestTaskFactoryUtil.java
samza-test/src/main/scala/org/apache/samza/test/performance/TestKeyValuePerformance.scala

Prior to `TaskContext` and `ContainerContext`, the container thread pool was injected into `StreamOperatorTask` using `TaskFactoryUtil` and round about ways.
Now that we have these contexts, it is easier to inject and simplify the DI.
**Changes**:
- Add container thread pool to `ContainerContext`
- Clean up `TaskFactoryUtil` and other remnants of previous DI
- Deprecate `StreamOperatorTaskFactory`
**Tests**:
- Unit tests
- Updated existing tests
**API Changes**: 
Added `getContainerThreadPool` to `ContainerContext`

SAMZA-2782: Clean up container thread pool DI into StreamOperatorTask

---

samza-api/src/main/java/org/apache/samza/context/TaskContext.java
samza-api/src/main/java/org/apache/samza/task/TaskExecutorFactory.java
samza-core/src/main/java/org/apache/samza/context/TaskContextImpl.java
samza-core/src/main/java/org/apache/samza/operators/impl/OperatorImpl.java
samza-core/src/main/java/org/apache/samza/task/DefaultTaskExecutorFactory.java
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/java/org/apache/samza/context/TestTaskContextImpl.java
samza-core/src/test/java/org/apache/samza/operators/TestJoinOperator.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestOperatorImpl.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestOperatorImplGraph.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestWindowOperator.java
samza-core/src/test/java/org/apache/samza/task/TestDefaultTaskExecutorFactory.java
samza-core/src/test/java/org/apache/samza/testUtils/StreamTestUtils.java
samza-sql/src/test/java/org/apache/samza/sql/system/TestAvroSystemFactory.java
samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java

Currently, the operator implementation chains the future using synchronous APIs (thenCompose, thenApply) which results in execution of these method calls on the future completion thread which happens to be the user thread in case of asynchronous operators in application DAG.
**Changes**:
- Use thread pool inject through `job.container.task.executor.factory`
- Extend the task executor factory to return operator executor 
- Wire in the task executor in `TaskContext`
- Default implementation which uses `#getTaskExecutor` if enabled and `job.container.thread.pool.size` > 1 or fallback to single threaded executor otherwise.
**Testing**:
- Unit tests for the factory
- Test updates for existing `OperatorImpl` tests.
**API Changes**:
- Add `getOperatorExecutor` to …

SAMZA-2781: Use framework thread to execute hand-offs and sub-DAG execution

---

samza-azure/src/main/java/org/apache/samza/system/eventhub/consumer/EventHubSystemConsumer.java
samza-azure/src/test/java/org/apache/samza/system/eventhub/MockEventHubClientManagerFactory.java

Symptom: self-reported bug.
Cause: A variable added in #1660 is unused. The parameter sets the offset in the `PartitionReceiver`. The change was required because of API changes in the previous PR.
Changes: This change was required in two places in the original PR, however, only [one](https://github.com/apache/samza/pull/1660#discussion_r1228789636) was unused. This PR corrects that and updates both sites to a similar code structure.
Tests: No new tests were added. Existing tests did not identify the mistake because the change did not affect  the mock used for testing. After the change, the tests failed until the mock was updated.

SAMZA-2776: Fix unused parameter - EventHubSystemConsumer

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/index/FileMetadata.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/util/DirDiffUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestDirDiffUtilAreSameFile.java

Re-factor `DirDiffUtil.getDirDiff` to minimize calls to sun.nio.fs.*
Profiling a real-world job showed ~38% of the time being spent in `DirDiffUtil.getDirDiff` for a given profile snapshot.  Investigating it seems that the call to `DirDiffUtil.areSameFile` is the primary cause of `DirDiffUtil.getDirDiff` showing up high on this particular profile.  Looking at the code there is the following comment:
```
// TODO MED shesharm: this compares each file in directory 3 times. Categorize files in one traversal instead.
```
Re-factored creation of the lists `filesToUpload`, `filesToRetain`, and `filesToRemove` to iterate on the files once which reduces the number of times `DirDiffUtil.areSameFile` is called.  
The re-factor should reduce the number of calls by reducing the number of calls to …

Re-factor DirDiffUtil.getDirDiff  to traverse and test files once.

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/util/DirDiffUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestDirDiffUtilAreSameFile.java

Fix scope of owner and group name caches in `DirDiffUtil.areSameFile`
In #1669 the caches were scoped incorrectly and will be re-created each time `areSameFile` called.  Scoping the group and name caches outside of the lambda to cache as expected.
* Added unit test `TestDirDiffUtilAreSameFile.testAreSameFile_Cache` to verify the caches are working as expected.
* `./gradlew check`

Fix scope of caches for DirDiffUtil.areSameFile

---

.github/workflows/ci.yml

This change allows GitHub Actions builds to submit build scans to ge.apache.org by authenticating those builds. The access key has been stored as an organizational secret by the ASF Infrastructure team in the Apache GitHub organization. The access key is not available to workflows triggered from forks.
This builds on the changes in https://github.com/apache/samza/pull/1665

Authenticate GitHub Actions builds to ge.apache.org

---

docs/learn/documentation/versioned/container/metrics-table.html
samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java
samza-yarn/src/main/scala/org/apache/samza/job/yarn/SamzaAppMasterMetrics.scala
samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnClusterResourceManager.java
samza-yarn/src/test/java/org/apache/samza/webapp/TestApplicationMasterRestClient.java

[LISAMZA-28234](https://jira01.corp.linkedin.com:8443/browse/LISAMZA-28234)
Symptom:
We have observed that Samza YARN AM requests 2-3x more containers than needed during job startup. Can cause temporary resource exhaustion in cluster when large jobs are launched, causing unrelated deployments to timeout/fail.
Change:
This PR added a Samza AM metric to monitor how many containers are allocated by RM and buffered in AM 
The metric increments when AM got an allocated container from RM and add it to the buffer. The metric decrements when AM released the overallocated containers (after all processors started). 
By observing this metric, we can know how many containers were allocated to a job during its startup and how long before the overallocated ones got released.

Add new SamzaApplicationMaster metric to track allocated containers buffered in AM

---

samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainerMetrics.scala
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java

LISAMZA-31001
Symptom: The "Container Not Running" metric is broken when container level metrics is enabled.
Fix: Adding a new gauge metric to report 1 whenever a container is processing. "Container Not Running" can be calculated by total_container_count - sum(container_running)

SAMZA-2788: Add new metric to emit 1 when containers are processing

---

samza-core/src/main/java/org/apache/samza/execution/IntermediateStreamManager.java
samza-core/src/main/java/org/apache/samza/task/DefaultTaskExecutorFactory.java
samza-core/src/test/java/org/apache/samza/execution/TestExecutionPlanner.java
samza-core/src/test/java/org/apache/samza/execution/TestIntermediateStreamManager.java

**Problem**: Intermediate stream partition count inference logic caps the partition size to 256 resulting in imbalances in work assignments to tasks
**Description**: As part of the intermediate partition size inference logic, we currently employ the following algorithm.
- partitionCount = Math.max(maxPartitionSize(inputStreams), maxPartitionSize(outputStreams))
- cap the partitionCount to MAX_INFERRED_PARTITIONS defined in the `IntermediateStreamManager` which is 256
- apply the inferred partition count to intermediate streams whose partition count is uninitialized
The logic above always caps the partition size of intermediate streams to 256 for all auto-created intermediate streams. This can prevent the job from scaling up uniformly as the intermediate partition assignment is capped to …

SAMZA-2789: Remove cap on intermediate stream partition count for stream mode

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManagerRestoreUtil.java
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java

Bug:
taskRestoreManagers.close() which in return calls blobStoreManager.close(), is called before the future for restoreDeletedSnapshots completes. This should only be called when all the futures are returned and complete.
Fix:
Close taskRestoreManagers after the restore as well as recovery of deleted snapshots (which also involves restore) are returned and complete. 
Init the blobStoreManager returned by factory, to avoid any race condition of calling operations on a closed blobStoreManager.

Fix race condition in ContainerStorageManager

---

samza-core/src/main/java/org/apache/samza/config/BlobStoreConfig.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreBackupManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreRestoreManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/util/DirDiffUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/TestBlobStoreBackupManager.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/TestBlobStoreRestoreManager.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestBlobStoreUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestDirDiffUtilAreSameFile.java

Issue:
When a samza job is moved to a new set of hosts and a full restore from Blob store is performed, the restore (and the job) fails with an error that the owner of the remote and local files are different. While this is an unexpected and correctly identified as an issue with the restore from blob store, some times this is not desirable. In this case, since the job moved to a new host, the gid/uid are different and restore/container starts fail. 
Fix:
Ignore the uid/gid match after restoring the state, if a config "blob.store.compare.file.owners.on.restore" is set.
By default we always match the owners, except for the verify restore step after a restore from blob store. In this case, we check this new config to see if we should match the owners of the restores files/dirs or not. 
Test: …

Ignore file owners comparison on restore when config is set

---

samza-core/src/main/java/org/apache/samza/application/ApplicationUtil.java
samza-core/src/main/java/org/apache/samza/config/ApplicationConfig.java
samza-core/src/main/java/org/apache/samza/config/RunLoopConfig.java
samza-core/src/main/java/org/apache/samza/container/RunLoop.java
samza-core/src/main/java/org/apache/samza/container/RunLoopFactory.java
samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala
samza-core/src/main/scala/org/apache/samza/storage/SideInputsManager.java
samza-core/src/test/java/org/apache/samza/application/TestApplicationUtil.java
samza-core/src/test/java/org/apache/samza/config/TestApplicationConfig.java
samza-core/src/test/java/org/apache/samza/container/TestRunLoop.java

Runloop currently takes in lot of parameters and the constructor has grown to the point where it is unmanageable with multiple overloads. Introducing new configuration requires lot of updates to existing tests and components even if the parameters have no effect on all of the usages.
With this PR, we should be able to decouple different users of RunLoop and enable these components to have their own scoped config. e.g., `SideInputManager` can now have its own set of runloop parameters without having to tie itself with `TaskConfig`.
**Changes**:
- Introduce `RunLoopConfig`, a container object to hold all required parameters for runloop from `Config`.
- Remove existing overloads of constructor 
- Simplify the constructor to take `RunLoopConfig` and initialize the necessary …

SAMZA-2790: Cleanup RunLoop constructor explosion

---

samza-shell/src/main/bash/run-class.sh

Manifest generation (application-level) is pointing to container-level symlinks instead of application-level files.
This will cause issues when multiple containers for an application land on a single host and the container the manifest is pointing to gets cleaned up.
```
[yyy@zzz filecache]$ cat /data/appcache/application_1668550466222_0989/filecache/10/xxx-0.0.672.tgz/classpath_workspace/manifest.txt|tail -n 2
/data/appcache/application_1668550466222_0989/container_e114_1668550466222_0989_01_000003/__package/lib/zstd-jni-1.5.2-3.jar
[yyy@zzz filecache]$
```
This patch is to resolve those symlinks to their application level paths.

SAMZA-2774: Resolve classpath symlinks

---

samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java
samza-core/src/test/java/org/apache/samza/runtime/TestContainerLaunchUtil.java

**Issues**
In ContainerLaunchUtil, exitProcess is called at various points, which can be perplexing when determining where the actual program termination occurs. 
**Changes**
1. Instead of exit at multi place, make the protected "run" return exitCode instead exit in itself. With the change, ContainerLaunchUtil has a unique exit path.
**Tests**
Add a unit test to cover exitCode = 0, verify the exit is called.

SAMZA-2792: Unique System.exit in ContainerLaunchUtil

---

docs/learn/documentation/versioned/jobs/configuration-table.html
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/config/ShellCommandConfig.java
samza-core/src/main/java/org/apache/samza/job/ShellCommandBuilder.java
samza-core/src/test/java/org/apache/samza/config/TestShellCommandConfig.java
samza-core/src/test/java/org/apache/samza/job/TestShellCommandBuilder.java

**Summary**: Support JVM options for worker process in Samza Beam portable mode
Description: With portable mode support for Samza Beam, we want to tune and configure the JVM options for worker process. In this PR, we add support by introducing worker.opts configuration and autosizing integration support.
**Changes**:
- Added worker.opts configuration
- Add autosizing integration support for Xmx
- Updated configuration table and website
**Usage Instructions**: worker.opts can be used similar to other samza application configuration although it only applies to Samza Beam portable execution mode and is ignored otherwise.

SAMZA-2763: Support worker JVM opts for Samza Beam portable mode

---

docs/learn/documentation/versioned/jobs/configuration-table.html
samza-core/src/main/java/org/apache/samza/config/JobConfig.java
samza-core/src/main/java/org/apache/samza/operators/impl/OperatorImpl.java
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala
samza-core/src/test/java/org/apache/samza/operators/impl/TestOperatorImpl.java

**Description**
As part of  [SAMZA-2781](https://issues.apache.org/jira/browse/SAMZA-2781), we use framework thread pool to execute hand-offs and sub-DAG execution. We want to add a config knob to enable users opt-in to the feature as opposed to enable it by default.
**Changes**
- Introduce config knob to use the framework executor
**Tests**
- Added unit tests
**API Changes**
None
**Usage Instructions**
Refer to the configuration documentation. To enable framework thread pool for sub-DAG execution and message hand off, set `job.operator.framework.executor.enabled` to `true`
**Upgrade Instructions**
None

SAMZA-2796: Introduce config knob for framework thread sub DAG execution

---

samza-core/src/main/java/org/apache/samza/coordinator/stream/CoordinatorStreamSystemProducer.java
samza-core/src/main/java/org/apache/samza/coordinator/stream/CoordinatorStreamWriter.java

- Some implementations of `SystemProducer` can have an async implementation of the send API. 
- `CoordinatorStreamWriter` writes only one message and closes the underlying `CoordinatorStreamSystemProducer` right after writes. There is a chance that the producer close will be called before the async write can complete.
- This PR adds `flush` API to `CoordinatorStreamSystemProducer`
- We will call `flush` prior to `stop` in `CoordinatorStreamWriter` so that async messages are flushed out prior to stop
- `./gradlew build`
- Tested with sample apps
None
None
None

SAMZA-2797: Add flush to CoordinatorStreamSystemProducer and call it during CoordinatorStreamWriter stop

---

samza-core/src/main/java/org/apache/samza/job/ShellCommandBuilder.java
samza-core/src/test/java/org/apache/samza/job/TestShellCommandBuilder.java

**Description**
Populate worker.opts in the environment variable only if available in the configs.
**Changes**
Check if worker.opts is present and then add it to environment variable
**Tests**
Updated unit tests

SAMZA-2798: Populate worker.opts in environment variable only if available

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/BlobStoreBackupManager.java
samza-core/src/main/java/org/apache/samza/storage/blobstore/util/DirDiffUtil.java
samza-core/src/main/scala/org/apache/samza/container/TaskInstance.scala

Currently we have noisy per commit logs that trigger each task.commit.ms which clogs up the users logs
```
2024-01-12 21:59:37.322 [Samza Task Commit Thread-46] TaskInstance [INFO] Cleaning up old checkpoint state for taskName: SystemStreamPartition [brooklin-profile-samza-euler-index-builder, profile-samza-euler-index-builder, 907] checkpointId: 1705096777263-770646
2024-01-12 21:59:37.322 [Samza Task Commit Thread-18] TaskInstance [INFO] Cleaning up old checkpoint state for taskName: SystemStreamPartition [brooklin-profile-samza-euler-index-builder, profile-samza-euler-index-builder, 1908] checkpointId: 1705096777264-482671
2024-01-12 21:59:37.321 [Samza Task Commit Thread-7] TaskInstance [INFO] Cleaning up old checkpoint state for taskName: SystemStreamPartition …
```

SAMZA-2784: Remove excessive commit logs

---

samza-core/src/main/java/org/apache/samza/job/ShellCommandBuilder.java
samza-core/src/test/java/org/apache/samza/job/TestShellCommandBuilder.java

**Description**
Remove worker.opts handling within `ShellCommandBuilder`. It is handled by beam internally and there is no other integration currently to have this integrated as part of the `ShellCommandBuilder` yet.
**Changes**
Remove worker.opts related changes in `ShellCommandBuilder`
**Tests**
Updated unit tests
**API Changes**: None; It shouldn't affect anything as it isn't used in samza container.

SAMZA-2799: Remove worker.opts handling in shell command builder

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManagerUtil.java
samza-core/src/main/scala/org/apache/samza/storage/SideInputsManager.java
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java

Fix for the bug: https://issues.apache.org/jira/browse/SAMZA-2752
What:
Set durable store names in a set in the ContainerStorageManager constructor
Why:
During previous refractoring, the createStore for durable stores was moved outside of constructor. However, the store directory paths are required to be set in constructor so that SamzaContainer class can set monitors for them. This patch sets the store names without creating the stores, so that monitoring can be set properly.

Create store directory paths in CSM constructor for disk space monitor

---

docs/learn/documentation/versioned/api/beam-api.md
gradle/buildscript.gradle
samza-shell/src/main/bash/run-class.sh

1. Fix the typo in the beam API documentation
2. Print out the current timestamp at `run-class.sh` with stdout. Before making the change, which helps better monitor the job during container launch time, before container logs are available
3. Fix the build issue, which has the same symptom mentioned in https://issues.apache.org/jira/browse/SAMZA-2786
---
```
$ echo "Current time: $(date '+%Y-%m-%d %H:%M:%S')"
Current time: 2024-07-29 17:20:03
```

Output Current Timestamp at run-class.sh script

---

samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbOptionsHelper.java

documentation of `targetFileSizeBase` and `targetFileSizeMultiplier` is located [here](https://javadoc.io/static/org.rocksdb/rocksdbjni/7.8.3/org/rocksdb/Options.html#targetFileSizeBase--) (texted copied below)
> targetFileSizeBase determines a level-1 file size. Target file size for level L can be calculated by targetFileSizeBase * (targetFileSizeMultiplier ^ (L-1)) For example, if targetFileSizeBase is 2MB and target_file_size_multiplier is 10, then each file on level-1 will be 2MB, and each file on level 2 will be 20MB, and each file on level-3 will be 200MB. by default targetFileSizeBase is 64MB.
https://github.com/apache/samza/blob/f9c3241b87ce5d7a568368d3ffec5dea174f7692/samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbOptionsHelper.java#L178-L184 
Behavior: 
- If …

BUG FIX: set target file size multiplier

---

samza-core/src/main/java/org/apache/samza/config/TaskConfig.java
samza-core/src/main/java/org/apache/samza/operators/impl/OperatorImplGraph.java
samza-core/src/main/java/org/apache/samza/operators/impl/WatermarkStates.java
samza-core/src/test/java/org/apache/samza/operators/impl/TestWatermarkStates.java

Currently in the Samza event-time watermark aggregation logic, it will compute the watermark as the min of watermarks from all upstream tasks. However, in the lagging cases, the upstream task might not generate watermark for a long period. In this case, the new watermarks will not be generated and the downstream aggregation will be stuck.
To address this issue, this patch adds the logic to exclude the tasks that have been "idle" in generating watermark for a configured time, so that the aggregated watermarks will still be generated. Note this mechanism will unblock downstream, but also at the risk of moving event-time clock faster and the events from lagging tasks will become late arrivals.

SAMZA-2801: Support excluding tasks from watermark computation when exceeding idle time

---

build.gradle
gradle/buildscript.gradle

**Symptom**: 
Master build doesn't work. We run into the following exception:
```
What went wrong:
A problem occurred configuring root project 'samza'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not find grolifant-0.12.jar (org.ysb33r.gradle:grolifant:0.12).
Searched in the following locations:
https://jcenter.bintray.com/org/ysb33r/gradle/grolifant/0.12/grolifant-0.12.jar
> Could not find okhttp-digest-1.10.jar (com.burgstaller:okhttp-digest:1.10).
Searched in the following locations:
https://jcenter.bintray.com/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.jar
```
**Cause**:
- `okhttp-digest`'s group has been changed from `com.burgstaller` to `io.github.rburgst`
- `org.ysb33r.gradle:grolifant` v0.12 isn't available anymore on jcenter. This version …

Update org.ysb33r.gradle:grolifant version and use io.github.rburgst instead of com.burgstaller

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/util/BlobStoreUtil.java

**Symptom**: 
`BlobStoreUtil` doesn't log the blob id today when it fails to deserialize the snapshot blob. Without the blob id, it is tricky to debug why the deserialization issue happened.
**Changes**:
- Log the blob id if we are unable to deserialize the snapshot blobs
**Tests**:
- ./gradlew build
**API Changes**:
None
**Upgrade Instructions**: 
None
**Usage Instructions**: 
None

Log bob deserialization exception for snapshot blobs

---

samza-core/src/main/java/org/apache/samza/storage/blobstore/util/BlobStoreUtil.java
samza-core/src/test/java/org/apache/samza/storage/blobstore/util/TestBlobStoreUtil.java

**Bug**: 
`BlobStoreUtil`'s `getSnapshotIndex` method currently gets the `SnapshotIndex` blob using `BlobStoreManager#get` and deserializes it using `SnapshotIndexSerde`. We handle the exceptions encountered in the get step and deserialization step using the chained `handle` step. 
The error log ,however, tells thats the exception was due to deserialization. This is incorrect as the `handle` will get exceptions from any of the previous steps i.e get and not just the deserialization step.
**Changes**:
- Change `handle` message to reflect the correct exception message
**Tests**:
- ./gradlew build
- Added unit tests to assert if appropriate exception is thrown
**API Changes**:
None
**Upgrade Instructions**: 
None
**Usage Instructions**: 
None

Fix exception message in BlobStoreUtil's getSnapshotIndex

---

samza-core/src/main/scala/org/apache/samza/storage/ContainerStorageManager.java
samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java

**Symptom**: 
If an external utility attempts to reset a job's state by clearing backups and checkpoints, the local state still remains. We need to clear the local rocksdb state of stateful jobs, if the inputs checkpoints don't exist.
**Changes**:
- This PR checks if the input checkpoints for a container are empty and clears the local logged stores if they are.
**Tests**:
- ./gradlew build
- Added unit test in `TestContainerStorageManager` to verify that stores are deleted from logged store dir on empty checkpoints
- Tested with a test job which had its checkpoints and backup cleared.
```
2024-12-18 17:57:55.891 [main] ContainerStorageManager [INFO] No checkpoints read. Attempting to clear logged stores.
2024-12-18 17:57:55.891 [main] ContainerStorageManager [INFO] Clearing store dir …
```

Clear local logged stores if input checkpoints are empty

---

samza-shell/src/main/bash/run-class.sh
samza-shell/src/main/bash/run-framework-class.sh

This PR contains fixes to several concurrency related issues when `run-class.sh` and `run-framework-class.sh` is used on samza-yarn.
BUG=[SAMZA-2804](https://issues.apache.org/jira/browse/SAMZA-2804)
A race condition exists when setting up the classpath during container launch.
During container launch using samza-yarn, run-class.sh creates a pathing jar file (which holds the classpath for the container launch). However, during the creation of this pathing jar, temporary files, as well as the pathing jar itself is not placed in a location unique to the container. This results in multiple containers writing to the same pathing jar location and temporary file location, which results in a race condition.
This race condition may show up in several ways, such as when Yarn removes jars from a …

SAMZA-2804: Concurrency issues identified in run-class.sh on samza-yarn
