apache/samza

samza-sql-shell/src/main/java/org/apache/samza/sql/client/impl/SamzaExecutor.java, samza-sql-shell/src/main/java/org/apache/samza/sql/client/interfaces/QueryResult.java
After https://issues.apache.org/jira/browse/SAMZA-2079 is fixed, we can revert this PR.
Pass the current unit tests.
Test all Shell comments in Shell.
=> SAMZA-2093: make Sql Shell not depend on result schemas

samza-autoscaling/src/main/java/org/apache/samza/autoscaling/deployer/ConfigManager.java, samza-autoscaling/src/main/java/org/apache/samza/autoscaling/utils/YarnUtil.java, samza-autoscaling/src/test/java/org/apache/samza/autoscaling/utils/YarnUtilTest.java
1. Visibility of several methods has been narrowed to private
2. Javadoc -> block comment
3. log entries correction
4. simplification for a few expressions
=> SAMZA-2101: code cleanup and refactoring - samza-autoscaling module

samza-azure/src/main/java/org/apache/samza/coordinator/AzureLock.java, samza-azure/src/main/java/org/apache/samza/coordinator/scheduler/LeaderLivenessCheckScheduler.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/EventHubClientManager.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/admin/EventHubSystemAdmin.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/consumer/EventHubIncomingMessageEnvelope.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/consumer/EventHubSystemConsumer.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/descriptors/EventHubsInputDescriptor.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/descriptors/EventHubsOutputDescriptor.java, samza-azure/src/main/java/org/apache/samza/system/eventhub/descriptors/EventHubsSystemDescriptor.java, samza-azure/src/main/java/org/apache/samza/util/BlobUtils.java, samza-azure/src/test/java/org/apache/samza/checkpoint/azure/ITestAzureCheckpointManager.java
1. Removed deprecated junit.framework.Assert
2. Add final modifiers
3. Remove redundant things (L literal, modifiers, local variables)
4. Optional.of -> Optional.ofNullable
5. Few methods are simplified
=> SAMZA-2102: [samza-azure] code cleanup and refactoring

gradle.properties, samza-test/src/main/config/join/README, samza-test/src/main/python/configs/tests.json, samza-test/src/main/python/stream_processor.py
Change versions as per RELEASE.md
=> Update Samza version for 1.1.0 release branch

samza-test/src/main/scala/org/apache/samza/test/performance/TestKeyValuePerformance.scala
Running the TestJeyValuePerformance test results in the following failure:
```
2019-03-19 11:16:36.713 [main] TestKeyValuePerformance$ [INFO] Running test: rocksdb-write-performance
Exception in thread "main" java.lang.IllegalArgumentException: Job name is not defined in configuration
at org.apache.samza.context.JobContextImpl.fromConfigWithDefaults(JobContextImpl.java:49)
at org.apache.samza.test.performance.TestKeyValuePerformance$$anonfun$invokeTest$2$$anonfun$apply$1.apply$mcVI$sp(TestKeyValuePerformance.scala:126)
at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
at org.apache.samza.test.performance.TestKeyValuePerformance$$anonfun$invokeTest$2.apply(TestKeyValuePerformance.scala:114)
at org.apache.samza.test.performance.TestKeyValuePerformance$$anonfun$invokeTest$2. …
```
=> SAMZA-2133: Fix the TestKeyValuePerformance test.

docs/learn/documentation/versioned/deployment/standalone.md, docs/learn/tutorials/versioned/deploy-samza-job-from-hdfs.md, docs/learn/tutorials/versioned/deploy-samza-to-CDH.md, docs/learn/tutorials/versioned/hello-samza-high-level-yarn.md, docs/learn/tutorials/versioned/hello-samza-high-level-zk.md, docs/learn/tutorials/versioned/remote-debugging-samza.md, docs/learn/tutorials/versioned/run-in-multi-node-yarn.md, docs/learn/tutorials/versioned/samza-rest-getting-started.md, docs/startup/download/index.md, docs/startup/hello-samza/versioned/index.md, gradle.properties, samza-test/src/main/config/join/README, samza-test/src/main/python/configs/tests.json
Updated hard coded version for the upcoming release
As per https://github.com/apache/samza/blob/master/docs/README.md
=> Release version updates

docs/startup/download/index.md
@shanthoosh @jagadish-v0 Added tools downloads link
=> Add 1.1.0 tools download page

docs/learn/tutorials/versioned/deploy-samza-job-from-hdfs.md, docs/learn/tutorials/versioned/deploy-samza-to-CDH.md, docs/learn/tutorials/versioned/hello-samza-high-level-code.md, docs/learn/tutorials/versioned/hello-samza-high-level-yarn.md, docs/learn/tutorials/versioned/hello-samza-high-level-zk.md, docs/learn/tutorials/versioned/run-in-multi-node-yarn.md, docs/learn/tutorials/versioned/samza-event-hubs-standalone.md, docs/learn/tutorials/versioned/samza-rest-getting-started.md, docs/startup/download/index.md, docs/startup/hello-samza/versioned/index.md
@vjagadish @shanthoosh  Followed the instructions as per https://github.com/apache/samza/blob/master/docs/README.md#release-new-version-website-checklist
Please let me know if I need to update the download version with 1.1.0 as well.
=> Update website for 1.1.0

samza-sql/src/main/java/org/apache/samza/sql/avro/AvroRelConverter.java
Misc fixes that are made in internal copy of AvroRelConverter.
=> Moving the Fixes from internal AvroRelConverter

docs/_config.yml, docs/startup/download/index.md
* Update the release variable in config.yml to generate javadocs.
* Update the index.md to point to 1.1-src url that would allow users to download the samza-1.1 source.
=> SAMZA-2150: Update the config/index.md for 1.1 release.

samza-core/src/main/java/org/apache/samza/runtime/ApplicationRunnerMain.java
Straight forward and a net win. Let me know if the community reject a solo "changes without functionality".
=> Add generic type info in ApplicationRunnerMain

samza-core/src/main/java/org/apache/samza/zk/ZkJobCoordinator.java, samza-core/src/main/scala/org/apache/samza/job/JobRunner.scala, samza-core/src/main/scala/org/apache/samza/util/CoordinatorStreamUtil.scala, samza-core/src/test/scala/org/apache/samza/util/TestCoordinatorStreamUtil.scala
The purpose of this RB is to ensure the CoordinatorStreamStore initialization and stream creation are consistent.
=> SAMZA-2181: Ensure consistency of coordinator store creation and initialization

samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java
=> SAMZA-2194:Disable flaky test in samza-sql

samza-api/src/main/java/org/apache/samza/operators/MessageStream.java, samza-api/src/main/java/org/apache/samza/table/Table.java, samza-api/src/main/java/org/apache/samza/table/descriptors/TableDescriptor.java, samza-core/src/main/java/org/apache/samza/operators/MessageStreamImpl.java, samza-core/src/main/java/org/apache/samza/operators/impl/SendToTableOperatorImpl.java, samza-core/src/main/java/org/apache/samza/operators/impl/StreamTableJoinOperatorImpl.java, samza-core/src/main/java/org/apache/samza/operators/spec/OperatorSpecs.java, samza-core/src/main/java/org/apache/samza/operators/spec/SendToTableOperatorSpec.java, samza-core/src/main/java/org/apache/samza/operators/spec/StreamTableJoinOperatorSpec.java, samza-core/src/test/java/org/apache/samza/operators/impl/TestStreamTableJoinOperatorImpl.java, samza-core/src/test/java/org/apache/samza/operators/spec/TestOperatorSpec.java, samza-test/src/test/java/org/apache/samza/test/table/TestRemoteTableEndToEnd.java
As per subject, this is a follow-up of SAMZA-2185
=> SAMZA-2200: Update table sendTo() and join() operation to accept args

samza-kv-couchbase/src/main/java/org/apache/samza/table/remote/couchbase/BaseCouchbaseTableFunction.java, samza-kv-couchbase/src/main/java/org/apache/samza/table/remote/couchbase/CouchbaseTableWriteFunction.java
Minor refactoring
1. Made java.util.concurrent.Timeout to be retriable
2. Allow CouchbaseTableWriteFunction.asyncWriteHelper() to return a CompletableFuture with value
=> SAMZA-2217: Refactoring of Couchbase table functions

samza-api/src/test/java/org/apache/samza/table/TestBaseTableDescriptor.java, samza-api/src/test/java/org/apache/samza/table/remote/TestTableRateLimiter.java, samza-core/src/main/java/org/apache/samza/table/batching/AsyncBatchingTable.java, samza-core/src/main/java/org/apache/samza/table/batching/BatchProcessor.java, samza-core/src/main/java/org/apache/samza/table/remote/DummyTableReadFunction.java, samza-core/src/main/java/org/apache/samza/table/remote/NoOpTableReadFunction.java, samza-kv-couchbase/src/test/java/org/apache/samza/table/remote/couchbase/TestCouchbaseBucketRegistry.java, samza-kv-inmemory/src/test/java/org/apache/samza/storage/kv/inmemory/TestInMemoryTableDescriptor.java, samza-kv-rocksdb/src/test/java/org/apache/samza/storage/kv/descriptors/TestRocksDbTableDescriptor.java, samza-kv/src/main/java/org/apache/samza/storage/kv/LocalTable.java, samza-kv/src/main/java/org/apache/samza/storage/kv/LocalTableProvider.java, samza-test/src/test/java/org/apache/samza/test/table/TestCouchbaseRemoteTableEndToEnd.java, samza-test/src/test/java/org/apache/samza/test/table/TestRemoteTableEndToEnd.java
This is a convenience class for cases only writes are required.
Removed compilation warnings from various files.
=> SAMZA-2219: Add a dummy table read function

samza-test/src/main/python/stream_processor.py, samza-test/src/main/python/tests/zk_client.py
This PR is comprised of the following changes:
* Updated the version number in the samza executable. 
* Updated the zookeeper base-path.
=> SAMZA-2225: Update configurations in standalone integration tests.

samza-sql/src/test/java/org/apache/samza/sql/util/MyTestObjUdf.java
Missed this file in this PR https://github.com/apache/samza/pull/1060.
=> SAMZA-2230: Fix for the compilation error

samza-core/src/main/java/org/apache/samza/system/inmemory/InMemoryManager.java, samza-test/src/test/java/org/apache/samza/test/framework/StreamTaskIntegrationTest.java
- Fixed the untested code path
- Fixed the bug in InMemoryManager
=> SAMZA-2291: Custom IME Put in InMemoryManager runs into Offset mismatch even if offsets are correctly set

samza-test/src/test/java/org/apache/samza/test/harness/InMemoryIntegrationTestHarness.java, samza-test/src/test/java/org/apache/samza/test/samzasql/SamzaSqlIntegrationTestHarness.java, samza-test/src/test/java/org/apache/samza/test/samzasql/TestSamzaSqlEndToEnd.java
Reduces build time by about 2 minutes
=> SAMZA-2306: Use in-memory system for SQL tests in samza-test

docs/_case-studies/slack.md
"Monitoring" was spelt "monitoiring."
=> [Docs] Fix typo in Slack case study

samza-yarn/src/main/java/org/apache/samza/config/YarnConfig.java, samza-yarn/src/main/scala/org/apache/samza/job/yarn/ClientHelper.scala
Since my original PR (https://github.com/apache/samza/pull/988) got messed up. Opening this new one. Please take a look at the original PR for comments.
=> SAMZA-2160 - Ability to configure application type on YARN deploys

samza-core/src/main/java/org/apache/samza/execution/JobNodeConfigurationGenerator.java, samza-core/src/main/java/org/apache/samza/runtime/ApplicationRunnerUtil.java, samza-core/src/main/java/org/apache/samza/util/ConfigUtil.java, samza-core/src/main/scala/org/apache/samza/job/JobRunner.scala, samza-core/src/test/java/org/apache/samza/util/TestConfigUtil.java, samza-test/src/main/java/org/apache/samza/test/integration/LocalApplicationRunnerMain.java
Refactor rewriterConfig to Java code, so it can be used in Beam and Yarn.
=> SAMZA-2358: refactor rewriterConfig to java

gradle.properties
Builds and publishes correct artifacts.
Verified that `samza-hello-samza` builds and deploys fine with these published artifacts.
=> Upgrade Gradle to 5.2.1

samza-core/src/main/java/org/apache/samza/clustermanager/ContainerAllocator.java, samza-core/src/main/java/org/apache/samza/clustermanager/ContainerManager.java, samza-core/src/main/java/org/apache/samza/clustermanager/ContainerProcessManager.java, samza-core/src/test/java/org/apache/samza/clustermanager/MockContainerAllocatorWithHostAffinity.java, samza-core/src/test/java/org/apache/samza/clustermanager/MockContainerAllocatorWithoutHostAffinity.java, samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java, samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithoutHostAffinity.java, samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerProcessManager.java
When #1180 was merged it was not squashed which screwed the commit log for master branch. So  #1208 was opened to revert that merge to have a cleaner the commit log. 
This PR just puts the feature again as one commit, but then actual review and comments are present at #1180
=> SAMZA-2340: [Container Placements] Introduce ContainerManager for handling validation for failures & starts of active & standby containers

docs/learn/documentation/versioned/jobs/configuration-table.html
=> SAMZA-2380:fixed a typo in the config table doc

samza-core/src/main/java/org/apache/samza/execution/JobPlanner.java
Currently the batch mode in job planner is computed based on the userconfig. This should be changed after the Samza InputDescriptor change. We should compute that based on the generated configs now.
Also add the logic to remove host affinity config for batch mode.
=> SAMZA-2377: Batch mode should be computed based on generated configs

gradle.properties
=> Update gradle properties to mark 1.4.0 as the next version

bin/setup-int-test.sh, samza-api/src/main/java/org/apache/samza/config/MapConfig.java, samza-core/src/main/java/org/apache/samza/coordinator/stream/CoordinatorStreamWriter.java, samza-core/src/main/java/org/apache/samza/storage/StateStorageTool.java, samza-core/src/main/java/org/apache/samza/storage/StorageRecovery.java, samza-core/src/main/scala/org/apache/samza/checkpoint/CheckpointTool.scala, samza-core/src/main/scala/org/apache/samza/coordinator/stream/CoordinatorStreamWriterCommandLine.scala, samza-core/src/main/scala/org/apache/samza/util/CommandLine.scala, samza-core/src/test/java/org/apache/samza/runtime/TestApplicationRunnerMain.java, samza-core/src/test/scala/org/apache/samza/checkpoint/TestCheckpointTool.scala, samza-core/src/test/scala/org/apache/samza/job/TestJobRunner.scala, samza-kv-rocksdb/src/main/java/org/apache/samza/storage/kv/RocksDbReadingTool.java, samza-rest/src/main/java/org/apache/samza/rest/SamzaRestService.java, samza-test/src/main/config/join/checker.samza, samza-test/src/main/config/join/common.properties, samza-test/src/main/config/join/emitter.samza, samza-test/src/main/config/join/joiner.samza, samza-test/src/main/config/join/watcher.samza, samza-test/src/main/java/org/apache/samza/test/integration/LocalApplicationRunnerMain.java
This reverts commit 1a03a6a9b8ed19129305842744d6619277bb72f6.
Reverting this change for the 1.4.0 branch since it is backwards incompatible and we don't want to release this for 1.4.
=> Revert "SAMZA-2420: Update CommandLine to use config loader for local config file (#1256)"

docs/startup/hello-samza/versioned/index.md
Samza-hello-world master points to stable samza releases.
Samza-hello-world ltest points to stable samza master.
Doc needs to reflect that.
=> Updating hello-world open source instructions

samza-core/src/main/java/org/apache/samza/clustermanager/ClusterResourceManager.java, samza-core/src/main/java/org/apache/samza/clustermanager/ContainerAllocator.java, samza-core/src/main/java/org/apache/samza/clustermanager/ContainerManager.java, samza-core/src/main/java/org/apache/samza/clustermanager/SamzaResource.java, samza-core/src/test/java/org/apache/samza/clustermanager/MockClusterResourceManager.java, samza-core/src/test/java/org/apache/samza/clustermanager/TestContainerAllocatorWithHostAffinity.java, samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java
=> Revert "SAMZA-2475: Add a allocated resource expiry timeout in samza yarn type of apps"

RELEASE.md, docs/README.md
I just did the Samza 1.4.0 release, and I found some areas which could be clarified in the release instructions.
=> [Documentation] clarifying some of the release instructions

samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java, samza-core/src/main/java/org/apache/samza/runtime/LocalContainerRunner.java
Move setting logging context to the code that gets executed by both Beam and non-Beam applications.
=> SAMZA-2513:Mdc for beam

docs/_config.yml, docs/learn/tutorials/versioned/hello-samza-high-level-code.md, docs/learn/tutorials/versioned/hello-samza-high-level-yarn.md, docs/learn/tutorials/versioned/hello-samza-high-level-zk.md, docs/learn/tutorials/versioned/samza-rest-getting-started.md, docs/startup/hello-samza/versioned/index.md
**Changes**: Documentation update related to 1.5.0 release
=> [DOCS] Update version in the docs for 1.5.0 release

docs/_blog/2020-08-28-announcing-the-release-of-apache-samza--1.5.1.md, docs/_config.yml, docs/_menu/index.html, docs/_releases/1.5.1.md, docs/archive/index.html, docs/startup/download/index.md
**Changes**:
Release blog for 1.5.1
Other 1.5.1 documentation changes
=> [DOCS] Update the docs & blogs for 1.5.1 release

samza-test/src/main/config/join/README, samza-test/src/main/python/configs/tests.json, samza-test/src/main/python/stream_processor.py
**Description**: Bump the versions used in test to the latest master branch version for 1.5.0 release
**Tests**: None
=> [Minor] Update the tests to use the master branch version for 1.5.0 release

gradle/dependency-versions.gradle
Changes: Upgrading RocksDb version for OSS
Tests: clean build
=> SAMZA-2608: Updating the RocksDb version for Samza 1.6 release

docs/learn/documentation/versioned/container/metrics-table.html, samza-core/src/main/java/org/apache/samza/container/ContainerHeartbeatMonitor.java, samza-core/src/main/java/org/apache/samza/coordinator/JobCoordinatorMetadataManager.java, samza-core/src/main/java/org/apache/samza/runtime/ContainerLaunchUtil.java, samza-core/src/test/java/org/apache/samza/container/TestContainerHeartbeatMonitor.java, samza-core/src/test/java/org/apache/samza/coordinator/TestJobCoordinatorMetadataManager.java, samza-yarn/src/main/java/org/apache/samza/job/yarn/YarnClusterResourceManager.java, samza-yarn/src/main/scala/org/apache/samza/job/yarn/SamzaAppMasterMetrics.scala, samza-yarn/src/test/java/org/apache/samza/job/yarn/TestYarnClusterResourceManager.java, samza-yarn/src/test/java/org/apache/samza/webapp/TestApplicationMasterRestClient.java
Description:
Application Master High Availability feature was introduced as part of PRs: #1442, #1448, #1449 and #1450. We add the relevant metrics for the components introduced as part of AM HA.
Changes:
- Metrics for Dynamic Container Heartbeat mechanism
- Refactored ContainerHeartbeatMonitor to take config object
- Metrics clean up for metadata management
- Metrics documentation update
- Additional metrics for Application Master to track the number of containers carried from previous attempt
Tests:
- Updated the unit tests for container heartbeat monitor
- Updated the tests for job coordinator metadata manager
- Updated YarnResourceClusterManager tests
Usage Instructions: The metrics should be available by default for jobs that have AM HA …
=> SAMZA-2615: Metrics for Application Master High Availability

docs/README.md
seems like the instructions in the README.md do not match the directory structure.
changed samza/docs/.. to docs/..
=> updated README. Made it to match the directory structure

docs/_committers/ke-wu.md
Trivial commit to test committer workflow
=> SAMZA-2624: Add Ke Wu to committer page

samza-core/src/main/java/org/apache/samza/task/StreamOperatorTask.java, samza-core/src/test/java/org/apache/samza/task/TestStreamOperatorTask.java
**Symptom**: 
Samza job fails with a TaskCallbackTimeoutException if InputOperator is not found in OperatorGraph for a SystemStream
**Cause:** 
Currently, the pipeline silently fails when there is no InputOperator for a SystemStream in the OperatorGraph as the code doesn't handle such cases. The pipeline just silently fails and the job would throw an exception due to sync task callback timeout (TaskCallbackTimeoutException).
One of the scenarios that causes this is due to non-determinism in the plan seen by the containers and the AM. It can happen in multiple scenarios where the transform/operators have non-determinism in generating their names. e.g. we noticed beam transform appended hashcode.
**Changes:** 
Call `failure` method of the TaskCallback with a SamzaException with the …
=> SAMZA-2641: Do not silently fail when InputOperator is not found in OperatorGraph for a SystemStream

samza-azure/src/main/java/org/apache/samza/system/azureblob/producer/AzureBlobSystemProducer.java
Symptom: Azure blob system producer fails to authenticate with blob storage using token credential
Cause: the azure service principal used by the samza job can potentially have different roles - some roles can create containers and upload but not not fetch azure account info
Changes: allow failures when trying to validate that the flush threshold size if supported by the account type (standard vs premium) 
Tests: Azure sdk classes (BlobServiceAsyncClient) if final and can not be mocked. To add a unit test, the already small method will need to be further divvied up to extract BlobServiceAsyncClient into a single line helper. As this is only a try catch and log change, not adding unit test.
Usage/upgrade instructions: N/A
Backwards compatible: yes
=> SAMZA-2668: AzureBlobSystemProducer: using TokenCredential throws ResourceNotFound 404 when establishing connection

samza-core/src/main/java/org/apache/samza/container/host/PosixCommandBasedStatisticsGetter.java
Symptom: Some samza job will crash due to YARN PMEM error despite the physical-memory-mb is much lower than the container size. 
Cause: Current physical-memory-mb metric only calculates the RSS memory of the java process that runs the application but ignores all its child processes, including those that load tensorflow models and take a lot of memory.
Changes: Get all the child processes of the java process that runs the application, and sum their RSS memory with the RSS memory of the java process as the physical-memory-mb of the container.
Test: unit tests
Tested with samza-hello-samza
=> Include memory usage of child processes in physical-memory-mb metric

samza-api/src/main/java/org/apache/samza/container/grouper/stream/SystemStreamPartitionGrouper.java
Changes: Removed wildcard import from SystemStreamPartitionGrouper.
@bringhurst
=> SAMZA-2680: Remove wildcard import

samza-api/src/main/java/org/apache/samza/util/Clock.java, samza-core/src/main/java/org/apache/samza/storage/StorageRecovery.java, samza-core/src/main/java/org/apache/samza/util/HighResolutionClock.java, samza-core/src/main/java/org/apache/samza/util/SystemClock.java, samza-core/src/main/java/org/apache/samza/util/SystemHighResolutionClock.java, samza-core/src/main/java/org/apache/samza/util/ThrottlingExecutor.java, samza-core/src/main/java/org/apache/samza/util/ThrottlingScheduler.java, samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala, samza-core/src/test/java/org/apache/samza/operators/TestJoinOperator.java, samza-core/src/test/scala/org/apache/samza/storage/TestContainerStorageManager.java, samza-kafka/src/main/scala/org/apache/samza/system/kafka/KafkaSystemFactory.scala, samza-kafka/src/test/java/org/apache/samza/storage/TestTaskStorageManager.scala, samza-kafka/src/test/java/org/apache/samza/system/kafka/TestKafkaSystemConsumer.java
Issues: Improve the usability of clock related interface/classes
Changes:
1. Move SystemClock from scala to java
2. Enrich SystemHighResolutionClock for ease of use
3. Add comments to Clock
API Changes: N/A
Upgrade Instructions: N/A
Usage Instructions: N/A
=> SAMZA-2753: Consolidate Clocks

samza-core/src/main/java/org/apache/samza/storage/blobstore/util/DirDiffUtil.java
It's possible that the group permissions for the restored file may not match the uploaded file. E.g., if the file is restored to a directory with different default permissions for new files than the original directory. We only really care about the permissions for the owner, so relaxing the post-restore verification to only check them.
=> Only verify permissions for file owner after blob store restore.

samza-core/src/main/java/org/apache/samza/coordinator/metadatastore/CoordinatorStreamStore.java, samza-core/src/main/java/org/apache/samza/execution/JobPlanner.java, samza-core/src/main/scala/org/apache/samza/container/SamzaContainer.scala, samza-core/src/main/scala/org/apache/samza/metrics/JmxServer.scala, samza-core/src/main/scala/org/apache/samza/util/Logging.scala
Config maps can be quite large. Remove duplicate / unnecessary logging for configs.
=> Removed unnecessary logging for configs

docs/_includes/footer.html
See https://issues.apache.org/jira/browse/SAMZA-2803
=> SAMZA-2803 Remove Google Analytics from the Samza Website
